### PR TITLE
lazily import multiprocessing.Pool in MapWrapper 

### PR DESCRIPTION
**Pull request by graingert**
#### What does this implement/fix?
@andyfaff rationale for late multiprocessing import: bugs.python.org/issue32596

### CODE REVIEW

**Comment by andyfaff** [comment]
Could you provide a rationale for why this is an improvement over the existing code?
I did some experimenting in the past that showed that ProcessPoolExecutor was slower (I'll try and find it).

**Comment by andyfaff** [comment]
```
import numpy as np
from concurrent.futures import ProcessPoolExecutor
from multiprocessing import Pool as Pool
import cmath


x = np.linspace(-100, 100, 100).astype(np.complex128)


def t(x):
     return np.sqrt(x)


def u(p, x):
    yp = np.array(list(p.map(cmath.sqrt, x)))
    return yp


def v(p, x):
    yp = np.array(list(p.map(cmath.sqrt, x)))
    return yp
```
```
>>> %timeit t(x)
2.04 µs ± 12 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
>>> with Pool(None) as p:
        %timeit u(p, x)
1.35 ms ± 30.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
>>> with ProcessPoolExecutor(None) as p:
         %timeit v(p, x)
19.5 ms ± 660 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
Sorry about the formatting. The example is a little artificial because it's better to just to call the numpy function directly. However, `ProcessPoolExecutor` still seems to take an inordinate time longer than `Pool` to perform the calculations.

**Comment by habnabit** [comment]
the original rationale for this is that I was (trying to) use scipy in an environment where `multiprocessing` has been explicitly patched out because of its bad behavior. not even attempting (or wanting) to use scipy in a multiprocessing context but a transitive import several levels deep originating from `import scipy.signal`.

**Comment by andyfaff** [comment]
At the moment the performance of `ProcessPoolExecutor` *seems* to be a lot poorer compared to `Pool`, and I'd be reluctant to make the change because it'll result in degraded speed.

What is the bad behaviour of `multiprocessing` you mention? Does import `scipy.signal` end up importing `scipy._lib._util`? Is the bad behaviour observed just from the import? What goes wrong from the import? (I'm making a lot of assumptions here)

`MapWrapper` could be moved to a separate file, which could be a band aid solution, but let's see if we can't tackle the root cause.

**Comment by graingert** [comment]
the problem is ProcessPoolExecutor uses a default chunksize of 1


```
import os
import attr
import contextlib
import timeit
import builtins
import sys
import numpy as np
from concurrent.futures import ProcessPoolExecutor
from multiprocessing import Pool
import cmath
import functools


x = np.linspace(-100, 100, 100).astype(np.complex128)


def t(x):
    return np.sqrt(x)


def u(p, x):
    yp = np.array(list(p.map(cmath.sqrt, x)))
    return yp


@attr.frozen
class ChunkyPool:
    _pool: ProcessPoolExecutor
    _max_workers: int

    @classmethod
    @contextlib.contextmanager
    def create(cls):
        max_workers = os.cpu_count()
        with ProcessPoolExecutor(max_workers) as pool:
            yield cls(pool=pool, max_workers=max_workers)

    def map(self, fn, iterable, chunksize=None):
        if not hasattr(iterable, "__len__"):
            iterable = list(iterable)

        if chunksize is None:
            chunksize, extra = divmod(len(iterable), self._max_workers * 4)
            if extra:
                chunksize += 1
        if len(iterable) == 0:
            chunksize = 0

        return self._pool.map(fn, iterable, chunksize=chunksize)

```




```
Python 3.8.2 (default, Jul 16 2020, 14:00:26) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.18.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from bench_pool import *

In [2]: with ChunkyPool.create() as p:
   ...:     %timeit u(p, x)
   ...: 
3.73 ms ± 125 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [3]: with Pool() as p:
   ...:     %timeit u(p, x)
   ...: 
2.34 ms ± 108 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [4]: with ProcessPoolExecutor() as p:
   ...:     %timeit u(p, x)
   ...: 
14.9 ms ± 1.89 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)

```

**Comment by andyfaff** [comment]
I wonder why `ProcessPoolExecutor.map` doesn't use the same chunksize as `Pool.map`?

I wonder what the underlying issue is with `multiprocessing.Pool`.

**Comment by graingert** [comment]
> I wonder what the underlying issue is with multiprocessing.Pool

they're about the same when you set a sensible chunksize

**Comment by andyfaff** [comment]
Sorry, I meant why are these mods needed in the first place?

> the original rationale for this is that I was (trying to) use scipy in an environment where multiprocessing has been explicitly patched out because of its bad behavior

What is that bad behaviour?

**Comment by graingert** [comment]
@andyfaff rationale for late multiprocessing import: https://bugs.python.org/issue32596

**Comment by andyfaff** [comment]
So the issue is that `multiprocessing.Pool` is a slow import?

With the toy issue above `ChunkyPool` is still on the order of 60% longer than `Pool`. It's unclear to me how that overhead would change for the different problems `MapWrapper` is used for; for some problems it might be negligible, for others it might be important.
However, slow import times are also a performance issue. I wonder if splitting out MapWrapper into its own file (and using that lazy import mechanism) would help?

**Comment by andyfaff** [comment]
(sorry pressed close instead of comment, the buttons are relatively close)

**Comment by andyfaff** [comment]
Another alternative is just do the import of `multiprocessing.Pool` in `MapWrapper`. Not usually a fan of that, but it's only a one-off

**Comment by graingert** [comment]
Defining MapWrapper lazily means people won't be able to use it without importing multiprocessing. Importing multiprocessing.Pool only when no mapper is passed will allow consumers to always pass a mapper to never import multiprocessing

File: scipy/_lib/_util.py [hunk 1]
```diff
@@ -367,6 +366,7 @@ def __init__(self, pool=1):
             self.pool = pool
             self._mapfunc = self.pool
         else:
+            from multiprocessing import Pool
```
Comment (larsoner) [inline scipy/_lib/_util.py:369]: Can you add a comment linking to this page and optionally a short description for the rationale, like:
```suggestion
            # importing multiprocessing at the top level can be slow,
            # see https://github.com/scipy/scipy/pull/12872
            # and https://bugs.python.org/issue32596
            from multiprocessing import Pool
```

**Review by larsoner — COMMENTED** [review]
+1 for nested import, seems like a low-cost reasonable-benefit solution

The only other place in non-test code where I see an un-nested `multiprocessing` import is `scipy/spatial/ckdtree.pyx`. Not sure if it's worth nesting that one, too.

**Review by larsoner — APPROVED** [review]

File: scipy/spatial/ckdtree.pyx [hunk 2]
```diff
@@ -18,8 +18,7 @@ from libcpp.algorithm cimport sort
 from libcpp cimport bool
 
 cimport cython
-
-from multiprocessing import cpu_count
+from os import cpu_count
```
Comment (graingert) [inline scipy/spatial/ckdtree.pyx:21]: this is slightly different, os.cpu_count returns an Optional[int] but multiprocessing.cpu_count raises RuntimeError rather than return None

Comment (graingert) [reply scipy/spatial/ckdtree.pyx:21]: I don't know how `cdef int number_of_processors = cpu_count()` handles errors here

Comment (graingert) [reply scipy/spatial/ckdtree.pyx:21]: @andyfaff `cdef int number_of_processors = cpu_count() or -1` ?

Comment (graingert) [reply scipy/spatial/ckdtree.pyx:21]: @larsoner I dismissed your review to draw your attention to this

Comment (larsoner) [reply scipy/spatial/ckdtree.pyx:21]: we could write a little wrapper that maintains current behavior:

https://stackoverflow.com/questions/53537230/difference-between-multiprocessing-cpu-count-and-os-cpu-count#answer-53537394

So something like:

```
def _cpu_count():
        num = os.cpu_count()
        if num is None:
            raise NotImplementedError('cannot determine number of cpus')
        else:
            return num
```

Comment (graingert) [reply scipy/spatial/ckdtree.pyx:21]: I'm not familiar with cpython, how does it handle exceptions at c-extension setup time?

Can you push the change?

Comment (larsoner) [reply scipy/spatial/ckdtree.pyx]: done

File: scipy/spatial/ckdtree.pyx [hunk 3]
```diff
@@ -400,7 +398,12 @@ cdef np.intp_t get_num_workers(workers: object, kwargs: dict) except -1:
 
     cdef np.intp_t n = operator.index(workers)
     if n == -1:
-        n = number_of_processors
+        num = os.cpu_count()
+        if num is None:
+            raise NotImplementedError(
+                'Cannot determine the number of cpus using os.cpu_count(), '
+                'cannot use -1 for the number of workers')
+        n = num
```
Comment (larsoner) [inline scipy/spatial/ckdtree.pyx:406]: @peterbell10 can you check to make sure these cKDTree changes are reasonable?

File: scipy/spatial/tests/test_kdtree.py [hunk 4]
```diff
@@ -520,6 +521,10 @@ def test_n_jobs():
     with pytest.raises(TypeError, match="Unexpected keyword argument"):
         T.query(points, 1, workers=1, n_jobs=1)
 
+    monkeypatch.setattr(os, 'cpu_count', lambda: None)
+    with pytest.raises(NotImplementedError, match="Cannot determine the"):
+        T.query(points, 1, workers=-1)
```
Comment (peterbell10) [inline scipy/spatial/tests/test_kdtree.py:526]: This function is specifically testing the `n_jobs` argument. This belongs in `test_ckdtree_parallel`.

File: scipy/spatial/ckdtree.pyx (hunk 2 above)
Comment (graingert) [reply scipy/spatial/ckdtree.pyx]: Thanks!

**Comment by larsoner** [comment]
@graingert we're working on finishing things up for 1.6.0, any time to make the last change requested here?

**Comment by graingert** [comment]
I'm a bit busy at the moment, does it just need moving to a different file?

**Comment by larsoner** [comment]
> I'm a bit busy at the moment, does it just need moving to a different file?

Looks like `test_ckdtree_parallel` is in the same file, so just moved to a different part of the same file

**Comment by larsoner** [comment]
Actually it looks like @peterbell10's comment is on some code I modified, so I'll move it!

**Comment by larsoner** [comment]
Okay push-forced an updated version with the test in the place @peterbell10 suggested. Should be ready for rebase+merge @peterbell10

**Comment by andyfaff** [comment]
I'm happy with the MapWrapper changes.

**Review by peterbell10 — APPROVED** [review]

**Comment by peterbell10** [comment]
Thanks @graingert, merged.
