### ISSUE TITLE
DOC: publicly expose `multivariate_normal` attributes `mean` and `cov`

### ISSUE THREAD

**Issue by jacopok** [scipy/scipy#17896]
### Issue with current documentation:

In scipy 1.9.3, the following code was valid and printed the covariance matrix of the distribution:

```
from scipy import stats
distribution = stats.multivariate_normal([0, 0], [[1, 0], [0, 1]])
print(distribution.cov)
```

In scipy 1.10.0, this gives the error
`AttributeError: 'multivariate_normal_frozen' object has no attribute 'cov'`
and in order to access the covariance from the frozen distribution the approach I found to work is 

```
from scipy import stats
distribution = stats.multivariate_normal([0, 0], [[1, 0], [0, 1]])
print(distribution.cov_object.covariance)
```

which does not work in scipy 1.9.3.
None of this is documented in the [docs](https://scipy.github.io/devdocs/reference/generated/scipy.stats.multivariate_normal.html#scipy-stats-multivariate-normal), neither is the change reported in the [changelog](https://github.com/scipy/scipy/releases/tag/v1.10.0).

### Idea or request for content:

It seems useful to document the [cov_object](https://github.com/scipy/scipy/blob/5beeda995449c55332ce141cad1be77621789f31/scipy/stats/_multivariate.py#L833) attribute of the frozen distribution somewhere; alternatively, to add a convenience `rv.cov` property redirecting to `rv.cov_object.covariance` for backwards compatibility.

**Comment by mdhaber** [comment]
I'm unable to find documentation of a `cov` attribute. It is the name of a parameter accepted by `multivariate_normal` methods, but I don't think it's guaranteed to be accessible as an attribute. That said, there have been requests (at least for univariate distributions) to make shape, location, and scale parameters available as attributes for all distributions.

**Comment by jacopok** [comment]
Indeed, I have not been able to find documentation for `cov`  being available as an attribute in the API, but I think it should be.

They (`mean` and `cov`) seem like simple enough attributes to make available as part of the API since they have to be stored anyway - I am willing to start a PR with some tests and documentation for this additional feature.
Shall I rename this issue to reflect the change?

**Comment by rkern** [comment]
The `cov` attribute is used in the `multivariate_normal_frozen` example in the docstring, so it was documented in that sense.

Note that we did change the implementation of `multivariate_normal` to allow the use of `Covariance` instances that allow for different representations of the covariance matrix (e.g. a precision matrix or a pre-factored Cholesky decomposition). That's the `cov_object`. You could restore the public `cov` attribute as a `@property` that returns `self.cov_object.covariance`, but I would not store the `cov` explicitly upon construction. Some `Covariance` implementations construct that matrix as-needed with properties; defer to that choice.

I think a PR that added explicit `Attributes` documentation for `mean`, `cov`, and `cov_object` with accompanying tests to ensure that they remain would be welcome.

**Comment by mdhaber** [comment]
> so it was documented in that sense.

I had a feeling that might be hiding somewhere. Yes, I was only looking at the rendered documentation. I didn't notice the documentation of the frozen instance you can get with `help(stats.multivariate_normal())`.

Alright, since it's documented (albeit hidden and not covered by unit tests), we can call this a bug and backport the fix in 1.10.1.
