### PR TITLE
BLD: optimize: use hidden visibility for static HiGHS libraries

### LINKED ISSUE #20256: MAINT, BLD: symbol visibility warnings on MacOS ARM static lib with clang c++17
With `meson` `1.4.0`, on latest `main` (bd42f896a), via `FC=gfortran-12 python dev.py test -j 8` I see the build output warning below, though the full suite passes otherwise. Using `Apple clang version 15.0.0 (clang-1500.3.9.4)`.

```
../scipy/_lib/highs/src/util/HighsDataStack.h:27:34: note: expanded from macro 'IS_TRIVIALLY_COPYABLE'
#define IS_TRIVIALLY_COPYABLE(T) __has_trivial_copy(T)
                                 ^
29 warnings generated.
[1477/1477] Linking target scipy/optimize/_highs/_highs_wrapper.cpython-311-darwin.so
ld: warning: direct access in function '__pyx_pymod_exec__highs_wrapper(_object*)' from file 'scipy/optimize/_highs/_highs_wrapper.cpython-311-darwin.so.p/meson-generated__highs_wrapper.cpp.o' to global weak symbol 'std::__1::piecewise_construct' from file 'scipy/optimize/_highs/libhighs.a(.._..__lib_highs_extern_filereaderlp_reader.cpp.o)' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
<snip more similar warnings>
```

Looks like static library symbol visibility is a bit annoying to fix on MacOS perhaps: https://stackoverflow.com/questions/2222162/how-to-apply-fvisibility-option-to-symbols-in-static-libraries

Bisected to commit below, C++ standards fun I guess. Perhaps gh-19255 will help with this, but not fully sure what's going on over there.

```
10c2a45586d8a169a0407efc90753ebfc0dbd626 is the first bad commit
commit 10c2a45586d8a169a0407efc90753ebfc0dbd626
Author: Lucas Colley <lucas.colley8@gmail.com>
Date:   Fri Jan 5 14:10:28 2024 +0000

    BLD: set default `cpp_std` to `c++17`
    [wheel build] [skip circle]

 meson.build                              | 2 +-
 scipy/io/_fast_matrix_market/meson.build | 1 -
 2 files changed, 1 insertion(+), 2 deletions(-)
```

### PR DESCRIPTION
**Pull request by rgommers**
This is a follow-up to gh-20477, where HiGHS wasn't touched on purpose to avoid a merge conflict in another PR.

Minor useful side benefit: it shrinks the size of `_highs_wrapper.so` by 0.4%

Closes gh-20256

After this, on macOS:
```
dyld_info -exports build/scipy/optimize/_highs/_highs_wrapper.cpython-310-darwin.so
build/scipy/optimize/_highs/_highs_wrapper.cpython-310-darwin.so [arm64]:
    -exports:
        offset      symbol
        0x0000273C  _PyInit__highs_wrapper
```

Before:
```
dyld_info -exports build/scipy/optimize/_highs/_highs_wrapper.cpython-310-darwin.so
build/scipy/optimize/_highs/_highs_wrapper.cpython-310-darwin.so [arm64]:
    -exports:
        offset      symbol
        0x0000467C  _PyInit__highs_wrapper
        0x0013B7AC  __Z10callICrashRK7HighsLpRK13ICrashOptionsR10ICrashInfo
        0x001ED6A0  __Z10first_wordRNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEi
        0x00085964  __Z10getLpCostsRK7HighsLpiiPd
...
(a ton of symbols)
```

### CODE REVIEW

**Review by lucascolley — APPROVED** [review]
LGTM, [GCC wiki](https://gcc.gnu.org/wiki/Visibility) says

> In your build system (Makefile etc), you will probably wish to add the -fvisibility=hidden and -fvisibility-inlines-hidden options to the command line arguments of every GCC invocation. 

and indeed, [`gnu_symbol_visibility: 'inlineshidden'`](https://mesonbuild.com/Reference-manual_functions.html#arguments10)

> is the same as hidden but also includes things like C++ implicit constructors as specified in the GCC manual

Thanks Ralf!
