### PR TITLE
BUG: Remove the need to specify window_size for find_peaks_cwt().

### LINKED ISSUE #12739: find_peaks_cwt has undocumented behavior when window_size is None and wavelet is ricker
From the documentation for find_peaks_cwt (window_size):
> Size of window to use to calculate noise floor. Default is cwt.shape[1] / 20.

However, when window_size is None and wavelet = ricker (default for find_peaks_cwt) this will also
trigger special case handing in scipy.signal.wavelets.cwt:
```
 if wavelet == ricker and window_size is None:
     ceil = np.ceil(N)
     if ceil != N:
         N = int(N)
```
which affects the output with my supplied input: [input.txt](https://github.com/scipy/scipy/files/5094980/input.txt).
So, in the end the result from find_peaks_cwt differs between when window_size is None and cwt.shape[1] / 20.

#### Reproducing code example:

```
>>> import json
>>> import numpy as np
>>> from scipy import signal
>>> vector = np.array(json.load(open('input.txt')))  # Attached file
>>> widths = np.linspace(1, 265)
>>> signal.find_peaks_cwt(vector, widths)
array([  22,  436,  868, 1299, 1732, 2164, 2596, 3028, 3459, 3892, 4324, 4756, 5189, 5620, 6052, 6484, 6916, 7349, 7780, 8212, 8625])
# window_size gets computed in _filter_ridge_lines to 433
>>> window_size = int(np.ceil(len(vector) / 20))
# Now, I supply this computed window_size:
>>> signal.find_peaks_cwt(vector, widths, window_size=window_size)
array([  23,  436,  868, 1300, 1732, 2164, 2596, 3028, 3460, 3892, 4325, 4757, 5189, 5621, 6053, 6485, 6917, 7349, 7781, 8213, 8626])
```

#### Scipy/Numpy/Python version information:
```
1.5.2 1.17.5 sys.version_info(major=3, minor=8, micro=5, releaselevel='final', serial=0)
```

### LINKED ISSUE #14229: find_peaks_cwt raises TypeError when using wavelet functions different than ricker
Hi I was trying to use the `find_peaks_cwt` function using other wavelets, but I get a TypeError:

```
import numpy as np
from scipy.signal.windows import gaussian
from scipy.signal import find_peaks_cwt

x = gaussian(200, 2)
widths = np.array([1, 2, 3, 4])
find_peaks_cwt(x, widths, wavelet=gaussian)
```

#### Error message:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-8-f207b53c7d51> in <module>
      5 x = gaussian(200, 2)
      6 widths = np.array([1, 2, 3, 4])
----> 7 find_peaks_cwt(x, widths, wavelet=gaussian)

~/miniconda3/envs/pycharm/lib/python3.8/site-packages/scipy/signal/_peak_finding.py in find_peaks_cwt(vector, widths, wavelet, max_distances, gap_thresh, min_length, min_snr, noise_perc, window_size)
   1289         wavelet = ricker
   1290 
-> 1291     cwt_dat = cwt(vector, wavelet, widths, window_size=window_size)
   1292     ridge_lines = _identify_ridge_lines(cwt_dat, max_distances, gap_thresh)
   1293     filtered = _filter_ridge_lines(cwt_dat, ridge_lines, min_length=min_length,

~/miniconda3/envs/pycharm/lib/python3.8/site-packages/scipy/signal/wavelets.py in cwt(data, wavelet, widths, dtype, **kwargs)
    461     # Determine output type
    462     if dtype is None:
--> 463         if np.asarray(wavelet(1, widths[0], **kwargs)).dtype.char in 'FDG':
    464             dtype = np.complex128
    465         else:

TypeError: gaussian() got an unexpected keyword argument 'window_size'
```

This error is raised also when using other wavelets from `scipy.signal.wavelet`

scipy version: 

```
1.6.2 1.20.3 sys.version_info(major=3, minor=8, micro=10, releaselevel='final', serial=0)
```

Looking at the source of  `find_peaks_cwt` I think that the problem is related with the  `window_size` argument that is passed to the wavelet function inside `cwt`. Currently, I am avoiding this problem by wrapping the `gaussian` function, but I think that the problem could be solved by removing the `window_size` parameter passed to `cwt`

```
def gaussian_wavelet(n, sigma, window_size=None):
    return gaussian(n, sigma)

find_peaks_cwt(x, widths, wavelet=gaussian_wavelet)
```

### LINKED ISSUE #15094: BUG: find_peaks_cwt `wavelet` parameter needs more parameters than described in docs
### Describe your issue.

Per the docs:
```
wavelet: callable, optional
Should take two parameters and return a 1-D array to convolve with vector. The first parameter determines the number of points of the returned wavelet array, the second parameter is the scale (width) of the wavelet. Should be normalized and symmetric. Default is the ricker wavelet.
```

However, when I put in my own wavelet, it also needs a `window_size` parameter. The shim introduced in fd966a4 where the `window_size`parameter is used just for the ricker wavelet may need to be done for other wavelets too (or maybe there's a better way to fix this).

Maybe related to #12739.

### Reproducing Code Example

```python
import numpy as np
from scipy import signal
xs = np.arange(0, np.pi, 0.05)
data = np.sin(xs)
peakind = signal.find_peaks_cwt(data, np.arange(1,10), wavelet=lambda points, a: -1 * signal.wavelets.ricker(points, a))
#peakind = signal.find_peaks_cwt(data, np.arange(1,10), wavelet=lambda points, a, window_size: -1 * signal.wavelets.ricker(points, a)) #this is the workaround needed
```

### Error message

```shell
Traceback (most recent call last):
  File "example.py", line 5, in <module>
    peakind = signal.find_peaks_cwt(data, np.arange(1,10), wavelet=lambda points, a: -1 * signal.wavelets.ricker(points, a))
  File "/Users/edbraun/opt/anaconda3/lib/python3.8/site-packages/scipy/signal/_peak_finding.py", line 1293, in find_peaks_cwt
    cwt_dat = cwt(vector, wavelet, widths, window_size=window_size)
  File "/Users/edbraun/opt/anaconda3/lib/python3.8/site-packages/scipy/signal/wavelets.py", line 463, in cwt
    if np.asarray(wavelet(1, widths[0], **kwargs)).dtype.char in 'FDG':
TypeError: <lambda>() got an unexpected keyword argument 'window_size'
```

### SciPy/NumPy/Python version information

1.7.1 1.21.4 sys.version_info(major=3, minor=8, micro=5, releaselevel='final', serial=0)

### PR DESCRIPTION
**Pull request by v0dro**
Closes https://github.com/scipy/scipy/issues/12739
Closes https://github.com/scipy/scipy/issues/15094
Closes https://github.com/scipy/scipy/issues/14229

All these issues relate to use of the `window_size` parameter passed into the `cwt` function called by `find_peaks_cwt()` that was introduced for compatibility with numpy <= 1.14. Since that is no longer necessary, this PR removes the need for specifying the `window_size` and simplifies specification of wavelets.

### CODE REVIEW

**Comment by v0dro** [comment]
@tupui @rgommers any update on the review of this PR?

**Comment by tupui** [comment]
Hi @v0dro, sorry for the delay. It's not my area so I would prefer leaving this to another maintainer. From the discussion in #12739 it seems correct. @endolith I've seen you helped on another issue, can you have a look at this?

**Comment by endolith** [comment]
@tylerjereddy is the one who added the shim https://github.com/scipy/scipy/issues/12739#issuecomment-676848234 so seems like the best person to approve taking it back out.  

As I said in https://github.com/scipy/scipy/issues/14229#issuecomment-1069556539 , `scipy.signal.windows.gaussian` is meant to be a window function, not a wavelet, so I'm not sure if it makes sense to test it as one.  Maybe it does.

**Comment by endolith** [comment]
The test failure is a case of https://github.com/scipy/scipy/issues/15854 ? Can that test be re-run?

**Comment by tylerjereddy** [comment]
> Can that test be re-run?

I've restarted it

**Comment by larsoner** [comment]
> scipy.signal.windows.gaussian is meant to be a window function, not a wavelet, so I'm not sure if it makes sense to test it as one. (Maybe it does, but a search for "Gaussian wavelet" finds Gabor/Morlet/DOG, but not Gaussian itself, so it doesn't seem common, at least.)

I think it doesn't really matter too much which window function is used here (could even just be `np.ones` or something!), just that it's not a default, but does comply with the param specification for the `wavelet` callable, which it looks like `gaussian` does (well enough at least).

Given that things are green I'll go ahead and merge, thanks @v0dro !
