### PR TITLE
ENH: Weighted tau

### PR DESCRIPTION
**Pull request by vigna**
This pull request implements a weighted version of Kendall's 𝛕: in the weighted 𝛕, exchanges have different importance, and in general having important elements in the wrong order creates more discordance than having unimportant elements in the wrong order.

DISCLAIMER: albeit definitions of weighted versions of Kendall's 𝛕 go back at least to Shieh's 1997 paper, the definition and algorithm implemented here appeared in a paper I wrote published at WWW 2015. The definition I give encompasses all previous attempts (so one can, say, use this code to compute Shieh's variant) and is meaningful also in the presence of ties.

I was lecturing about the weighted 𝛕 at ISI in Turin recently and someone in the audience said "oh that's so nice but we will use it only if it's in SciPy". So here I am.

I understand that it might not be considered a good idea to add to SciPy something so new (and possibly useless). But I think it's interesting, in particular for big data analysis. Our use case is comparing complex centralities with indegrees: there are tons of ties, and moreover you're not really interested in what happens in the large tail of very-low-indegree nodes—you want to know whether there is correlation on the important nodes.

Note that the null distribution is not known, so there's no p-value: the code computes only the measure of correlation (the p-value is always NaN).

The code is by and large a rework of my code for #5754. Comments are more than welcome. Presently the I'm using fused types to generate 16 compiled variants handling 32/64-bits float/ints, but maybe we can reduce the choice to two types instead of four.

### CODE REVIEW

File: scipy/stats/stats.py [hunk 1]
```diff
@@ -105,6 +105,8 @@
    spearmanr
    pointbiserialr
    kendalltau
+   weightedrankedtau
+   weightedtau
```
Comment (rgommers) [inline scipy/stats/stats.py]: These two functions are so similar that they should be merged. I'd use ``weightedtau`` as the name, and add ``rank=None, use_ranked=False`` keywords (or something similar).

**Comment by rgommers** [comment]
> DISCLAIMER: albeit definitions of weighted versions of Kendall's 𝛕 go back at least to Shieh's 1997 paper, the definition and algorithm implemented year appeared in a paper I wrote published at WWW 2015. The definition I give encompasses all previous attempts (so one can, say, use this code to compute Shieh's variant) and is meaningful also in the presence of ties.
>
> I understand that it might not be considered a good idea to add to SciPy something so new (and possibly useless). 

I was trying to understand if it's really new or not, since SciPy isn't really the place for brand new algorithms. I can't access Shieh's 1997 paper (would be good to add that paper to References), so can't compare directly. But if your paper is a better way of calculating a statistic that's well known and 20 years old by now - and that's what it sounds like - that's different from a brand new algorithm.

**Comment by rgommers** [comment]
> Presently the I'm using fused types to generate 16 compiled variants handling 32/64-bits float/ints, but maybe we can reduce the choice to two types instead of four.

Maybe another alternative is to make the Cython implementation only handle two input arrays of the same type, that way you support all inputs without the ``ntypes**2`` scaling of binary size.

**Comment by josef-pkt** [comment]
just a preliminary comment, I haven't figured out what the weighting does, and didn't try to look for references:

I'm in general in favor of functions like this given that it is implemented by an efficient algorithm (not a trivial n**2). There might be a question on the exact weighting scheme that is used, I don't know yet.

(related: 
I was looking at outlier robust covariance estimators and different weighting schemes that reduce the influence of outliers. kendalltau is a candidate for this, and a weighted version sounds useful.
It also sounds a bit like measures of association for ordered categorical data like agreement measures. However, if we are in a fully discrete space like a ordered contingency table, then it might be more useful or efficient to use the frequency counts directly, AFAIR, we had a discussion for association in contingency tables before with Sturla.
)

File: scipy/stats/stats.py (hunk 1 above)
Comment (vigna) [inline scipy/stats/stats.py]: OK, it'll try that.

**Comment by vigna** [comment]
@rgommers OK, I'll make the two types identical. Indeed this is probably 99% of the use cases, and it avoids the quadratic explosion.

So, technically the definition for the case with ties and the algorithm to compute it (with and without ties) are new. Shieh's version, as well as others that can be computed by the algorithm in the paper, are instantiation of the general definition that I gave.

In Shieh's paper all ranks must be distincts (actually, if I remember correctly she works with permutations) and element weights are multiplied. So it's like the weighted 𝛕 with additive=False and rank=[0,1,2,...,n-1].

**Comment by vigna** [comment]
Can anybody help with the following error?

    ERROR: objects in scipy.stats.__all__ but not in refguide::

        weightedtau

    ERROR: refguide or doctests have errors

I've trying to understand what's wrong, but I'm clueless.

**Comment by ev-br** [comment]
The error message asks you to add tge function name to https://github.com/scipy/scipy/blob/master/scipy/stats/__init__.py

**Comment by pv** [comment]
The "refguide" error message could be clarified, though, it's not
possible to know what it means if you don't already know...

**Comment by rgommers** [comment]
> The "refguide" error message could be clarified, though, it's not possible to know what it means if you don't already know...

Good point, done in gh-6765

**Comment by vigna** [comment]
Ok, spacing / documentation issues are all fixed now. The only addition I might think of is a test implementing the trivial quadratic algorithm, if you think it's a good idea.

**Comment by rgommers** [comment]
That probably is a good idea. Just pure Python on a small data set, will be helpful to verify correctness of the optimized Cython implementation.

**Comment by vigna** [comment]
@rgommers I added a thorough test against a quadratic implementation. I also realized that the quadratic implementation might give an intuition of how the weighting process works, so it's good to have it there.

File: scipy/stats/stats.py [hunk 2]
```diff
@@ -3565,6 +3568,159 @@ def count_rank_tie(ranks):
...
+    References
+    ----------
+    .. [1] Sebastiano Vigna "A weighted correlation index for rankings with ties".
+           In Proceedings of the 24th international conference on World Wide Web,
+           pages 1166-1176. ACM, 2015.
+    .. [2] W.R. Knight, "A Computer Method for Calculating Kendall's Tau with
+           Ungrouped Data", Journal of the American Statistical Association,
+           Vol. 61, No. 314, Part 1, pp. 436-439, 1966.
+
+    Notes
```
Comment (rgommers) [inline scipy/stats/stats.py]: the ``Notes`` section comes before the ``References`` one

File: scipy/stats/stats.py [hunk 3]
```diff
@@ -3565,6 +3568,159 @@ def count_rank_tie(ranks):
...
+    -----
+    This function uses an O(n log n), mergesort-based algorithm [1]_ that is a
+    weighted extension of Knight's algorithm for Kendall's tau [2]_.
+
```
Comment (rgommers) [inline scipy/stats/stats.py]: I'd still explain the Shieh version here including citation, and explain that this implementation based on [1] is a generalized version.

File: scipy/stats/stats.py [hunk 4]
```diff
@@ -3565,6 +3568,159 @@ def count_rank_tie(ranks):
...
+
+def weightedtau(x, y, rank=True, weigher=lambda x: 1./(x+1), additive=True):
+    """
+    Computes a weighted version of Kendall's tau.
+
+    The weighted tau is a weighted version of Kendall's tau in which
+    exchanges of high weight are more influent than exchanges of low
+    weight. The default parameters compute the additive hyperbolic version
+    of the index, tau_h, which has been shown to provide the best balance
```
Comment (rgommers) [inline scipy/stats/stats.py]: You want to surround ``tau_h`` by double backticks, so it gets rendered as code. Otherwise the ``_`` will lead to strange rendering issues.

Comment (rgommers) [inline scipy/stats/stats.py]: That goes for multiple code snippets below, all double backticks.

File: scipy/stats/stats.py [hunk 5]
```diff
@@ -3565,6 +3568,159 @@ def count_rank_tie(ranks):
...
+    rather than of scores (i.e., a larger value implies a lower rank) you
+    must negate the ranks, so that elements of higher rank are associated
+    with a larger value.
+
+    Parameters
+    ----------
+    x, y : array_like
+        Arrays of rankings, of the same shape. If arrays are not 1-D, they will
+        be flattened to 1-D.
+    rank: array_like of ints or False or True, optional
```
Comment (rgommers) [inline scipy/stats/stats.py]: ``False or True`` --> ``bool``

File: scipy/stats/stats.py [hunk 6]
```diff
@@ -3565,6 +3568,159 @@ def count_rank_tie(ranks):
...
+        A nonnegative rank assigned to each element. If it is None, the
+        decreasing lexicographical rank by (x,y) will be used: elements of
+        higher rank will be those with larger x-values, using y-values to
+        break ties (in particular, swapping x and y will give a different
+        result). If you use False, the element indices will be used
+        directly as ranks. The default is True, in which case this
+        function returns the average of the values obtained using the
+        decreasing lexicographical rank by (x,y) and by (y,x).
+    weigher : function, optional
```
Comment (rgommers) [inline scipy/stats/stats.py]: we normally use ``callable`` instead of ``function``

File: scipy/stats/stats.py (hunk 2 above)
Comment (vigna) [inline scipy/stats/stats.py]: Fixed.

File: scipy/stats/stats.py [hunk 7]
```diff
@@ -3565,6 +3568,159 @@ def count_rank_tie(ranks):
     # Limit range to fix computational errors
     return KendalltauResult(min(1., max(-1., tau)), pvalue)
 
+WeightedTauResult = namedtuple('WeightedTauResult', ('correlation', 'pvalue'))
+
+
+def weightedtau(x, y, rank=True, weigher=lambda x: 1./(x+1), additive=True):
```
Comment (rgommers) [inline scipy/stats/stats.py]: I haven't benchmarked this, but it looks like passing a Python function to the inner loops of your Cython code will be quite inefficient. Does it make sense to at least make the default fast by using ``weigher=None`` and implementing the default ``x./(x+1)`` on the Cython side?

File: scipy/stats/stats.py [hunk 8]
```diff
@@ -3565,6 +3568,159 @@ def count_rank_tie(ranks):
...
+        break ties (in particular, swapping x and y will give a different
+        result). If you use False, the element indices will be used
+        directly as ranks. The default is True, in which case this
+        function returns the average of the values obtained using the
+        decreasing lexicographical rank by (x,y) and by (y,x).
+    weigher : function, optional
+        The weigher function. Must map nonnegative integers (zero representing
+        the most important element) to a nonnegative weight. The default is
+        hyperbolic weighing, that is, x -> 1/(x+1).
+    additive : boolean, optional
```
Comment (rgommers) [inline scipy/stats/stats.py]: ``boolean`` --> ``bool``

File: scipy/stats/tests/test_stats.py [hunk 9]
```diff
@@ -644,6 +644,87 @@ def test_kendalltau_nan_2nd_arg():
...
+    assert_equal(np.nan, p_value)
+    tau, p_value = stats.weightedtau(x, y, additive=False)
+    assert_approx_equal(-0.62205716951801038, tau)
+    assert_equal(np.nan, p_value)
+    # This must be exactly Kendall's tau
+    tau, p_value = stats.weightedtau(x, y, weigher=lambda x: 1)
+    assert_approx_equal(-0.47140452079103173, tau)
+    assert_equal(np.nan, p_value)
+
+    # Asymmatric, ranked version
```
Comment (rgommers) [inline scipy/stats/tests/test_stats.py]: typo

File: scipy/stats/tests/test_stats.py [hunk 10]
```diff
@@ -644,6 +644,87 @@ def test_kendalltau_nan_2nd_arg():
...
+    assert_approx_equal(-0.56694968153682723, tau)
+    assert_equal(np.nan, p_value)
+    tau, p_value = stats.weightedtau(x, y, additive=False)
+    assert_approx_equal(-0.62205716951801038, tau)
+    assert_equal(np.nan, p_value)
+    # This must be exactly Kendall's tau
+    tau, p_value = stats.weightedtau(x, y, weigher=lambda x: 1)
+    assert_approx_equal(-0.47140452079103173, tau)
+    assert_equal(np.nan, p_value)
+
```
Comment (rgommers) [inline scipy/stats/tests/test_stats.py]: would be good to test empty array input here

Comment (rgommers) [inline scipy/stats/tests/test_stats.py]: and a couple of ``assert_raises`` tests for the checks on size mismatches

File: scipy/stats/tests/test_stats.py [hunk 11]
```diff
@@ -644,6 +644,87 @@ def test_kendalltau_nan_2nd_arg():
...
+                    disc += w
+        return (conc - disc) / np.sqrt(tot - u) / np.sqrt(tot - v)
+
+    for s in range(3,10):
+        a = []
+        # Generate rankings with ties
+        for i in range(s):
+            a += [i]*i
+        b = list(a)
+        np.random.shuffle(a)
```
Comment (rgommers) [inline scipy/stats/tests/test_stats.py]: it's easy to miss in a review, but all tests should be seeded.

Comment (vigna) [inline scipy/stats/tests/test_stats.py]: Should I fix also the Kendall 𝛕 test in this commit?

File: scipy/stats/tests/test_stats.py [hunk 12]
```diff
@@ -644,6 +644,87 @@ def test_kendalltau_nan_2nd_arg():
...
+        np.random.shuffle(b)
+        # First pass: use element indices as ranks
+        rank = np.arange(len(a), dtype=np.intp)
+        for i in range(2):
```
Comment (rgommers) [inline scipy/stats/tests/test_stats.py]: ``i`` is not used, so better ``for _ in range(2):``

File: scipy/stats/_stats.pyx [hunk 13]
```diff
@@ -97,3 +98,188 @@ def _kendall_dis(intp_t[:] x, intp_t[:] y):
...
+
+    u += s * (n - first - 1) if additive else (s * s - sq) / 2
+    if first == 0: # x is constant (all ties)
+        return np.nan
+
+    # this closure recursively sorts sections of perm[] by comparing
+    # elements of y[perm[]] using temp[] as support
+
+    # Note that to accumulate exchange weights we need to use
+    # a mutable object due to Python's scoping rules
```
Comment (rgommers) [inline scipy/stats/_stats.pyx]: not sure that this comment adds much...

File: scipy/stats/_stats.pyx [hunk 14]
```diff
@@ -97,3 +98,188 @@ def _kendall_dis(intp_t[:] x, intp_t[:] y):
...
+        w = weigher(rank[perm[i]])
+        s += w
+        sq += w * w
+
+    u += s * (n - first - 1) if additive else (s * s - sq) / 2
+    if first == 0: # x is constant (all ties)
+        return np.nan
+
+    # this closure recursively sorts sections of perm[] by comparing
+    # elements of y[perm[]] using temp[] as support
```
Comment (rgommers) [inline scipy/stats/_stats.pyx]: this comment got disconnected from the code it's about

File: scipy/stats/stats.py (hunk 7 above)
Comment (vigna) [inline scipy/stats/stats.py]: Good point. I added a

    if weigher == False:
        weigher = lambda x: 1./(1 + x)

at the start of the Cython method, and it's more than twice faster now for the hyperbolic case.

**Comment by rgommers** [comment]
Haven't looked in detail at the algorithm yet, but this looks like it's in good shape.

File: scipy/stats/_stats.pyx [hunk 15]
```diff
@@ -97,3 +98,188 @@ def _kendall_dis(intp_t[:] x, intp_t[:] y):
...
+        perm[offset+i:offset+i+length0-j] = perm[offset+j:offset+length0]
+        perm[offset:offset+i] = temp[0:i]
+        return weight
+
+    # weigh discordances
+    weigh(0, n)
+
+    # weigh ties in y
+    first = 0
+    cdef float64_t v = 0
```
Comment (vigna) [inline scipy/stats/_stats.pyx]: Moved all at top.

**Comment by vigna** [comment]
One question to you guys: my builds are failing for a completely mysterious error apparently caused by this lambda in _stats.pyx:

    if weigher is None:
        weigher = lambda x: 1./(1 + x)
    
Using the Cython support in IPython the code above compiles without problems. But it seem to disrupt the compilation of SciPy, and I couldn't find any other instance of a lambda in SciPy's Cython code.

    scipy/stats/_stats.c:8324:18: error: redefinition of ‘__pyx_lambda_funcdef_lambda1’
    scipy/stats/_stats.c:6010:18: note: previous definition of ‘__pyx_lambda_funcdef_lambda1’ was here
    scipy/stats/_stats.c:10638:18: error: redefinition of ‘__pyx_lambda_funcdef_lambda1’
    scipy/stats/_stats.c:8324:18: note: previous definition of ‘__pyx_lambda_funcdef_lambda1’ was here
    scipy/stats/_stats.c:12952:18: error: redefinition of ‘__pyx_lambda_funcdef_lambda1’
    scipy/stats/_stats.c:10638:18: note: previous definition of ‘__pyx_lambda_funcdef_lambda1’ was here

Any suggestion?

**Comment by rgommers** [comment]
Maybe just a different version of Cython? ``lambda`` isn't officially unsupported, but I've never seen it used either. With ``lambda`` you're still getting a Python function rather than a compiled one, so it's not what you want I'd think.

**Comment by vigna** [comment]
OK, I isolated the problem. The problem is not the lambda per se—it is supported and works OK *as long as there only one type in the fused type* (see the tests—they're all working now that the fused type contains only np.int64). If there is more than one fused type, the Cython compiler the system is currently using generates for each fused type a symbol for the lambda, and the symbols are all the same, so after the first one they generate a duplicate symbol error. This Cython bug is apparently fixed in later releases, as I have no problem compiling _stats.pyx manually or via IPython.

Now, using the lambda improves speed by 250% in the default case. I tried alternatives, like a function doing a test for each evaluation, but it's much slower.

What do you guys think I should do? Report somewhere? Implement the lambda optimization at a later time?

**Comment by rgommers** [comment]
> What do you guys think I should do? Report somewhere? Implement the lambda optimization at a later time?

We can bump the minimum Cython version required to build Scipy, that's not a big deal. On TravisCI we use ``0.22``. What is the minimum version that works?

If it's fixed in later Cython releases, then no need to report I'd say.

**Comment by vigna** [comment]
It works with 0.23.4 (that's the version I have installed). Current version is 0.25.1.

**Comment by rgommers** [comment]
Thanks, updated minimum required Cython version to 0.23.4 in gh-6786. Once that's in you can rebase on top of it and get the faster ``lambda`` function back.

**Comment by rgommers** [comment]
Updated Cython version merged now.

**Comment by rgommers** [comment]
the build failed with:

    scipy/stats/_stats.c:8324:18: error: redefinition of ‘__pyx_lambda_funcdef_lambda1’
    static PyObject *__pyx_lambda_funcdef_lambda1(CYTHON_UNUSED PyObject *__pyx_self, PyObject *__pyx_v_x) {

**Comment by vigna** [comment]
So it's working with Travis CI, not with Circle CI. Are they using different versions of Cython?

**Comment by ev-br** [comment]
https://circleci.com/gh/scipy/scipy/1495?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
shows `pip install -q --install-option="--no-cython-compile" Cython==0.22`

However on master, https://github.com/scipy/scipy/blob/master/circle.yml lists 0.23.4

So a rebase on master should probably fix it.

**Comment by ev-br** [comment]
A slight git error somewhere...

**Comment by vigna** [comment]
Er. I thought I had rebased correctly. Are you telling me this is not the case? 😞

**Comment by ev-br** [comment]
A bunch of extraneous commits should not be there.

Try 
```
$ git fetch upstream
$ git rebase upstream/master
```

**Comment by vigna** [comment]
Er... those are *exactly* the two lines I wrote on my terminal.

**Comment by charris** [comment]
Looks more like you did a merge from master.

**Comment by vigna** [comment]
This is my setting:

    git remote -v
    origin	https://github.com/vigna/scipy (fetch)
    origin	https://github.com/vigna/scipy (push)
    upstream	https://github.com/scipy/scipy.git (fetch)
    upstream	https://github.com/scipy/scipy.git (push)

I did 

    git fetch upstream
    git rebase upstream/master
    git pull
    git push
 
Maybe the remote stuff wasn't set correctly?

**Comment by vigna** [comment]
At least it works...

**Comment by ev-br** [comment]
To a first approximation, you never want to do `git pull` 

```
git fetch upstream
git rebase upstream/master
git push origin HEAD -f
```

**Comment by vigna** [comment]
OK, I didn't know that. How do I get out of this mess? Please be patient.

**Comment by ev-br** [comment]
Try repeating `$ git rebase upstream/master`. Check the commits, if it looks reasonable, force-push (git push --force).

**Comment by vigna** [comment]
Done. Does it look better?

**Comment by rgommers** [comment]
yes, looks good to me

**Comment by vigna** [comment]
OK, let me know if I need to do anything else.

File: scipy/stats/tests/test_stats.py (hunk 11 above)
Comment (rgommers) [inline scipy/stats/tests/test_stats.py]: seeding is all done now

**Comment by rgommers** [comment]
@vigna rather than making a bunch of nitpicky comments I've added a couple of commits in https://github.com/rgommers/scipy/tree/weighted_tau. GitHub has a really annoying bug where it misses forks; I don't see yours from the PR interface so can't send you a PR. Can you please add my commits?

    git remote add rgommers https://github.com/rgommers/scipy.git
    git fetch rgommers
    git merge rgommers/weighted_tau

**Comment by rgommers** [comment]
@josef-pkt @ev-br do you still want to look at the math/weighting in more detail? I'm inclined to merge this soon.

**Comment by charris** [comment]
@rgommers I've taken to doing edits (edit button) on the PRs for some of those tiny nitpicky  things. Github will make it a commit in the originating repo. Not all repos seem to allow that however.

**Comment by rgommers** [comment]
>  Not all repos seem to allow that however.

I believe that's a per PR setting; there's a checkbox when you submit a PR whether you allow maintainers to edit it.

I haven't started using that, maybe I will soon. Still like my editor better though:)

**Comment by charris** [comment]
Well, me too 8) But for fixing typos it works a treat.

**Comment by vigna** [comment]
@rgommers I added your changes, thanks! I do not how I got convinced that a double backslash was needed to get the math right.

**Comment by rgommers** [comment]
> I do not how I got convinced that a double backslash was needed to get the math right.

That is needed normally, but it's ugly if you have a lot of them. So you can use raw strings ``r"""`` which don't treat ``\`` as an escape character.

**Comment by vigna** [comment]
I just did a thorough review, and everything seems to be fine. There's a small issue: in the documentation, x and y are called "arrays of rankings", as it happens with Kendall's 𝛕 documentation. The problem is that with the weighted 𝛕 this is confusing: first of all, there is a separate rank array, so the word "ranking" can be ambiguous. But, more importantly, whereas in the computation the unweighted version you can feed scores or ranks indifferently, this does not happen with the weighted version: you must provide scores, not ranks (in fact, if you have ranks at hand you must negate them, as explained in the documentation). A larger score means a higher rank.

I am thinking of a more appropriate term. Would "Arrays of scores" or "Arrays of observations" work?

**Comment by rgommers** [comment]
> Would "Arrays of scores" or "Arrays of observations" work?

both would work I guess; I have a preference for "observations" because it's a less stats-specific term

**Comment by vigna** [comment]
In the end I went for "scores" as "observation" does not imply that a larger score is better.

The PR for me is complete at this point.

File: scipy/stats/stats.py [hunk 16]
```diff
@@ -3566,6 +3570,168 @@ def count_rank_tie(ranks):
...
+    >>> y = [1, 4, 7, 1, 0]
+    >>> tau, _ = stats.weightedtau(x, y, weigher=lambda x: 1)
+    >>> tau
+    -0.47140452079103173
+
+    >>> x = [12, 2, 1, 12, 2]
+    >>> y = [1, 4, 7, 1, 0]
+    >>> stats.weightedtau(x, y, rank=None)
+    WeightedTauResult(correlation=-0.4157652301037516, pvalue=nan)
+    >>> stats.weightedtau(y, x, rank=None)
```
Comment (josef-pkt) [inline scipy/stats/stats.py]: looks like `rank=False` would be better according to docstring
docstring doesn't say what happens if it is None.

**Comment by josef-pkt** [comment]
looks fine to me, except I have a question about the dtype handling, and the unit test only use integer examples, AFAICS

Does x, y integer and the same x and y as dtype(float) produce the same results?

From my interpretation, if x, y are integers, then they are not changed to ranks, but they are if x,y are a float type.
kendalltau is invariant to monotonic transformation, but in the integer case, the raw data are not converted to the same scaling in terms of ranks.

???

**Comment by josef-pkt** [comment]
another issue, given that it is now available in most stats functions is nan handling.
I assume the current "propagate" behavior is to sort nan to the end and given them implicitly the highest ranks, except the sign comparison might add nans to the results (?).

**Comment by vigna** [comment]
@josef-pkt The unit tests contain examples with several different types. The _toranks() function is possibly misnamed, in the sense that it transforms the score to integers, but assuming that a lower score is a lower rank. That is, _toranks([1,2,3])=[0,1,2]. Probably _toranks() is not a good name.

_toint64()?

**Comment by vigna** [comment]
The nan issue is different. If there's a different number of nans in the two vectors that "nan first" strategy will not work. Moreover, it might make sense when all exchanges have the same weight, but it has no mathematical basis when the exchanges are weighted.

Would you prefer that the function exists with an exceptions if nans are present?

**Comment by vigna** [comment]
Since np.lexsort() and np.argsort() consider np.nan the smallest number, a strategy could be just using _toranks() if there is any nan. At that point the function will manage just integer ranks, with nans having lowest rank.

**Comment by WarrenWeckesser** [comment]
> Since np.lexsort() and np.argsort() consider np.nan the smallest number, [...]

`nan`s are treated like the *largest* number.  From the docstring of `numpy.sort` (to which the docstring of `argsort` refers):

    Previous to numpy 1.4.0 sorting real and complex arrays containing nan
    values led to undefined behaviour. In numpy versions >= 1.4.0 nan
    values are sorted to the end.

For example,

```
In [33]: x
Out[33]: array([  1.,   3.,  nan,   2.])

In [34]: np.sort(x)
Out[34]: array([  1.,   2.,   3.,  nan])
```

**Comment by vigna** [comment]
Oh yes, you're right. I made a test in Jupyter and I read the results backwards 😵.

**Comment by vigna** [comment]
I am trying to implement in a simple way a "nan as smallest score" policy. I have two problems I need help with:

1) If I turn an input array into integers using _toranks(), the resulting object (a memory view) has no dtype field. So when I check for dtype I get an error. Is wrapping the memory view into a np.array(-, dtype=np.int64) going to cause any slowdown?

2) Is there any better way to find whether an array contains a NaN than scanning the array? kendalltau() adds up all values and checks for NaN, but this really seems overkill to me.

**Comment by vigna** [comment]
So the answer to 1., by benchmarking, is no, no slowdown. I modified the code accordingly.

**Comment by vigna** [comment]
After some reading and some testing, now I'm checking for NaNs in vector x using np.isnan(np.min(x)).

With that, I think I solved all raised issues! ☺️

**Comment by vigna** [comment]
Anybody interested in merging this?

**Comment by rgommers** [comment]
Okay, the last set of commits regarding nan handling looks fine to me now. All other comments addressed, so in it goes. Thanks @vigna!
