### ISSUE TITLE
BUG: csr_matrix.A not implemented

### ISSUE THREAD

**Issue by JunyanReplicant** [scipy/scipy#21049]
### Describe your issue.

Hello, in previous Scipy versions, the csr_matrix.A is a short form for csr_matrix.toarray() although it is not explicitly listed in the documentation, but many research packages implement their codes in this way. (e.g., a biology-related package scVelo)
Today after I install scipy, several packages are reporting this error: 'csr_matrix' object has no attribute 'A'. And then I notice this issue. I can confirm it still worked in 1.13.0

### Reproducing Code Example

```python
scipy.sparse.csr_matrix((3, 4), dtype=np.int8).A
```

### Error message

```shell
'csr_matrix' object has no attribute 'A'
```

### SciPy/NumPy/Python version and system information

```shell
1.14.0
```

**Comment by lucascolley** [comment]
This is mentioned in the release notes (https://github.com/scipy/scipy/releases/tag/v1.14.0)

<img width="575" alt="image" src="https://github.com/scipy/scipy/assets/51488791/abfd46b8-f638-4411-9785-42c3ef5c28d2">
