### ISSUE TITLE
BUG: sparse.linalg.expm for sparse matrices

### ISSUE THREAD

**Issue by davidgontier** [scipy/scipy#15506]
Here is a minimal code:

```
import scipy.sparse as sparse
import numpy as np

I = sparse.linalg.aslinearoperator( np.eye(2) )
E = sparse.linalg.expm(I)
```

I got this error:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-51-4b6becc82cad> in <module>
      3 
      4 I = sparse.linalg.aslinearoperator( np.eye(2) )
----> 5 E = sparse.linalg.expm(I)

/usr/local/lib/python3.9/site-packages/scipy/sparse/linalg/matfuncs.py in expm(A)
    589             [  0.        ,   0.        ,  20.08553692]])
    590     """
--> 591     return _expm(A, use_exact_onenorm='auto')
    592 
    593 

/usr/local/lib/python3.9/site-packages/scipy/sparse/linalg/matfuncs.py in _expm(A, use_exact_onenorm)
    627 
    628     # Detect upper triangularity.
--> 629     structure = UPPER_TRIANGULAR if _is_upper_triangular(A) else None
    630 
    631     if use_exact_onenorm == "auto":

/usr/local/lib/python3.9/site-packages/scipy/sparse/linalg/matfuncs.py in _is_upper_triangular(A)
    124         return lower_part.nnz == 0
    125     else:
--> 126         return not np.tril(A, -1).any()
    127 
    128 

<__array_function__ internals> in tril(*args, **kwargs)

/usr/local/lib/python3.9/site-packages/numpy/lib/twodim_base.py in tril(m, k)
    463     """
    464     m = asanyarray(m)
--> 465     mask = tri(*m.shape[-2:], k=k, dtype=bool)
    466 
    467     return where(mask, m, zeros(1, m.dtype))

TypeError: tri() missing 1 required positional argument: 'N'
```

I am working with Python 3.9.10 on osX Monterey 12.2

**Comment by ogauthe** [comment]
Hi @davidgontier ,
`sparse.linalg.expm` does not accept `LinearOperator` as input, it has to be dense or sparse matrix. You may consider
```python
m = sparse.csc_matrix(np.eye(2))
me = sparse.linalg.expm(m)
```

**Comment by davidgontier** [comment]
Dear @ogauthe ,
Thx for the quick reply. Too bad it does not accept LinearOperator. I'll change my code accordingly!
