### ISSUE TITLE
Windows wheel builds for x86-64 on scipy-release repo broken

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#25067]
All x86-64 Windows builds are failing, the arm64 ones work fine. From [example log](https://github.com/scipy/scipy-release/actions/runs/24828354546/job/72670115767):

```
  + python -m build 'D:\a\scipy-release\scipy-release\scipy-src' --wheel '--outdir=C:\Users\runneradmin\AppData\Local\Temp\cibw-run-1o75h_i9\cp313-win_amd64\built_wheel'
  * Creating isolated environment: venv+pip...
  * Installing packages in isolated environment:
    - Cython>=3.2.0
    - meson-python>=0.15.0
    - numpy>=2.0.0
    - pybind11>=2.13.2
    - pythran>=0.18.1
  * Getting build dependencies for wheel...
  * Building wheel...
  + meson setup D:\a\scipy-release\scipy-release\scipy-src D:\a\scipy-release\scipy-release\scipy-src\.mesonpy-4bjhs3cx -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=D:\a\scipy-release\scipy-release\scipy-src\.mesonpy-4bjhs3cx\meson-python-native-file.ini
  The Meson build system
  Version: 1.11.1
  Source dir: D:\a\scipy-release\scipy-release\scipy-src
  Build dir: D:\a\scipy-release\scipy-release\scipy-src\.mesonpy-4bjhs3cx
  Build type: native build
  Project name: scipy
  Project version: 1.18.0.dev0+git20260423.58d174c
  C compiler for the host machine: C:\Strawberry\c\bin\ccache.EXE cc (gcc 15.2.0 "cc (x86_64-posix-seh-rev1, Built by MinGW-Builds project) 15.2.0")
  C linker for the host machine: cc ld.bfd 2.46.0.20260210
  C++ compiler for the host machine: C:\Strawberry\c\bin\ccache.EXE c++ (gcc 15.2.0 "c++ (x86_64-posix-seh-rev1, Built by MinGW-Builds project) 15.2.0")
  C++ linker for the host machine: c++ ld.bfd 2.46.0.20260210
  
  ..\meson.build:1:0: ERROR: Compiler cython cannot compile programs.
```

`meson-log.txt` shows:
```
  Run-time dependency python3 found: YES 3.9
  checking compilation of transpiled source:
  Sanity check compiler command line: cc -D_FILE_OFFSET_BITS=64 -o sanity_check_for_cython.dll sanity_check_for_cython.c -D_FILE_OFFSET_BITS=64 -IC:/Strawberry/c/lib/pkgconfig/../../../../share/python/include/python3.9 -LC:/Strawberry/c/lib/pkgconfig/../../../../share/python/lib -lpython3.9 -shared -Wl,--allow-shlib-undefined
  Sanity check compile stdout:
  
  -----
  Sanity check compile stderr:
  sanity_check_for_cython.c:19:10: fatal error: Python.h: No such file or directory
     19 | #include "Python.h"
        |          ^~~~~~~~~~
  compilation terminated.
  
  -----
  
  ..\meson.build:1:0: ERROR: Compiler cython cannot compile programs.
  

ERROR Backend subprocess exited when trying to invoke build_wheel
```

Likely contributors:
- The release repo uses `cibuildwheel` 3.4.0, while in this repo we're still on 3.3.1. 3.4.0 has a deliberate change related to PATH handling: https://github.com/pypa/cibuildwheel/pull/2723
- Meson 1.11.0 also has a new Cython sanity check, introduced in https://github.com/mesonbuild/meson/commit/379165e

Note that the C/C++ compiler detections also show `C:\Strawberry\c\...` which is probably undesirable. IIRC we used to delete that whole directory outright, and Meson also tries to ignore it, because Strawberry Perl in the GHA images is hopelessly broken.

Filing an issue now because I'm out of time for today to keep digging.

**Comment by rgommers** [comment]
Easiest way to iterate on this is probably to bump `cibuildwheel` to 3.4.0 in this repo, push it to one's own fork and run just a single Windows wheel build job there to reproduce. 

We may want to put back something like this in `cibw_before_build.sh`:
```bash
if [[ $RUNNER_OS == "Windows" ]]; then
       rm -rf /c/Strawberry/c/lib/pkgconfig/*.pc
   fi
```

Might also be an issue with the new Cython check. `meson-python` avoids picking up the wrong Python interpreter by passing the path to the right one in a `native-file.ini`, but this Cython check doesn't do that I suspect.

**Comment by andyfaff** [comment]
I'm looking into this.

> C:\Strawberry\c\... which is probably undesirable. IIRC we used to delete that whole directory outright,

I don't think it was because of that. I seem to recall it's because the pkg-config that was found on that path was borked.

From the timing of things it looks like the latest release of meson caused the issue. The April 13 build was fine, the April 16 build was broken, `meson==1.11.0` was released on April 14th. 

Works:
cibuildwheel==3.4.0 and meson==1.10.2
cibuildwheel==3.3.1 and meson==1.11.1

Doesn't work:
cibuildwheel==3.4.0 and meson==1.11.1

Not sure if this is a cibuildwheel issue, or a meson issue. Pinning one or the other will provide a temp fix.

**Comment by andyfaff** [comment]
The logfile has this suspicious stuff:
```
Detecting compiler via: `cython -V` -> 0
  stdout:
  Cython version 3.2.4
  -----------
  Sanity check transpiler command line: cython --fast-fail -o sanity_check_for_cython.c sanity_check_for_cython.pyx -3
  Sanity check transpiler stdout:
  
  -----
  Sanity check transpiler stderr:
  
  -----
  'utf-8' codec can't decode byte 0x90 in position 2: invalid start byte
  Unusable script 'C:\\Users\\runneradmin\\AppData\\Local\\Temp\\build-env-4ddowjfw\\Scripts\\python.exe'
  Pkg-config binary missing from cross or native file, or env var undefined.
  Trying a default Pkg-config fallback at pkg-config
  Found pkg-config: YES (C:\Users\runneradmin\AppData\Local\Temp\cibw-run-ix5ouwlr\cp312-win_amd64\build\venv\Scripts\pkg-config.EXE) 2.5.1
  Determining dependency 'python3' with pkg-config executable 'C:\\Users\\runneradmin\\AppData\\Local\\Temp\\cibw-run-ix5ouwlr\\cp312-win_amd64\\build\\venv\\Scripts\\pkg-config.EXE'
  env[PKG_CONFIG_PATH]: D:/a/scipy-release/scipy-release/.openblas
  env[PKG_CONFIG]: C:\Users\runneradmin\AppData\Local\Temp\cibw-run-ix5ouwlr\cp312-win_amd64\build\venv\Scripts\pkg-config.EXE
  -----------
  Called: `C:\Users\runneradmin\AppData\Local\Temp\cibw-run-ix5ouwlr\cp312-win_amd64\build\venv\Scripts\pkg-config.EXE --modversion python3` -> 0
  stdout:
  3.9
```
Which would indicate to me that the correct python can't be found or something. Unfortunately I don't know enough about the innards of meson-python/meson/cython to be able to figure out if there's something in there that needs fixing.

**Comment by andyfaff** [comment]
It seems like `rm -fo c:/Strawberry/c/lib/pkgconfig/*.pc` does allow the build to run. This seems like a temporary fix to me.

Probably the normal way of detecting python is screwed up a bit (I don't know which of cython/cibuildwheel/meson is responsible), and pkg-config is left to its own devices to find any python
