### PR TITLE
ENH: `multivariate_normal_frozen`: restore `cov` attribute

### LINKED ISSUE #17896: DOC: publicly expose `multivariate_normal` attributes `mean` and `cov`
### Issue with current documentation:

In scipy 1.9.3, the following code was valid and printed the covariance matrix of the distribution:

```
from scipy import stats
distribution = stats.multivariate_normal([0, 0], [[1, 0], [0, 1]])
print(distribution.cov)
```

In scipy 1.10.0, this gives the error
`AttributeError: 'multivariate_normal_frozen' object has no attribute 'cov'`
and in order to access the covariance from the frozen distribution the approach I found to work is 

```
from scipy import stats
distribution = stats.multivariate_normal([0, 0], [[1, 0], [0, 1]])
print(distribution.cov_object.covariance)
```

which does not work in scipy 1.9.3.
None of this is documented in the [docs](https://scipy.github.io/devdocs/reference/generated/scipy.stats.multivariate_normal.html#scipy-stats-multivariate-normal), neither is the change reported in the [changelog](https://github.com/scipy/scipy/releases/tag/v1.10.0).

### Idea or request for content:

It seems useful to document the [cov_object](https://github.com/scipy/scipy/blob/5beeda995449c55332ce141cad1be77621789f31/scipy/stats/_multivariate.py#L833) attribute of the frozen distribution somewhere; alternatively, to add a convenience `rv.cov` property redirecting to `rv.cov_object.covariance` for backwards compatibility.

### Additional context (e.g. screenshots, GIFs)

_No response_

### PR DESCRIPTION
**Pull request by jacopok**
#### Reference issue
Closes #17896 

#### What does this implement?
This PR formalizes the inclusion of the mean and covariance attributes of the `multivariate_normal_gen` and `multivariate_normal_frozen` classes.
Specifically:

- a `@property` called `rv.cov` is added to both, which returns `rv.cov_object.covariance`, which is the actual covariance matrix
- the availability of the `mean`, `cov` and `cov_object` attributes
    -  is documented in the `Attributes` section
    - is tested in a few new unit tests in `stats/tests/test_multivariate.py`

##### PR checklist

- [x] Did you check that the code can be distributed under a BSD license? See [License Considerations](https://scipy.github.io/devdocs/dev/hacking.html#license-considerations). *Yes, I wrote it myself*
- [x] Are there unit tests with good code coverage? See [NumPy/SciPy Testing Guidelines](https://docs.scipy.org/doc/numpy/reference/testing.html). *Yes, the new features are fully tested*
- [x] Do all unit tests pass locally? See [The dev.py interface](https://scipy.github.io/devdocs/dev/contributor/meson.html#the-dev-py-interface). *Yes they do*
- [x] Do all public function have docstrings including examples? See the [numpydoc docstring guide](https://numpydoc.readthedocs.io/en/latest/format.html). *Not applicable*
- [x] Does the documentation render correctly? See [Rendering documentation locally with Sphinx](https://scipy.github.io/devdocs/dev/contributor/rendering_documentation.html#rendering-documentation). *It shows a sensible output, the "Attributes" section is quite low down in the page which I did not expect, if you know how to improve that I'd be glad to change it*
- [x] Is the code style correct? See [PEP8 and SciPy](https://scipy.github.io/devdocs/dev/contributor/pep8.html#pep8-scipy). *The linter does not seem to complain*
- [x] Are there benchmarks? See [Benchmarking SciPy with airspeed velocity](https://scipy.github.io/devdocs/dev/contributor/benchmarking.html#benchmarking-with-asv). *Not applicable, I think*
- [x] Is the commit message [formatted correctly](https://numpy.org/devdocs/dev/development_workflow.html#writing-the-commit-message)?
- [x] Is the docstring of the new functionality tagged with .. versionadded:: X.Y.Z (where X.Y.Z is the version number of the next release? See the updating, workers, and constraints documentation of [differential_evolution](https://github.com/scipy/scipy/blob/main/scipy/optimize/_differentialevolution.py), for example. You can get the next version number from the most recent release notes on [the wiki](https://github.com/scipy/scipy/wiki) or from the MAJOR and MINOR version number variables in [setup.py](https://github.com/scipy/scipy/blob/main/setup.py). *I did this with version 1.10.1*
- [x] In case of larger additions, is there a tutorial or more extensive module-level description? Tutorial files are in doc/source/tutorial. *Not applicable*
- [x] If compiled code is added, is it integrated correctly via setup.py? See [Compiled code](https://scipy.github.io/devdocs/dev/contributor/contributor_toc.html#compiled-code) for more information *Not applicable*

### CODE REVIEW

File: scipy/stats/_multivariate.py [hunk 1]
```diff
@@ -305,6 +305,24 @@ class multivariate_normal_gen(multi_rv_generic):
...
+        Covariance matrix of the distribution.
+
+        .. versionadded:: 1.10.1
+
+    cov_object : `Covariance`
+        Representation of the covariance matrix as a `Covariance` object.
+
+        .. versionadded:: 1.10.1
+
+
```
Comment (mdhaber) [inline scipy/stats/_multivariate.py:325]:
```suggestion
```
This is the documentation of `multivariate_normal_gen`, but `mean`, `cov`, and `cov_object` are only attributes of `multivariate_normal_frozen`. I don't think we want these changes to `multivariate_normal_gen`.

File: scipy/stats/_multivariate.py [hunk 2]
```diff
@@ -503,6 +521,10 @@ def _process_quantiles(self, x, dim):
 
         return x
 
+    @property
+    def cov(self):
+        return self.cov_object.covariance
+
```
Comment (mdhaber) [inline scipy/stats/_multivariate.py:527]:
```suggestion
```

File: scipy/stats/_multivariate.py [hunk 3]
```diff
@@ -839,6 +879,10 @@ def __init__(self, mean=None, cov=1, allow_singular=False, seed=None,
         self.abseps = abseps
         self.releps = releps
 
+    @property
+    def cov(self):
+        return self.cov_object.covariance
+
```
Comment (mdhaber) [inline scipy/stats/_multivariate.py:885]: I think that this should return whatever the user passed in as `cov`. 
- If the user passed in a matrix (as a list or np.array), then `self.cov` will be an object of type `CovViaPSD` (which is not a public class), and we should return `self.cov_object.covariance`. 
- If the user passed in a `Covariance` object for cov, then that is stored directly in `self.cov`, and this should return `self.cov`

File: scipy/stats/tests/test_multivariate.py [hunk 4]
```diff
@@ -513,6 +513,15 @@ def test_frozen(self):
         assert_allclose(norm_frozen.cdf(x), multivariate_normal.cdf(x, mean, cov))
         assert_allclose(norm_frozen.logcdf(x),
                         multivariate_normal.logcdf(x, mean, cov))
+    
+    def test_frozen_multivariate_normal_exposes_attributes(self):
+        np.random.seed(1234)
```
Comment (mdhaber) [inline scipy/stats/tests/test_multivariate.py:518]: Some reviewers have a strong preference for only using NumPy `Generator`s, even in tests. I don't mind it, so to please everyone, this should be `rng = np.random.default_rng(349582469826092)` and `rng` should be passed into `multivariate_normal`.

File: scipy/stats/tests/test_multivariate.py [hunk 5]
```diff
@@ -770,6 +779,25 @@ def test_mean_cov(self):
...
+        model = multivariate_normal(mean, covariance)
+        assert np.allclose(model.cov, covariance)
+
+    def test_multivariate_normal_covariance_object_is_exposed(self):
+        mean = np.zeros(2)
+        covariance_obj = Covariance.from_diagonal([1, 1])
+        model = multivariate_normal(mean, covariance_obj)
+        assert isinstance(model.cov_object, Covariance)
+        assert np.allclose(model.cov_object.covariance, covariance_obj.covariance)
+
```
Comment (mdhaber) [inline scipy/stats/tests/test_multivariate.py:800]:
```suggestion
```
I don't see a difference between this and the previous test.

File: scipy/stats/tests/test_multivariate.py [hunk 6]
```diff
@@ -513,6 +513,15 @@ def test_frozen(self):
         assert_allclose(norm_frozen.cdf(x), multivariate_normal.cdf(x, mean, cov))
         assert_allclose(norm_frozen.logcdf(x),
                         multivariate_normal.logcdf(x, mean, cov))
+    
+    def test_frozen_multivariate_normal_exposes_attributes(self):
```
Comment (mdhaber) [inline scipy/stats/tests/test_multivariate.py:517]: This can be [parametrized](https://docs.pytest.org/en/6.2.x/parametrize.html) over `cov`: in one case it should be a regular matrix; in the other, it should be a `Covariance` object.

**Review by mdhaber — COMMENTED** [review]
Thanks @jacopok.

File: scipy/stats/_multivariate.py (hunk 3 above)
Comment (rkern) [reply scipy/stats/_multivariate.py:885]: I think that's a pretty complicated set of semantics, and doesn't really fix one of the backwards compatibility issues. Because the old interface was only semi-documented, what the `.cov` attribute guaranteed was a little fuzzy, but it wasn't "whatever was passed in as `cov`". The input did get processed and normalized to a full covariance matrix from a scalar or a diagonal or a list of lists, etc. into a 2-dim array that was the covariance matrix. So someone could well have written library functions that take `multivariate_normal_frozen` instances and access the `.cov` to get the fully normalized covariance matrix. I think it makes sense to honor those semantics here.

File: scipy/stats/_multivariate.py [hunk 7]
```diff
@@ -816,6 +838,24 @@ def __init__(self, mean=None, cov=1, allow_singular=False, seed=None,
...
+        Covariance matrix of the distribution.
+
+        .. versionadded:: 1.10.1
+
+    cov_object : `Covariance`
+        Representation of the covariance matrix as a `Covariance` object.
+
+        .. versionadded:: 1.10.1
+
+
```
[the remark this answers is not in the document]
Comment (rkern) [reply scipy/stats/_multivariate.py:858]: Well, that's what underscores are for. Generally, we honor accidental public-ness. If you really don't want to, then we should underscore it now and place a `cov_object` property that's deprecated.

That's the other way out for `mean` and `cov`, too, if you really don't want them to continue.

[the remark this answers is not in the document]
Comment (mdhaber) [reply scipy/stats/_multivariate.py:858]: Are you going to review this PR?

File: scipy/stats/_multivariate.py (hunk 3 above)
Comment (mdhaber) [reply scipy/stats/_multivariate.py:885]: Sure. Whatever code was written before 1.10 will still work with what I suggested.

Yes, "whatever the user passed in as `cov`" is not very accurate. I forgot that there are over 50 lines of processing to convert the user input into a standard-format ndarray. It would be difficult to capture all of that in the docstring.

Perhaps if it is to become public it could be described as:
```
    cov : ndarray or Covariance
        Covariance of the distribution.
```

Comment (rkern) [reply scipy/stats/_multivariate.py:885]: Whole programs will still work (ones that create the `multivariate_normal_frozen` instances then access their `.cov` attribute), but not necessarily individual functions that were written against a (very reasonable) guess at what was being promised by the interface. Both are aspects of backwards compatibility that would have to be restored if we really want to care about backwards compatibility here, not just whole-program compatibility.

If you really don't want these extra attributes (a very reasonable design decision), just hide them behind deprecated properties and move on (but make sure that the `cov` property returns the actual array along with the `DeprecationWarning`). There probably are very few programs that ever relied on these.

Comment (mdhaber) [reply scipy/stats/_multivariate.py:885]: If I understand correctly, this is not backward compatible with all code written before 1.10
```python3
    @property
    def cov(self):  # this is what I had in mind
        if isinstance(self.cov_object, CovViaPSD)
            return self.cov_object.covariance
        else:  # cov_object is a different type of Covariance
            return self.cov_object
```

but this is:
```python3
    @property
    def cov(self):  # this is what is in the PR
        return self.cov_object.covariance
```

But I'm having trouble understanding why. If it's simple to provide an example that might have been written before 1.10 which would be broken by the former but not the latter, I'd appreciate it.

Comment (mdhaber) [reply scipy/stats/_multivariate.py:885]: I found another mistake in my comment at the top; perhaps this will help. In the bulleted list when I wrote `self.cov`, I meant `self.cov_object`.

- If the user passed in a matrix (as a list or np.array), then `self.cov_object` will be an object of type `CovViaPSD` (which is not a public class), and we should return `self.cov_object.covariance`. 
- If the user passed in a `Covariance` object for cov, then that is stored directly in `self.cov_object`, and this should return `self.cov_object`

File: scipy/stats/_multivariate.py (hunk 7 above)
[the remark this answers is not in the document]
Comment (jacopok) [reply scipy/stats/_multivariate.py:858]: If it's an option, I would remove the `versionadded` and keep the documentation in!

This is indeed just a formalization of an already-kind-of-existing feature, but I think that 
adding the property, the tests and the documentation for it should really be in the same PR/version.

It seems to me like the shape attributes of a frozen distribution (here, mean and cov) _should_ be documented and accessible, and that this should remain true even if as you say in that discussion they
> should [not] be "objects" with a __call__ method that creates a "frozen distribution"; they should be classes that get instantiated with shape parameters
in that the attributes of this class corresponding to the shape parameters should be publicly accessible, don't you agree?

File: scipy/stats/tests/test_multivariate.py (hunk 4 above)
Comment (jacopok) [reply scipy/stats/tests/test_multivariate.py:518]: Leaving this was actually just an oversight on my part, the rest of the test is deterministic so the seeding can just be removed!

File: scipy/stats/tests/test_multivariate.py (hunk 6 above)
Comment (jacopok) [reply scipy/stats/tests/test_multivariate.py]: Done in c633842!

File: scipy/stats/tests/test_multivariate.py (hunk 4 above)
Comment (jacopok) [reply scipy/stats/tests/test_multivariate.py]: Solved in [0e82be9](https://github.com/scipy/scipy/pull/17904/commits/0e82be9c6875ae18f647c8589f8eeee0080d37b6)

File: scipy/stats/_multivariate.py (hunk 3 above)
Comment (jacopok) [reply scipy/stats/_multivariate.py:867]: Since this feature was not really documented before, couldn't this be the time to make the decision to have `self.cov` consistently return the matrix representation of the covariance?

This was what I had in mind, it may not be completely backwards compatible with version 1.10.0 since in that one the user may have passed in a `Covariance` object and expected it back, but that's been out for a relatively short time so it seems acceptable to me (correct me if I'm wrong about this of course).

**Comment by tupui** [comment]
> Since this feature was not really documented before, couldn't this be the time to make the decision to have self.cov consistently return the matrix representation of the covariance?
> 
> This was what I had in mind, it may not be completely backwards compatible with version 1.10.0 since in that one the user may have passed in a Covariance object and expected it back, but that's been out for a relatively short time so it seems acceptable to me (correct me if I'm wrong about this of course).

I am personally against that. From an API point of view I don't think we should do that.

Since we now have `Covariance` it would be better to push people into using this and pass the object. Doing so, you already have the object and don't need to get it from the class. The purpose of the class is about distribution, then to me the API should not return things mildly related.

To this PR, my preference would actually be to add `cov` back and deprecate it directly. i.e. fix the backward incompatibility (falls under a 1.10.1) and prepare for the future saying we don't want this.

File: scipy/stats/_multivariate.py (hunk 7 above)
[the remark this answers is not in the document]
Comment (jacopok) [reply scipy/stats/_multivariate.py]: For now I have removed the `versionadded` in 98ac5fd since it surely should not have been there.

**Comment by jacopok** [comment]
> Since we now have `Covariance` it would be better to push people into using this and pass the object. Doing so, you already have the object and don't need to get it back from the class (otherwise we can argue that all classes should have attributes for all inputs, I think this should not be the case). The purpose of the class is about distribution, then to me the API should not return things mildly related.

Pushing people toward the class sounds fair! So, do you think the API should expose `cov_object`?
In my opinion either way is fine, I'll provide the concrete example that prompted me to make this PR:
I have some tests which use a `multivariate_normal_frozen` as a fixture; they use some samples from it
and make some checks against its mean and covariance.

If `cov` or `cov_object` are available I can access them as attributes of the single object being passed in, otherwise I would need to pass them separately, while it seems like I _should_ be able to access the covariance from the frozen distribution.

> To this PR, my preference would actually be to add `cov` back (and not bother about any alternative cases or anything) and deprecate it directly. i.e. fix the backward incompatibility (falls under a 1.10.1) and prepare for the future saying we don't want this.

This sounds OK to me if `cov_object` will be available after `cov` is deprecated!

**Comment by tupui** [comment]
> ... So, do you think the API should expose `cov_object`?

IMO no. We should just add back `cov` which would raise a deprecation warning.

> This sounds OK to me if `cov_object` will be available after `cov` is deprecated!

No, cf previous comment.

> If `cov` or `cov_object` are available I can access them as attributes of the single object being passed in, otherwise I would need to pass them separately, while it seems like I _should_ be able to access the covariance from the frozen distribution.
> ...
> however I do think that in general these classes should expose attributes corresponding to their inputs unless there is some obstruction / processing step preventing it.

I don't think this is a good idea. Imagine a nested structure `A.B.C`, `A` could be very bloated object then if it contains all inputs from all linked objects. This is really not a thing to keep track of all inputs in the classes like that and when it's done it's for very specific purposes (e.g. you need a way to reset the class and reprocess the inputs).

**Comment by jacopok** [comment]
I don't mean to argue here, and I am fine with adding a deprecation warning and merging this PR of course.

However, I would like to understand the reasoning here: even in the situation you mention, `A` would still be storing all its inputs (or a processed version of them), this is just about whether to expose them as part of the API or not...

Also I would not expose all inputs, but only the "defining" ones - mean and covariance, not `allow_singular` or `seed` for example.

**Comment by rkern** [comment]
> Since we now have `Covariance` it would be better to push people into using this and pass the object.

One problem here is that we don't seem to have any method for taking a plain covariance matrix ndarray (an incredibly common case) and getting a `Covariance` instance. The processing logic in `multivariate_normal` is the only place that I see it.

> Doing so, you already have the object and don't need to get it back from the class 

No, not necessarily. Once you have objects like the frozen distributions, you start passing them around. You start writing functions that take those objects and not every piece of information in the environment that led to its construction.

> (otherwise we can argue that all classes should have attributes for all inputs, I think this should not be the case).

While I think that is an arguable and not at all absurd design philosophy, but I also don't feel like one has to adopt it entirely or avoid it entirely. One can have individualized cases for exposing different parts of the data held by the object. @jacopok has one such case. Wanting to have `mean` and `cov_object` exposed doesn't entail having every possible attribute on every possible object exposed.

File: scipy/stats/_multivariate.py (hunk 3 above)
Comment (mdhaber) [reply scipy/stats/_multivariate.py:857]: Maybe this is the explanation I needed:

- Before SciPy 1.10, library writes function `f` that accepts a `multivariate_normal_frozen` as an input `dist`. If `getattr(dist, 'cov', None)` does not produce an array, `f` will fail.
- After SciPy 1.10 is released, user writes new code that creates `dist` with `Covariance` object, calls library's function as `f(dist)`. In `f`, `getattr(dist, 'cov', None)` returns a `Covariance` object instead of an array, and therefore `f` fails.

(Incorrect perspective: User reports to library that it does not work with `dist` objects created with instance of `Covariance`. Library fixes bug.)

Comment (rkern) [reply scipy/stats/_multivariate.py:857]: If you want to expose the `Covariance` object underlying the `multivariate_normal_frozen` instance, exposing the `cov_object` is the best way to do that, not this variable behavior with the `cov` attribute. Having `.cov` be either an array or a `Covariance` object depending on how it was created is a very difficult to use API. Functions that consume these instances should be able to be written in such a way that does not care about that detail because those functions are far away from the instantiation of those objects.

If you don't want to expose the `Covariance` object or the explicit covariance matrix, just go with the PR's implementation of the property, deprecate it, and remove it at the scheduled time.

File: scipy/stats/_multivariate.py [hunk 8]
```diff
@@ -816,6 +816,18 @@ def __init__(self, mean=None, cov=1, allow_singular=False, seed=None,
             Relative error tolerance for the cumulative distribution function
             (default 1e-5)
 
+    Attributes
```
Comment (rkern) [inline scipy/stats/_multivariate.py:819]: This whole section needs to be indented 4 more spaces to align with its surroundings.

File: scipy/stats/_multivariate.py [hunk 9]
```diff
@@ -816,6 +816,18 @@ def __init__(self, mean=None, cov=1, allow_singular=False, seed=None,
...
+    ----------
+    mean : ndarray
+        Mean of the distribution.
+
```
Comment (rkern) [inline scipy/stats/_multivariate.py:823]: We don't have empty lines between these entries.

File: scipy/stats/_multivariate.py [hunk 10]
```diff
@@ -816,6 +816,18 @@ def __init__(self, mean=None, cov=1, allow_singular=False, seed=None,
...
+    mean : ndarray
+        Mean of the distribution.
+        
+    cov : ndarray
+        Covariance matrix of the distribution.
+
+    cov_object : `Covariance`
+        Representation of the covariance matrix as a `Covariance` object.
+
+
```
Comment (rkern) [inline scipy/stats/_multivariate.py:830]: Only one empty line between sections.

**Review by rkern — COMMENTED** [review]
There are some minor formatting changes needed in the docstring.

As a matter of the design choices, I personally think this PR implements the best thing to do. I think there are other reasonable options, though. In my preference order:

1. Leave the PR as-is.
2. Document `mean` and `cov_object` but deprecate the currently-implemented `cov` property.
3. Rename the `mean` and `cov_object` attributes to have leading underscores, implement `mean` and `cov_object` properties to expose them, but deprecate those properties. Remove the example. Make a note in the docstring that no attributes are part of the supported interface of the object.
4. Do nothing in the code, but remove the example, and make a note in the docstring that no attributes are part of the supported interface of the object.

**Comment by jacopok** [comment]
Sounds good! I have one question: it was [suggested](https://github.com/scipy/scipy/pull/17904#discussion_r1095214838) by @mdhaber to remove the attributes documentation from `multivariate_normal_gen` and only have it in `multivariate_normal_frozen`, which sounds fair since it's only the frozen instance which has those attributes; I have implemented it in [16070f8](https://github.com/scipy/scipy/pull/17904/commits/16070f875bcf29d8a71cb66f8a9d8a80e72d036c).

However, it is not clear how a user may actually view the documentation of `multivariate_normal_frozen` (except for reading the docstring of course): as far as I can tell, the only page in the HTML docs is https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.multivariate_normal.html, which comes from `multivariate_normal_gen`. On the base page https://docs.scipy.org/doc/scipy/reference/stats.html there is no reference to frozen objects. Also, on the multivariate_normal HTML doc page there is no link to the frozen distribution.
I have no experience with how this is typically handled within scipy, but it seems like for these documented attributes to be useful they would need to show up where a user can find them. Am I missing something here?

**Comment by tupui** [comment]
> However, I would like to understand the reasoning here: even in the situation you mention, A would still be storing all its inputs (or a processed version of them), this is just about whether to expose them as part of the API or not...

`A` would store its inputs but also provide `B` and `B` itself would have its inputs, etc. You end up with huge objects and huge API surface.

> Also I would not expose all inputs, but only the "defining" ones - mean and covariance, not allow_singular or seed for example.

This is your interpretation, but we would set a precedent here that could be used to justify other changes.

> One problem here is that we don't seem to have any method for taking a plain covariance matrix ndarray (an incredibly common case) and getting a Covariance instance. The processing logic in multivariate_normal is the only place that I see it.

Then let's have that elsewhere, like in the `Covariance` class. This is saying that if you want to convert a plain covariance matrix to an object you would use this class (and maybe not even use the class for anything else).

I personally don't like the direction of this PR. Even more since it's marked as a backport candidate. I will step back and let you make the calls.

**Comment by rkern** [comment]
I brought it up because @mdhaber thought that it's hiddenness was important elsewhere in the discussion (about keeping `cov_object` hidden). My point, inelegantly made, was more that that lacuna demonstrates that as a project, we haven't made any particular design decision to expose and encourage the use of `Covariance` in general for all places where a covariance matrix might exist. We use them internally, and we allow them to be input in place of plain-old ndarrays where it makes sense, but as a project, we have not chosen to move away from plain-old ndarrays as inputs in APIs. That was not an accidental or incomplete choice.

In particular, I would object if we did, and the use of `CovViaPSD` here demonstrates why. The choice to convert a plain-old ndarray into a PSD is one that is actually tied to the algorithm that it goes on to implement. There is no default way to turn a plain-old ndarray into one of the specialized `Covariance` implementations that's good for all algorithms. If you have a covariance matrix ndarray from any of the myriad APIs either inside of `scipy` or outside that output covariance matrices, putting the choice of specialized `Covariance` implementation onto the user is forcing them to precommit to a decision before there is enough information to do so. That's a well-known factor in API usability (known as "Premature Commitment" in the [cognitive dimensions framework](https://en.wikipedia.org/wiki/Cognitive_dimensions_of_notations)). It's great to _allow_ the user to provide one when they know the properties of all the uses, and that there is value in reusing the factorization across API calls.

I do agree that we should expose `CovViaPSD` as a way to convert plain-old ndarrays in the `Covariance` API and not leave it buried in here. It should be among the supported options for other functions that need to convert plain-old ndarrays into the `Covariance` API. I don't think it should be the default way to turn a plain-old ndarray into a `Covariance` instance, and I'm really not sure that there ought to be one.

**Comment by jacopok** [comment]
This has sparked a lot of discussion, so here is an attempt to restrict the scope of the PR to the minimal changes that solve #17896: 

- ensuring through tests that `mean` and `cov` are exposed but not explicitly adding them as attributes;
- keeping the property `cov`; 
- removing all changes regarding `cov_object`.

Adding the attributes explicitly should probably wait until a minor release (and a different PR) and be done under the scope of #16278.

My two cents are that after those changes the `cov` attribute should have a well-defined return type, and that that return type should probably be `Covariance`, but again that becomes out of scope.

**Review by mdhaber — APPROVED** [review]

**Review by tupui — APPROVED** [review]

**Comment by mdhaber** [comment]
This looks like a good compromise that restores the behavior to that of 1.9.3. Thanks @jacopok!
