### PR TITLE
ENH: special: ensure error handling thread-safety

### PR DESCRIPTION
**Pull request by andfoy**
#### Reference issue

See https://github.com/scipy/scipy/issues/20669

#### What does this implement/fix?

This is a continuation of the work done in https://github.com/scipy/scipy/pull/21496, this time, each module gets its own PR detailing changes that ensure that the tests pass under a concurrent scenario. 

The main change in this PR consists of extracting the error cache into a threadlocal variable, this ensures that each thread is able to define the conditions under errors should be reported independently.

#### Additional information

See the description of https://github.com/scipy/scipy/pull/21496 for more detailed information.

cc @rgommers

### CODE REVIEW

**Review by rgommers — COMMENTED** [review]
Thanks @andfoy! 

Changing `sf_error` from C to C++ code is fine I think - would be good to spell out the reason for it in the PR description. 

I don't have real-world experience with `PyMutex` yet, and this is the first place we'd be introducing it in SciPy - @ngoldbaum could you please have a quick look to check that the usage here looks about right?

The Windows jobs (which use MinGW) are pretty unhappy with `multiple definition of `pthread_mutex_destroy'`:
```
[116/1457] Linking target scipy/special/_ufuncs_cxx.cp311-win_amd64.pyd
FAILED: scipy/special/_ufuncs_cxx.cp311-win_amd64.pyd 
"c++"  -o scipy/special/_ufuncs_cxx.cp311-win_amd64.pyd scipy/special/_ufuncs_cxx.cp311-win_amd64.pyd.p/meson-generated__ufuncs_cxx.cpp.obj scipy/special/_ufuncs_cxx.cp311-win_amd64.pyd.p/_faddeeva.cxx.obj scipy/special/_ufuncs_cxx.cp311-win_amd64.pyd.p/_wright.cxx.obj scipy/special/_ufuncs_cxx.cp311-win_amd64.pyd.p/ellint_carlson_wrap.cxx.obj scipy/special/_ufuncs_cxx.cp311-win_amd64.pyd.p/Faddeeva.cc.obj scipy/special/_ufuncs_cxx.cp311-win_amd64.pyd.p/sf_error.cc.obj scipy/special/_ufuncs_cxx.cp311-win_amd64.pyd.p/wright.cc.obj "-Wl,--allow-shlib-undefined" "-Wl,-O1" "-shared" "-Wl,--start-group" "-Wl,--out-implib=scipy\special\_ufuncs_cxx.cp311-win_amd64.dll.a" "-lucrt" "-static" "scipy/special/libsf_error_state.dll.a" "-Wl,--version-script=C:/Users/runneradmin/AppData/Local/Temp/build-via-sdist-_z5_mnfd/scipy-1.15.0.dev0/scipy/_build_utils/link-version-pyinit.map" "C:\hostedtoolcache\windows\Python\3.11.9\x64\python311.dll" "-lkernel32" "-luser32" "-lgdi32" "-lwinspool" "-lshell32" "-lole32" "-loleaut32" "-luuid" "-lcomdlg32" "-ladvapi32" "-Wl,--end-group"
C:/rtools40/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/rtools40/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/lib/../lib\libpthread.a(libwinpthread_la-mutex.o):(.text+0x80): multiple definition of `pthread_mutex_lock'; scipy/special/libsf_error_state.dll.a(d000073.o):(.text+0x0): first defined here
C:/rtools40/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/rtools40/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/lib/../lib\libpthread.a(libwinpthread_la-mutex.o):(.text+0x3a0): multiple definition of `pthread_mutex_unlock'; scipy/special/libsf_error_state.dll.a(d000076.o):(.text+0x0): first defined here
C:/rtools40/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/rtools40/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/lib/../lib\libpthread.a(libwinpthread_la-mutex.o):(.text+0x520): multiple definition of `pthread_mutex_init'; scipy/special/libsf_error_state.dll.a(d000072.o):(.text+0x0): first defined here
C:/rtools40/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/rtools40/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/lib/../lib\libpthread.a(libwinpthread_la-mutex.o):(.text+0x570): multiple definition of `pthread_mutex_destroy'; scipy/special/libsf_error_state.dll.a(d000071.o):(.text+0x0): first defined here
```

And the `-Werror` one has a minor complaint:
```
[49/1464] Compiling C++ object scipy/special/libsf_error_state.so.p/sf_error_state.cpp.o
FAILED: scipy/special/libsf_error_state.so.p/sf_error_state.cpp.o 
clang++-17 -Iscipy/special/libsf_error_state.so.p -Iscipy/special -I../scipy/special -Iscipy/_lib -I../scipy/_lib -I../scipy/_build_utils/src -fdiagnostics-color=always -DNDEBUG -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Werror -std=c++17 -O3 -fPIC -MD -MQ scipy/special/libsf_error_state.so.p/sf_error_state.cpp.o -MF scipy/special/libsf_error_state.so.p/sf_error_state.cpp.o.d -o scipy/special/libsf_error_state.so.p/sf_error_state.cpp.o -c ../scipy/special/sf_error_state.cpp
../scipy/special/sf_error_state.cpp:6:19: error: unused variable 'err_mutex' [-Werror,-Wunused-variable]
    6 | static std::mutex err_mutex;
      |                   ^~~~~~~~~
1 error generated.
```

File: scipy/special/sf_error.cc [hunk 1]
```diff
@@ -54,10 +62,13 @@ void sf_error_v(const char *func_name, sf_error_t code, const char *fmt, va_list
         PyOS_snprintf(msg, 2048, "scipy.special/%s: %s", func_name, sf_error_messages[(int) code]);
     }
 
+#ifndef Py_GIL_DISABLED
 #ifdef WITH_THREAD
```
Comment (ngoldbaum) [inline scipy/special/sf_error.cc:66]: unrelated to this, but CPython removed threadless builds in Python 3.7, so `WITH_THREAD` is always defined

File: scipy/special/sf_error.cc [hunk 2]
```diff
@@ -54,10 +62,13 @@ void sf_error_v(const char *func_name, sf_error_t code, const char *fmt, va_list
...
     save = PyGILState_Ensure();
 #endif
-
+#else
+    PyMutex_Lock(&err_mutex);
+#endif
```
Comment (ngoldbaum) [inline scipy/special/sf_error.cc:71]: Can you explain more why you're not calling `PyGILState_Ensure` and `PyGILState_Release` on the GIL-enabled build? If this is some kind of error callback mechanism (which it looks like it is) you would still need to have a valid thread state to be able to call into the C API. If a scipy function spawned a thread (say, via OpenMP, without going through the `threading` module) that called one of these error callbacks before registering the thread with the interpreter with `PyGILState_Ensure`, that would crash. Did you add the ifdefs to avoid a deadlock or something like that?

File: scipy/special/sf_error_state.cpp [hunk 3]
```diff
@@ -1,10 +1,10 @@
 #include <stdlib.h>
-
 #include "sf_error_state.h"
 
 
+
 /* If this isn't volatile clang tries to optimize it away */
-static volatile sf_action_t sf_error_actions[] = {
+static volatile thread_local sf_action_t sf_error_actions[] = {
```
Comment (ngoldbaum) [inline scipy/special/sf_error_state.cpp:7]: does this still need to be volatile if it's thread_local?

Comment (ngoldbaum) [reply scipy/special/sf_error_state.cpp:7]: heh, LLVM was trying to tell the author of the comment above that the code was doing UB...

File: scipy/special/sf_error.cc (hunk 2 above)
Comment (andfoy) [reply scipy/special/sf_error.cc:66]: Sorry, I wasn't aware of the purpose of `PyGILState_STATE`, I thought it was related to something about the GIL and therefore it needed culling under free-threaded circumstances. I've just restored them on https://github.com/scipy/scipy/pull/21956/commits/87e5f3bf1da498f7d381e0ee33d805b74ad80361.

The mutex there is to prevent concurrent writing to the module attribute that's being used to keep track of errors.

File: scipy/special/sf_error_state.cpp (hunk 3 above)
Comment (andfoy) [reply scipy/special/sf_error_state.cpp:7]: Would it still optimize it away when using both `static` and `thread_local`?

Comment (ngoldbaum) [reply scipy/special/sf_error_state.cpp:7]: No, the comment is alluding to the fact that LLVM was optimizing away a `static volatile` variable storing global state. LLVM was doing this because marking a variable as `volatile` is *not* sufficient to prevent data races, so LLVM detected UB there and optimized it away, because by definition UB can't happen.

If it's `static thread_local` then there's no multithreaded data race and no UB.

**Comment by andfoy** [comment]
It seems that MinGW has issues with respect to the `thread_local` keyword: https://github.com/msys2/MINGW-packages/issues/2519#issuecomment-304155278, the only straight-forward solution would be to either extract the error state to a singleton object per-thread or to lock a global state only when MinGW is detected.

**Comment by rgommers** [comment]
> It seems that MinGW has issues with respect to the `thread_local` keyword: [msys2/MINGW-packages#2519 (comment)](https://github.com/msys2/MINGW-packages/issues/2519#issuecomment-304155278), 

Okay, this has some history and is a little complex - see this:

https://github.com/scipy/scipy/blob/1d57f315d9454446d333d37d19f2a44f4baf35c9/scipy/fft/_pocketfft/meson.build#L1-L26

I think it'd be nice to have this PR focused on this issue. The `scipy.io` changes were already merged as part of gh-21955, so can be dropped. It'd be good to open a separate PR for the test changes different from the `sf_error` ones (those are mechanical and can be merged straight away). And then for this PR see if the `fft._pocketfft` approach applies here as well - and if not, we have something to discuss indeed.

**Comment by rgommers** [comment]
I had a chat with @steppi about this topic. We agreed that for MinGW issue it's not a big deal to use a global lock instead of threadlocals (only when MinGW is used to build). As long as the code is robust against concurrent writes, the worst that can happen is that floating-point warnings escape or get treated differently in threaded usage - we can live with that for as long as we need to keep MinGW around probably.

**Comment by andfoy** [comment]
It seems that using `std::mutex` also causes the same MinGW threading issues to surface.

File: scipy/special/sf_error_state.cpp [hunk 4]
```diff
@@ -1,10 +1,19 @@
...
 #include "sf_error_state.h"
 
+#ifdef __MINGW64__
+#include <mutex>
+std::mutex err_mutex;
+
+#define THREAD_LOCAL
+#else
+#define THREAD_LOCAL thread_local
+#endif
```
Comment (rgommers) [inline scipy/special/sf_error_state.cpp:11]: This won't work. What thread-local define to use needs compiler checks - those are already implemented:

https://github.com/scipy/scipy/blob/7466219fb545a7b774c820ce22ae04826c59cd80/scipy/meson.build#L155-L194

You can include `scipy_config.h` and use `SCIPY_TLS` where you'd otherwise use `thread_local`.

File: scipy/special/sf_error.cc [hunk 5]
```diff
@@ -3,6 +3,7 @@
 
 #include <stdarg.h>
 #include <stdlib.h>
+#include <signal.h>
```
Comment (rgommers) [inline scipy/special/sf_error.cc:6]: minor: not used?

**Review by rgommers — COMMENTED** [review]
> It seems that using `std::mutex` also causes the same MinGW threading issues to surface.

The problem seems to be pretty fundamental, and related to the MinGW build we use. We use Rtools 4.0.0.20220206, which is built with GCC 10.3.0 (see [this for example [this log](https://github.com/scipy/scipy/actions/runs/12146287262/job/33869853363)). MinGW-w64 comes in two build flavors: `posix` and `win32`. The `posix` builds have threading support, the `win32` ones don't. I can't quite tell what Rtools is, but I assume it's `win32`. Also note that in gh-21735 @isuruf is attempting to upgrade the MinGW toolchain to one derived from conda-forge.

More context:
- https://en.wikipedia.org/wiki/Mingw-w64 has some notes on threading
- https://stackoverflow.com/questions/17242516/mingw-w64-threads-posix-vs-win32 is relevant
- https://github.com/meganz/mingw-std-threads is still separately maintained it looks like
- Several MinGW-w64 builds at https://www.mingw-w64.org/downloads/ have notes on providing threading support.

@isuruf do you know if the builds you maintain are built with `pthreads`?

@carlkl you may have some insights to share perhaps?

**Comment by isuruf** [comment]
> @isuruf do you know if the builds you maintain are built with pthreads?

It's `win32` thread model, but we do have `winpthreads` packaged.

File: scipy/special/sf_error_state.cpp (hunk 3 above)
Comment (steppi) [reply scipy/special/sf_error_state.cpp]: I didn't write the comment above, but I did copy it from its original home into the `sf_error_state.c`. I don't think the variable being optimized away necessarily had anything to do with data races.  I think what was going on is that `clang` decided this wasn't being used in the translation unit because `scipy_sf_error_set_action` and `scipy_sf_error_get_action` are only called through the Python runtime, and Python's dynamic function lookup makes it tricky to determine that they are actually used through static analysis. A more principled solution would have been to conditionally compile in a `__attribute__((used))` on platforms that support it. If it's working now without the `volatile`, it may just be that Clang's static analyzer has improved.

Comment (steppi) [reply scipy/special/sf_error_state.cpp]: Sorry, my attempted explanation assumed there's some kind of link time optimization going on, but that might not necessarily be the case. I still don't think the original issue had anything to do with a data race, I think the way that these could only be accessed from Python with the GIL in place would have prevented that possibility.

**Comment by rgommers** [comment]
Quick note: we should be handling this by removed `sf_error_state.dll`, since it's giving issues in multiple places - I discussed with @steppi. So no need to further dig into arcane MinGW details right now.

**Comment by andfoy** [comment]
@rgommers Does that mean that we only should apply this comment to land this PR? https://github.com/scipy/scipy/pull/21956#discussion_r1868321923

**Comment by rgommers** [comment]
> @rgommers Does that mean that we only should apply this comment to land this PR? [#21956 (comment)](https://github.com/scipy/scipy/pull/21956#discussion_r1868321923)

I think so, yes. However, I would hold off on any changes here and let @steppi make the infra changes first (unless he says otherwise). And then rebase the needed parts of this PR on top.

File: scipy/special/tests/test_basic.py [hunk 6]
```diff
@@ -79,8 +79,8 @@ def test_binom(self):
         assert_func_equal(cephes.binom, rknown.ravel(), nk, rtol=1e-13)
 
         # Test branches in implementation
-        rng = np.random.RandomState(1234)
-        n = np.r_[np.arange(-7, 30), 1000*rng.rand(30) - 500]
+        np.random.seed(1234)
+        n = np.r_[np.arange(-7, 30), 1000*np.random.rand(30) - 500]
```
Comment (rgommers) [inline scipy/special/tests/test_basic.py:83]: I think you picked up a bunch of changes here that revert the random number handling back to using global state - looks like a mistake?

**Comment by rgommers** [comment]
This PR no longer applies after gh-22419 redid how `special.errstate` is implemented, and gh-22742 supersedes this PR now. Since that's all green, I'll close this PR. Thanks @andfoy & reviewers.
