### PR TITLE
ENH: optimize: allow COBYQA optimization to run in parallel

### LINKED ISSUE #24027: ENH: optimize: Allow concurrent use of COBYQA minimizer
### Is your feature request related to a problem? Please describe.

Right now, all COBYQA optimizations take a lock prior to calling into the COBYQA code.

This lock was added in https://github.com/scipy/scipy/pull/21496, to fix test failure where COBYQA would sometimes give incorrect output.

This means that multiple threads calling `minimize(method='COBYQA')` will proceed serially.

### Describe the solution you'd like.

I would like it if multiple COBYQA optimizations could proceed in parallel.

In order for that to happen, the following would need to be done.

- [ ] Many tests are skipped in pytest-run-parallel when COBYQA optimization is in use. This was initially added to address test failures. However, the skips were not removed after the COBYQA lock was added, and COBYQA became thread safe again.
- [ ] Investigate the failing tests from https://github.com/scipy/scipy/pull/21496.
   - [ ] [These lines look very suspicious.](https://github.com/cobyqa/cobyqa/blob/3fd86f2757d3e265b72a1099059ecc899582de9e/cobyqa/models.py#L238-L241)
- [ ] Write any new tests for COBYQA, if applicable.

This is a pure Python module that makes limited use of global state, so achieving concurrent use of COBYQA seems achievable. COBYQA's upstream is also interested in patches to improve this, see https://github.com/cobyqa/cobyqa/issues/182.

### Describe alternatives you've considered.

_No response_

### Additional context (e.g. screenshots, GIFs)

xref https://github.com/scipy/scipy/pull/21496

xref https://github.com/cobyqa/cobyqa/issues/182

### PR DESCRIPTION
**Pull request by nickodell**
#### Reference issue

Closes #24027

#### What does this implement/fix?

When COBYQA was first added to SciPy, there were a number of test suite failures where COBYQA would give different results randomly when run from multiple threads. COBYQA is supposed to be deterministic, so this was quite alarming. These issues went away when a lock was added in #21496, in commit dc73938784aa08ac6c3e00c850ed24a5cda24cb1.

In #24041, I fixed the issue that was causing these different results. The cause of this issue was that in order to make COBYQA faster, we asked upstream to put a cache in front of repeated calls to `scipy.linalg.eigh()`.

This cache was not locked, and could be modified concurrently by multiple threads, leading to eigh values from other threads being re-used. I solved this by submitting a patch to COBYQA which moved the eigh cache to an object that was not shared between threads.

I believe that this problem was the only remaining thread safety problem, for three reasons.

 * I have been testing the lock change using pytest-run-parallel and a free threading build, and I have seen no failures caused by removing the lock over 100 runs of the optimize test suite.
 * Upstream believes a lock is not required: they do not use a lock to serialize calls to COBYQA in their own package.
 * No-one has reported any thread safety problems to the upstream repository since the release of COBYQA 1.1.3 in November 2025.

#### Additional information

### CODE REVIEW

File: scipy/optimize/_cobyqa_py.py [hunk 1]
```diff
@@ -55,7 +53,7 @@ def _minimize_cobyqa(fun, x0, args=(), bounds=None, constraints=(),
     .. [1] COBYQA
            https://www.cobyqa.com/stable/
     """
-    from .._external.cobyqa import minimize  # import here to avoid circular imports
+    from .._lib.cobyqa import minimize  # import here to avoid circular imports
```
Comment (andyfaff) [inline scipy/optimize/_cobyqa_py.py]:
```suggestion
    from .._lib.cobyqa import minimize as _cobqa_minimize # import here to avoid circular imports
```

File: scipy/optimize/_cobyqa_py.py [hunk 2]
```diff
@@ -68,5 +66,4 @@ def _minimize_cobyqa(fun, x0, args=(), bounds=None, constraints=(),
         'radius_final': float(final_tr_radius),
         'scale': bool(scale),
     }
-    with COBYQA_LOCK:
-        return minimize(fun, x0, args, bounds, constraints, callback, options)
+    return minimize(fun, x0, args, bounds, constraints, callback, options)
```
Comment (andyfaff) [inline scipy/optimize/_cobyqa_py.py]:
```suggestion
    return _cobqa_minimize(fun, x0, args, bounds, constraints, callback, options)
```

File: scipy/optimize/_cobyqa_py.py (hunk 1 above)
Comment (andyfaff) [reply scipy/optimize/_cobyqa_py.py]: In fact this could probably be at the top if we use 'import as'?

**Review by andyfaff — APPROVED** [review]

File: scipy/optimize/_cobyqa_py.py (hunk 1 above)
Comment (nickodell) [reply scipy/optimize/_cobyqa_py.py]: >In fact this could probably be at the top if we use 'import as'?

Unfortunately, COBYQA uses parts of scipy.optimize. If I move the import outside of this function, I get an error like this:

```
Traceback:
/home/nodell/.miniforge3/envs/scipy-dev/lib/python3.13/importlib/__init__.py:88: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
scipy/optimize/__init__.py:423: in <module>
    from ._minimize import *
scipy/optimize/_minimize.py:34: in <module>
    from ._cobyqa_py import _minimize_cobyqa
scipy/optimize/_cobyqa_py.py:4: in <module>
    from .._lib.cobyqa import minimize as _cobyqa_minimize  # import here to avoid circular imports
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
scipy/_lib/cobyqa/__init__.py:1: in <module>
    from .main import minimize
scipy/_lib/cobyqa/main.py:4: in <module>
    from scipy.optimize import (
E   ImportError: cannot import name 'Bounds' from partially initialized module 'scipy.optimize' (most likely due to a circular import) (/home/nodell/scipy/build-install/usr/lib/python3.13/site-packages/scipy/optimize/__init__.py)
```

Comment (nickodell) [reply scipy/optimize/_cobyqa_py.py]: I re-tried this after merging in the change to move COBYQA from _lib to subprojects - same error.

**Comment by nickodell** [comment]
Hang on, I'm missing the changes from #24271. I'm going to rebase on top of that, so that I avoid combining a substantive change with a merge commit.

File: scipy/optimize/_cobyqa_py.py (hunk 1 above)
Comment (nickodell) [reply scipy/optimize/_cobyqa_py.py]: I've applied the suggestion to rename the import in commit ef1886a.

File: scipy/optimize/_cobyqa_py.py (hunk 2 above)
Comment (nickodell) [reply scipy/optimize/_cobyqa_py.py]: I've applied the suggestion to rename the import in commit ef1886a.

**Comment by nickodell** [comment]
Regarding this test failure: https://github.com/scipy/scipy/actions/runs/21550611052/job/62098771697?pr=24466

```
_______________ TestPoisson.test_fill_space[l_bounds1-u_bounds1] _______________

self = <scipy.stats.tests.test_qmc.TestPoisson object at 0x13a491bf0>
l_bounds = [-5, -5], u_bounds = [5, 5]

    @pytest.mark.parametrize("l_bounds, u_bounds",  # add bounds to test gh-22819
        [(None, None), ([-5, -5], [5, 5]),  ([1.1, 1.1], [5.1, 5.1])])
    def test_fill_space(self, l_bounds, u_bounds):
        radius = 0.2
        engine = self.qmce(d=2, radius=radius, l_bounds=l_bounds, u_bounds=u_bounds)
    
        sample = engine.fill_space()
        # circle packing problem is np complex
>       assert l2_norm(sample) >= radius
E       assert np.float64(0.19999995985843508) >= 0.2
E        +  where np.float64(0.19999995985843508) = l2_norm(array([[-0.77608197,  1.13404075],\n       [-1.01362098,  1.09635316],\n       [-0.78927703,  1.3735868 ],\n       ...,\n       [-4.22197675,  3.72761342],\n       [-4.98296556, -4.5606922 ],\n       [-1.34089559, -4.44003031]], shape=(1530, 2)))

engine     = <scipy.stats._qmc.PoissonDisk object at 0x1515cd5e0>
l_bounds   = [-5, -5]
radius     = 0.2
sample     = array([[-0.77608197,  1.13404075],
       [-1.01362098,  1.09635316],
       [-0.78927703,  1.3735868 ],
       ...,
       [-4.22197675,  3.72761342],
       [-4.98296556, -4.5606922 ],
       [-1.34089559, -4.44003031]], shape=(1530, 2))
self       = <scipy.stats.tests.test_qmc.TestPoisson object at 0x13a491bf0>
u_bounds   = [5, 5]

scipy/stats/tests/test_qmc.py:967: AssertionError
=========================== short test summary info ============================
FAILED scipy/stats/tests/test_qmc.py::TestPoisson::test_fill_space[l_bounds1-u_bounds1] - assert np.float64(0.19999995985843508) >= 0.2
 +  where np.float64(0.19999995985843508) = l2_norm(array([[-0.77608197,  1.13404075],\n       [-1.01362098,  1.09635316],\n       [-0.78927703,  1.3735868 ],\n       ...,\n       [-4.22197675,  3.72761342],\n       [-4.98296556, -4.5606922 ],\n       [-1.34089559, -4.44003031]], shape=(1530, 2)))
= 1 failed, 81878 passed, 7511 skipped, 199 deselected, 307 xfailed, 24 xpassed in 548.06s (0:09:08) =
```

I'm able to reproduce this issue locally about 1 / 200 times using this test command on main:

```
spin test -s stats -- -k 'test_qmc and test_fill_space' --iterations=10 -x --forever 
```

Configuration:

```
>>> scipy.show_config()
Build Dependencies:
  blas:
    detection method: extraframeworks
    found: true
    has ilp64: false
    include directory: unknown
    lib directory: unknown
    name: Accelerate
    openblas configuration: unknown
    pc file directory: unknown
    version: unknown
  lapack:
    detection method: extraframeworks
    found: true
    has ilp64: false
    include directory: unknown
    lib directory: unknown
    name: Accelerate
    openblas configuration: unknown
    pc file directory: unknown
    version: unknown
  pybind11:
    detection method: config-tool
    include directory: unknown
    name: pybind11
    version: 3.0.1
Compilers:
  c:
    commands: /opt/homebrew/Cellar/llvm/20.1.1/bin/clang
    linker: ld64
    name: clang
    version: 20.1.1
  c++:
    commands: /opt/homebrew/Cellar/llvm/20.1.1/bin/clang++
    linker: ld64
    name: clang
    version: 20.1.1
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.2.4
  fortran:
    commands: gfortran
    linker: ld64
    name: gcc
    version: 15.1.0
  pythran:
    include directory: ../venv/lib/python3.13/site-packages/pythran
    version: 0.18.1
Machine Information:
  build:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
  cross-compiled: false
  host:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
Python Information:
  path: /Users/nick/programming/scipy/venv/bin/python3.13
  version: '3.13'
```

Edit: opened #24486 to track this.

**Comment by nickodell** [comment]
@andyfaff Should be ready for review now.
