### ISSUE TITLE
BLD: pip build from source fails in `_stats_pythran` with PyPy3.11

### ISSUE THREAD

**Issue by puni073** [scipy/scipy#22583]
### Describe your issue.

build fails using pypy3.11-v7.3.18

### Reproducing Code Example

both of
```
pip3 install scipy==1.15.2
```
and
```
git clone https://github.com/scipy/scipy
cd scipy
git submodule update --init
pip3 install .
```
fails.

### Error message

```shell
[551/1466] Generating 'scipy/stats/_stats_pythran.pypy311-pp73-x86_64-linux-gnu.so.p/_stats_pythran.cpp'
      FAILED: scipy/stats/_stats_pythran.pypy311-pp73-x86_64-linux-gnu.so.p/_stats_pythran.cpp
      /tmp/pip-build-env-8fm34ex_/overlay/bin/pythran -E ../scipy/stats/_stats_pythran.py -o scipy/stats/_stats_pythran.pypy311-pp73-x86_64-linux-gnu.so.p/_stats_pythran.cpp
      WARNING: Overriding pythran description with argspec information for: numpy.arange
      WARNING: Overriding pythran description with argspec information for: numpy.array
      WARNING: Overriding pythran description with argspec information for: numpy.concatenate
      WARNING: Overriding pythran description with argspec information for: numpy.empty
      WARNING: Overriding pythran description with argspec information for: numpy.empty_like
      WARNING: Overriding pythran description with argspec information for: numpy.fromiter
      WARNING: Overriding pythran description with argspec information for: numpy.fromfile
      WARNING: Overriding pythran description with argspec information for: numpy.zeros
      CRITICAL: I am in trouble. Your input file does not seem to match Pythran's constraints...
      ../scipy/stats/_stats_pythran.py:187:10 error: function uses an unknown (or unsupported) keyword argument `dtype`
      ----
          pmf = np.zeros(n + 1, dtype=np.float64)
                ^~~~ (o_0)
      ----
```

### SciPy/NumPy/Python version and system information

```shell
SciPy: 1.15.2 and head
Python: pypy3.11-v7.3.18-linux64
```

**Comment by lucascolley** [comment]
The error message seems to be complaining about `np.zeros` not having a `dtype` parameter, but it has had that parameter for many NumPy versions. Is this error familiar at all @serge-sans-paille ?

**Comment by lucascolley** [comment]
@puni073 would you be able to tell us which Pythran and NumPy versions are used during the build? Or perhaps post the full build log as a GitHub Gist?

**Comment by puni073** [comment]
```
      Program pythran found: YES 0.17.0 0.17.0 (/tmp/pip-build-env-wmzzm5ol/ove
rlay/bin/pythran)
```
```
      numpy-config found: YES (/tmp/pip-build-env-wmzzm5ol/overlay/bin/numpy-config) 2.2.3
      Run-time dependency numpy found: YES 2.2.3
```

**Comment by serge-sans-paille** [comment]
It works with pythran 0.15 (see https://godbolt.org/z/dM4Wxs84P) and also on my setup (same code, python 3.12.8, pythran top-of-tree, numpy 2.2.3). I've tested pythran 0.17 and it works too. @puni073 can you check if that works on your setup but using cpython instead of pypy?

**Comment by puni073** [comment]
Could you reproduce the issue using PyPy3.11 first?
PyPy3.10 builds Scipy successfully but PyPy3.11 does not on my setup.

**Comment by lucascolley** [comment]
cc @mattip @cfbolz for PyPy

**Comment by serge-sans-paille** [comment]
I've added CI for pypy 3.11 in pythran to be sure and I can reproduce: https://github.com/serge-sans-paille/pythran/actions/runs/13500802735/job/37718473073?pr=2280. This seems to be specific to pypy3.11, but why o_O ?

**Comment by lucascolley** [comment]
tentatively/optimistically adding the upstream bug label, as this probably should work given that it works with cpython and other pypy versions

**Comment by cfbolz** [comment]
"      WARNING: Overriding pythran description with argspec information for: numpy.zeros" this is a message a little bit above the actual error, that looks a little bit suspicious, given that the actual error?

**Comment by serge-sans-paille** [comment]
yes. Here is a simple pypy scession that showcases the issue:

```
>>>> import inspect, numpy
>>>> inspect.getfullargspec(numpy.zeros)
FullArgSpec(args=['self'], varargs='args', varkw='keywords', defaults=None, kwonlyargs=[], kwonlydefaults=None, annotations={})
>>>> inspect.getfullargspec(numpy.ones)
FullArgSpec(args=['shape', 'dtype', 'order'], varargs=None, varkw=None, defaults=(None, 'C'), kwonlyargs=['device', 'like'], kwonlydefaults={'device': None, 'like': None}, annotations={})
```

basically the introspection for numpy.zeros seems to be incomplete (if not incorrect)

**Comment by serge-sans-paille** [comment]
@cfbolz does that ring any bell?

**Comment by cfbolz** [comment]
@serge-sans-paille ok, but we would have to find a difference between pypy 3.10 and 3.11. what I'm seeing is this:

PyPy 3.10:
```
>>>> import inspect, numpy
>>>> inspect.getfullargspec(numpy.zeros)
Traceback (most recent call last):
  File "/home/cfbolz/bin/pypy3.10-v7.3.17-linux64/lib/pypy3.10/inspect.py", line 1287, in getfullargspec
    sig = _signature_from_callable(func,
  File "/home/cfbolz/bin/pypy3.10-v7.3.17-linux64/lib/pypy3.10/inspect.py", line 2508, in _signature_from_callable
    return _signature_from_builtin(sigcls, obj,
  File "/home/cfbolz/bin/pypy3.10-v7.3.17-linux64/lib/pypy3.10/inspect.py", line 2302, in _signature_from_builtin
    raise ValueError("no signature found for builtin {!r}".format(func))
ValueError: no signature found for builtin <builtin_function_or_method object at 0x00007f0ea5bcdbe0>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<python-input-1>", line 1, in <module>
    inspect.getfullargspec(numpy.zeros)
  File "/home/cfbolz/bin/pypy3.10-v7.3.17-linux64/lib/pypy3.10/inspect.py", line 1297, in getfullargspec
    raise TypeError('unsupported callable') from ex
TypeError: unsupported callable
>>>> inspect.getfullargspec(numpy.ones)
FullArgSpec(args=['shape', 'dtype', 'order'], varargs=None, varkw=None, defaults=(None, 'C'), kwonlyargs=['device', 'like'], kwonlydefaults={'device': None, 'like': None}, annotations={})
```

PyPy 3.11

```
>>>> import inspect, numpy
>>>> inspect.getfullargspec(numpy.zeros)
FullArgSpec(args=['self'], varargs='args', varkw='keywords', defaults=None, kwonlyargs=[], kwonlydefaults=None, annotations={})
>>>> inspect.getfullargspec(numpy.ones)
FullArgSpec(args=['shape', 'dtype', 'order'], varargs=None, varkw=None, defaults=(None, 'C'), kwonlyargs=['device', 'like'], kwonlydefaults={'device': None, 'like': None}, annotations={})
```

So the problem is that inspect of `numpy.zeros` gives an incomplete result on 3.11, whereas it used to raise an error on 3.10

/cc @mattip

**Comment by lucascolley** [comment]
perhaps we should move this discussion to the PyPy repo?

**Comment by mattip** [comment]
Fixed in PyPy via pypy/pypy#5227 will be part of an upcoming bug-fix release. Thanks for trying out the first PyPy3.11 release.
