### PR TITLE
MAINT: stats.rv_count: revert gh-17236

### LINKED ISSUE #8057: Subclass of scipy.stats.rv_discrete initiated with values throws an AttributeError on pmf method
Subclass of `scipy.stats.rv_discrete` initiated with values (i.e `rv_sample`) throws an error if `pmf `method is called. The same without subclassing works fine.

### Reproducing code example:
```
from scipy import stats 

class subc_rv_discrete(stats.rv_discrete):
    pass

xk = (0,1,2,3)
pk = (0.1, 0.2, 0.3, 0.4)

inst = subc_rv_discrete(values=(xk, pk))
inst.pmf(xk)
```
### Error message:
```
Traceback (most recent call last):

  File "<ipython-input-48-129655c38e6a>", line 10, in <module>
    inst.pmf(xk)

  File "C:\Anaconda3\lib\site-packages\scipy\stats\_distn_infrastructure.py", line 2832, in pmf
    args, loc, _ = self._parse_args(*args, **kwds)

AttributeError: 'rv_sample' object has no attribute '_parse_args'
```
### Scipy/Numpy/Python version information:
```
0.19.0 1.12.1 sys.version_info(major=3, minor=6, micro=1, releaselevel='final', serial=0)
```

### PR DESCRIPTION
**Pull request by mdhaber**
#### Reference issue
gh-17236

#### What does this implement/fix?
gh-17236 introduced `rv_count`, a discrete analog of `rv_histogram`. It is really just a wrapper of the corresponding feature of `rv_discrete` needed to fix gh-8057. However, https://github.com/scipy/scipy/pull/17236#issuecomment-1288420090 exposed many bugs in this feature of `rv_count` (stemming from shortcomings of `rv_discrete`), so I don't think we should announce this as a new feature. Since SciPy 1.10 is branching soon, I think we need to revert so we can take our time to resolve these issues.

### CODE REVIEW

**Comment by ev-br** [comment]
https://github.com/scipy/scipy/pull/17236#issuecomment-1288420090 is certainly on my TODO list. Whether I'll manage to actually work on this or not in the 1.10 timeframe remains to be see though.

**Comment by mdhaber** [comment]
Ok! I figured it would be good to have this ready to go just in case...

**Comment by tylerjereddy** [comment]
One thing I'd like to ask is that we make a decision here pretty soon, because we're 10 days from the branching point.

The milestone makes sense, because it sounds like we really may have a problem if we release without taking some kind of action, but if the desired solution isn't realistic within 10 days I'd obviously prefer to avoid a last minute scramble, and we're at 31 milestone PRs still!

**Comment by tylerjereddy** [comment]
@ev-br @mdhaber will the alternative likely be merged by Tuesday or should we proceed with reverting?

**Comment by ev-br** [comment]
An alternative won't make it before branching, so let's revert for 1.10.0 and plan to redo this for 1.11. Thanks Matt, Tyler.
