### ISSUE TITLE
linprog kwargs not recognised

### ISSUE THREAD

**Issue by lucas-wilkins** [scipy/scipy#14514]
`scipy.optimize.linprog` is supposed to accept keywords `rr_method` and `autoscale`, but they are not recognised (c.1.7.0 at least), raising a TypeError

#### Reproducing code example:

```
result = linprog(np.array([1,1]), A_eq=np.array([[1,0]]), b_eq=1, A_ub=np.array([[0,1]]), b_ub=np.array([2]), rr_method="SVD")
# ERROR

result = linprog(np.array([1,1]), A_eq=np.array([[1,0]]), b_eq=1, A_ub=np.array([[0,1]]), b_ub=np.array([2]), autoscale=True)
# ERROR

```

#### Error message:

```
Traceback (most recent call last):
  File <REDACTED>, line 7, in <module>
    result = linprog(np.array([1,1]), A_eq=np.array([[1,0]]), b_eq=1, A_ub=np.array([[0,1]]), b_ub=np.array([2]), rr_method="SVD")
TypeError: linprog() got an unexpected keyword argument 'rr_method'

```
similarly for autoscale

#### Scipy/Numpy/Python version information:
```
1.7.0 1.20.1 sys.version_info(major=3, minor=8, micro=6, releaselevel='final', serial=0)
```

Also doesn't work on 1.6

**Comment by mdhaber** [comment]
They are not keywords; they need to be part of the `options` dictionary, e.g.
```
result = linprog(np.array([1,1]), A_eq=np.array([[1,0]]), b_eq=1, A_ub=np.array([[0,1]]), b_ub=np.array([2]), options={'rr_method':'SVD'})
```

For new code, I'd recommend one of the HiGHS methods, which do not use these options.

**Comment by lucas-wilkins** [comment]
Oh, I see, I didn't notice that they were subheadings of the option keyword documentation, not the documentation for the keywords themselves.

**Comment by eschanet** [comment]
Hi! In case no one else is already on this, I would be down to adding an example for how to use `'options'` to the docs.
