### ISSUE TITLE
BUG: TestInterop.test_splrep_errors blocking 1.2.1 wheel builds

### ISSUE THREAD

**Issue by tylerjereddy** [scipy/scipy#9777]
The `1.2.1` wheel builds are experiencing both Windows ([see matrix](https://ci.appveyor.com/project/scipy/scipy-wheels/builds/22183437)) and POSIX ([see matrix](https://travis-ci.org/MacPython/scipy-wheels/builds/489822897)) failures for the test / traceback below the fold, and in short a message like `E           dfitpack.error: failed in converting 3rd argument 'y' of dfitpack.curfit to C/Fortran array`

<details>

```
_______________________ TestInterop.test_splrep_errors ________________________

[gw1] darwin -- Python 3.6.6 /Users/travis/build/MacPython/scipy-wheels/venv/bin/python



self = <scipy.interpolate.tests.test_bsplines.TestInterop object at 0x10c3316a0>



    def test_splrep_errors(self):

        # test that both "old" and "new" splrep raise for an n-D ``y`` array

        # with n > 1

        x, y = self.xx, self.yy

        y2 = np.c_[y, y]

        with assert_raises(ValueError):

>           splrep(x, y2)



self       = <scipy.interpolate.tests.test_bsplines.TestInterop object at 0x10c3316a0>

x          = array([  0.        ,   0.31415927,   0.62831853,   0.9424778 ,

         1.25663706,   1.57079633,   1.88495559,   2.19... 10.36725576,  10.68141502,  10.99557429,

        11.30973355,  11.62389282,  11.93805208,  12.25221135,  12.56637061])

y          = array([  1.00000000e+00,   9.51056516e-01,   8.09016994e-01,

         5.87785252e-01,   3.09016994e-01,   6.12323400e-....28626380e-16,

         3.09016994e-01,   5.87785252e-01,   8.09016994e-01,

         9.51056516e-01,   1.00000000e+00])

y2         = array([[  1.00000000e+00,   1.00000000e+00],

       [  9.51056516e-01,   9.51056516e-01],

       [  8.09016994e-01,   ...6994e-01,   8.09016994e-01],

       [  9.51056516e-01,   9.51056516e-01],

       [  1.00000000e+00,   1.00000000e+00]])



../venv/lib/python3.6/site-packages/scipy/interpolate/tests/test_bsplines.py:623: 

_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

../venv/lib/python3.6/site-packages/scipy/interpolate/fitpack.py:289: in splrep

    res = _impl.splrep(x, y, w, xb, xe, k, task, s, t, full_output, per, quiet)

_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 



x = array([  0.        ,   0.31415927,   0.62831853,   0.9424778 ,

         1.25663706,   1.57079633,   1.88495559,   2.19... 10.36725576,  10.68141502,  10.99557429,

        11.30973355,  11.62389282,  11.93805208,  12.25221135,  12.56637061])

y = array([[  1.00000000e+00,   1.00000000e+00],

       [  9.51056516e-01,   9.51056516e-01],

       [  8.09016994e-01,   ...6994e-01,   8.09016994e-01],

       [  9.51056516e-01,   9.51056516e-01],

       [  1.00000000e+00,   1.00000000e+00]])

w = array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,

        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,

        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,

        1.,  1.])

xb = 0.0, xe = 12.566370614359172, k = 3, task = 0, s = 0.0

t = array([  0.00000000e+000,   2.68156176e+154,   2.35953965e+232,

         2.23887699e-046,   5.24588357e+180,   1.71359...5.00642076e-308,   0.00000000e+000,   0.00000000e+000,

         0.00000000e+000,   5.56268465e-308,   3.78576810e-270])

full_output = 0, per = 0, quiet = 1



    def splrep(x, y, w=None, xb=None, xe=None, k=3, task=0, s=None, t=None,

               full_output=0, per=0, quiet=1):

        """

        Find the B-spline representation of 1-D curve.

    

        Given the set of data points ``(x[i], y[i])`` determine a smooth spline

        approximation of degree k on the interval ``xb <= x <= xe``.

    

        Parameters

        ----------

        x, y : array_like

            The data points defining a curve y = f(x).

        w : array_like, optional

            Strictly positive rank-1 array of weights the same length as x and y.

            The weights are used in computing the weighted least-squares spline

            fit. If the errors in the y values have standard-deviation given by the

            vector d, then w should be 1/d. Default is ones(len(x)).

        xb, xe : float, optional

            The interval to fit.  If None, these default to x[0] and x[-1]

            respectively.

        k : int, optional

            The order of the spline fit. It is recommended to use cubic splines.

            Even order splines should be avoided especially with small s values.

            1 <= k <= 5

        task : {1, 0, -1}, optional

            If task==0 find t and c for a given smoothing factor, s.

    

            If task==1 find t and c for another value of the smoothing factor, s.

            There must have been a previous call with task=0 or task=1 for the same

            set of data (t will be stored an used internally)

    

            If task=-1 find the weighted least square spline for a given set of

            knots, t. These should be interior knots as knots on the ends will be

            added automatically.

        s : float, optional

            A smoothing condition. The amount of smoothness is determined by

            satisfying the conditions: sum((w * (y - g))**2,axis=0) <= s where g(x)

            is the smoothed interpolation of (x,y). The user can use s to control

            the tradeoff between closeness and smoothness of fit. Larger s means

            more smoothing while smaller values of s indicate less smoothing.

            Recommended values of s depend on the weights, w. If the weights

            represent the inverse of the standard-deviation of y, then a good s

            value should be found in the range (m-sqrt(2*m),m+sqrt(2*m)) where m is

            the number of datapoints in x, y, and w. default : s=m-sqrt(2*m) if

            weights are supplied. s = 0.0 (interpolating) if no weights are

            supplied.

        t : array_like, optional

            The knots needed for task=-1. If given then task is automatically set

            to -1.

        full_output : bool, optional

            If non-zero, then return optional outputs.

        per : bool, optional

            If non-zero, data points are considered periodic with period x[m-1] -

            x[0] and a smooth periodic spline approximation is returned. Values of

            y[m-1] and w[m-1] are not used.

        quiet : bool, optional

            Non-zero to suppress messages.

            This parameter is deprecated; use standard Python warning filters

            instead.

    

        Returns

        -------

        tck : tuple

            (t,c,k) a tuple containing the vector of knots, the B-spline

            coefficients, and the degree of the spline.

        fp : array, optional

            The weighted sum of squared residuals of the spline approximation.

        ier : int, optional

            An integer flag about splrep success. Success is indicated if ier<=0.

            If ier in [1,2,3] an error occurred but was not raised. Otherwise an

            error is raised.

        msg : str, optional

            A message corresponding to the integer flag, ier.

    

        Notes

        -----

        See splev for evaluation of the spline and its derivatives.

    

        The user is responsible for assuring that the values of *x* are unique.

        Otherwise, *splrep* will not return sensible results.

    

        See Also

        --------

        UnivariateSpline, BivariateSpline

        splprep, splev, sproot, spalde, splint

        bisplrep, bisplev

    

        Notes

        -----

        See splev for evaluation of the spline and its derivatives. Uses the

        FORTRAN routine curfit from FITPACK.

    

        If provided, knots `t` must satisfy the Schoenberg-Whitney conditions,

        i.e., there must be a subset of data points ``x[j]`` such that

        ``t[j] < x[j] < t[j+k+1]``, for ``j=0, 1,...,n-k-2``.

    

        References

        ----------

        Based on algorithms described in [1]_, [2]_, [3]_, and [4]_:

    

        .. [1] P. Dierckx, "An algorithm for smoothing, differentiation and

           integration of experimental data using spline functions",

           J.Comp.Appl.Maths 1 (1975) 165-184.

        .. [2] P. Dierckx, "A fast algorithm for smoothing data on a rectangular

           grid while using spline functions", SIAM J.Numer.Anal. 19 (1982)

           1286-1304.

        .. [3] P. Dierckx, "An improved algorithm for curve fitting with spline

           functions", report tw54, Dept. Computer Science,K.U. Leuven, 1981.

        .. [4] P. Dierckx, "Curve and surface fitting with splines", Monographs on

           Numerical Analysis, Oxford University Press, 1993.

    

        Examples

        --------

    

        >>> import matplotlib.pyplot as plt

        >>> from scipy.interpolate import splev, splrep

        >>> x = np.linspace(0, 10, 10)

        >>> y = np.sin(x)

        >>> tck = splrep(x, y)

        >>> x2 = np.linspace(0, 10, 200)

        >>> y2 = splev(x2, tck)

        >>> plt.plot(x, y, 'o', x2, y2)

        >>> plt.show()

    

        """

        if task <= 0:

            _curfit_cache = {}

        x, y = map(atleast_1d, [x, y])

        m = len(x)

        if w is None:

            w = ones(m, float)

            if s is None:

                s = 0.0

        else:

            w = atleast_1d(w)

            if s is None:

                s = m - sqrt(2*m)

        if not len(w) == m:

            raise TypeError('len(w)=%d is not equal to m=%d' % (len(w), m))

        if (m != len(y)) or (m != len(w)):

            raise TypeError('Lengths of the first three arguments (x,y,w) must '

                            'be equal')

        if not (1 <= k <= 5):

            raise TypeError('Given degree of the spline (k=%d) is not supported. '

                            '(1<=k<=5)' % k)

        if m <= k:

            raise TypeError('m > k must hold')

        if xb is None:

            xb = x[0]

        if xe is None:

            xe = x[-1]

        if not (-1 <= task <= 1):

            raise TypeError('task must be -1, 0 or 1')

        if t is not None:

            task = -1

        if task == -1:

            if t is None:

                raise TypeError('Knots must be given for task=-1')

            numknots = len(t)

            _curfit_cache['t'] = empty((numknots + 2*k + 2,), float)

            _curfit_cache['t'][k+1:-k-1] = t

            nest = len(_curfit_cache['t'])

        elif task == 0:

            if per:

                nest = max(m + 2*k, 2*k + 3)

            else:

                nest = max(m + k + 1, 2*k + 3)

            t = empty((nest,), float)

            _curfit_cache['t'] = t

        if task <= 0:

            if per:

                _curfit_cache['wrk'] = empty((m*(k + 1) + nest*(8 + 5*k),), float)

            else:

                _curfit_cache['wrk'] = empty((m*(k + 1) + nest*(7 + 3*k),), float)

            _curfit_cache['iwrk'] = empty((nest,), intc)

        try:

            t = _curfit_cache['t']

            wrk = _curfit_cache['wrk']

            iwrk = _curfit_cache['iwrk']

        except KeyError:

            raise TypeError("must call with task=1 only after"

                            " call with task=0,-1")

        if not per:

            n, c, fp, ier = dfitpack.curfit(task, x, y, w, t, wrk, iwrk,

>                                           xb, xe, k, s)

E           dfitpack.error: failed in converting 3rd argument `y' of dfitpack.curfit to C/Fortran array



_curfit_cache = {'iwrk': array([          0,           0,           0,           0,          13,

                 0,           8,     ...91e-003,

         7.86915649e-004,   2.13820142e-314,   0.00000000e+000,

         4.94065646e-324,   2.74390537e-003])}

full_output = 0

iwrk       = array([          0,           0,           0,           0,          13,

                 0,           8,           0, ...688015,   411828500,  1070759306,

                 0,           0,           0,           0,  1980694531], dtype=int32)

k          = 3

m          = 41

nest       = 45

per        = 0

quiet      = 1

s          = 0.0

t          = array([  0.00000000e+000,   2.68156176e+154,   2.35953965e+232,

         2.23887699e-046,   5.24588357e+180,   1.71359...5.00642076e-308,   0.00000000e+000,   0.00000000e+000,

         0.00000000e+000,   5.56268465e-308,   3.78576810e-270])

task       = 0

w          = array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,

        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,

        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,

        1.,  1.])

wrk        = array([  0.00000000e+000,   6.42285340e-323,   0.00000000e+000,

         6.42285340e-323,   0.00000000e+000,   0.00000...391e-003,

         7.86915649e-004,   2.13820142e-314,   0.00000000e+000,

         4.94065646e-324,   2.74390537e-003])

x          = array([  0.        ,   0.31415927,   0.62831853,   0.9424778 ,

         1.25663706,   1.57079633,   1.88495559,   2.19... 10.36725576,  10.68141502,  10.99557429,

        11.30973355,  11.62389282,  11.93805208,  12.25221135,  12.56637061])

xb         = 0.0

xe         = 12.566370614359172

y          = array([[  1.00000000e+00,   1.00000000e+00],

       [  9.51056516e-01,   9.51056516e-01],

       [  8.09016994e-01,   ...6994e-01,   8.09016994e-01],

       [  9.51056516e-01,   9.51056516e-01],

       [  1.00000000e+00,   1.00000000e+00]])



../venv/lib/python3.6/site-packages/scipy/interpolate/_fitpack_impl.py:502: error

----------------------------- Captured stderr call -----------------------------

too many axes: 2 (effrank=2), expected rank=1
```

</details>

There seems to be some correlation between the observation of a single test failure and an older version of NumPy for wheel builds.

**Comment by tylerjereddy** [comment]
I've reproduced this on SciPy master locally using new vs. old NumPy versions. The input values at the point of failure in the code look very similar with each NumPy version, but I'm continuing to dissect.

**Comment by tylerjereddy** [comment]
SciPy master fails the test with NumPy `1.13.3` and passes with NumPy `1.14.0`. I'll report back when I finish bisecting, which is taking a while because of the clean builds and two projects involved, etc.

**Comment by tylerjereddy** [comment]
I've bisected to the first (oldest) NumPy commit that allows the SciPy test in question to **pass**, which is from @WarrenWeckesser (note that `bad` here means that the test passed), but after the version of NumPy we claim to support on master: 

```
1f1e8265af27e7f602a0428acf06c8201ebef915 is the first bad commit
commit 1f1e8265af27e7f602a0428acf06c8201ebef915
Author: Warren Weckesser <warren.weckesser@gmail.com>
Date:   Tue Jun 27 00:25:57 2017 -0400

    BUG: f2py: Convert some error messages printed to stderr to exceptions.

    In f2py/src/fortranobject.c, the function `check_and_fix_dimensions` does
    pretty much what it says on the tin:
```

Clearly an `f2py` issue, and I've confirmed other Fortran-related failures on master, but apparently just the one for the `1.2.x` wheel builds.

A plan of action might look something like this:

- PR with a commit to activate 1.13.3 testing "for real" (see #9784) in our CI, and show it fails
- another commit in the above PR to somehow allow the suite to pass with 1.13.3, perhaps via a compatibility layer? could get ugly
- perhaps try to backport the above CI & f2py patches to the LTS maintenance branch, then retry wheel builds

Alternatively, I suppose a more aggressive stance on NumPy versions might be decided on, and the patching might only happen for the LTS branch? @rgommers

**Comment by rgommers** [comment]
`TestInterop.test_splrep_errors` tests for this:
```
        # test that both "old" and "new" splrep raise for an n-D ``y`` array
        # with n > 1
```
That's not actually very critical. I propose to mark that as `xfail` on `1.2.x`. That should fix all wheel builds, and at that point 1.2.1 can be released. This is way more critical - we're still in a place where 1.2.0 cannot be built from source on Python 2.7. Changing CI to really pick up 1.13.3 on the LTS branch is good to do, but can also be done after releasing v1.2.1

Then we get to master, where we need a real fix - would be good to open a PR that shows all failures, as I suggested in gh-9784. I'm not yet clear on the impact, so no opinion yet on the "could get ugly" part.

**Comment by rgommers** [comment]
this was solved, closing.
