### ISSUE TITLE
scipy/spatial/tests/test_kdtree.py::Test_random_ball_compiled::test_in_ball() crash on Python 3.8

### ISSUE THREAD

**Issue by vstinner** [scipy/scipy#10227]
Hi,

We are trying to build scipy 1.3 in Fedora using Python 3.8.0a4 and numpy 1.16.3, but a test does fails with an assertion error:

```
$ python runtests.py --tests 'scipy/spatial/tests/test_kdtree.py::Test_random_ball_compiled::test_in_ball' -v
Building, see build.log...
Build OK (0:00:02.003250 elapsed)
(...)
scipy/spatial/tests/test_kdtree.py::Test_random_ball_compiled::test_in_ball
Aborted (core dumped)
```

I reproduced this issue on Fedora Rawhide using:

```
sudo dnf install -y openblas-devel gcc-gfortran patch
sudo dnf debuginfo-install python38

# remove deprecation warning
sudo vim /usr/lib64/python3.8/inspect.py +1114

python3.8 -m venv env
python -m pip install pytest

./env/bin/pip install -U  https://github.com/cython/cython/archive/0.29.8.zip
wget https://files.pythonhosted.org/packages/93/48/956b9dcdddfcedb1705839280e02cbfeb2861ed5d7f59241210530867d5b/numpy-1.16.3.zip
unzip -d . numpy-1.16.3.zip 
cd numpy-1.16.3
rm -f -v $(grep -rl '/\* Generated by Cython')  PKG-INFO
python setup.py install

cd

wget 'https://files.pythonhosted.org/packages/cb/97/361c8c6ceb3eb765371a702ea873ff2fe112fa40073e7d2b8199db8eb56e/scipy-1.3.0.tar.gz'
tar -xf scipy-1.3.0.tar.gz 
cd scipy-1.3.0

wget https://src.fedoraproject.org/rpms/scipy/raw/master/f/acceptable_failure_rate.patch
patch -p1 < acceptable_failure_rate.patch 

# Run the whole test suite
# python runtests.py  -v

# Only run the test which crash
# python runtests.py --tests 'scipy/spatial/tests/test_kdtree.py::Test_random_ball_compiled::test_in_ball'

gdb -args python runtests.py --tests 'scipy/spatial/tests/test_kdtree.py::Test_random_ball_compiled::test_in_ball'
```

I had to compile numpy manully since numpy includes code generated by Cython which is not compatible with Python 3.8. Cython 0.29.8 is going to be released soon with the fix (version tagged in Git, not published yet).

gdb traceback:

```
scipy/spatial/tests/test_kdtree.py::Test_random_ball_compiled::test_in_ball

Program received signal SIGABRT, Aborted.
0x00007ffff7e383f5 in raise () from /lib64/libc.so.6

(gdb) where
#0  0x00007ffff7e383f5 in raise () from /lib64/libc.so.6
#1  0x00007ffff7e228d9 in abort () from /lib64/libc.so.6
#2  0x00007ffff51cf338 in std::__replacement_assert (__file=__file@entry=0x7ffff52172a8 "/usr/include/c++/9/bits/stl_vector.h", __line=__line@entry=1120, 
    __function=__function@entry=0x7ffff52175f0 "std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::front() [with _Tp = long int; _Alloc = std::allocator<long int>; std::vector<_Tp, _Alloc>::reference = long int&]", __condition=__condition@entry=0x7ffff52171c8 "__builtin_expect(!this->empty(), true)")
    at /usr/include/c++/9/x86_64-redhat-linux/bits/c++config.h:2533
#3  0x00007ffff51ce7e7 in std::vector<long, std::allocator<long> >::front (this=<optimized out>) at scipy/spatial/ckdtree.cxx:10696
#4  __pyx_pf_5scipy_7spatial_7ckdtree_7cKDTree_16query_ball_point__thread_func (__pyx_v_stop=<optimized out>, __pyx_v_start=<optimized out>, __pyx_self=<optimized out>) at scipy/spatial/ckdtree.cxx:10709
#5  __pyx_pw_5scipy_7spatial_7ckdtree_7cKDTree_16query_ball_point_1_thread_func (__pyx_self=<optimized out>, __pyx_args=<optimized out>, __pyx_kwds=<optimized out>) at scipy/spatial/ckdtree.cxx:10351
#6  0x00007ffff519f281 in __Pyx_PyObject_Call (kw=0x0, arg=<optimized out>, func=<cython_function_or_method at remote 0x7ffff5b01040>) at scipy/spatial/ckdtree.cxx:35485
#7  __pyx_pf_5scipy_7spatial_7ckdtree__run_threads (__pyx_self=<optimized out>, __pyx_v_n_jobs=<optimized out>, __pyx_v_n=<optimized out>, __pyx_v__thread_func=<optimized out>) at scipy/spatial/ckdtree.cxx:16478
#8  __pyx_pw_5scipy_7spatial_7ckdtree_1_run_threads (__pyx_self=<optimized out>, __pyx_args=<optimized out>, __pyx_kwds=<optimized out>) at scipy/spatial/ckdtree.cxx:16001
#9  0x00007ffff7bb804f in cfunction_call_varargs (kwargs=<optimized out>, args=<optimized out>, func=<built-in function _run_threads>) at /usr/src/debug/python38-3.8.0~a4-2.fc31.x86_64/Objects/call.c:755
#10 PyCFunction_Call (func=<built-in function _run_threads>, args=<optimized out>, kwargs=<optimized out>) at /usr/src/debug/python38-3.8.0~a4-2.fc31.x86_64/Objects/call.c:786
#11 0x00007ffff51800b6 in __Pyx_PyObject_Call (func=<built-in function _run_threads>, arg=(<cython_function_or_method at remote 0x7ffff5b01040>, 1, 1), kw=0x0) at scipy/spatial/ckdtree.cxx:35485
#12 0x00007ffff51bf115 in __pyx_pf_5scipy_7spatial_7ckdtree_7cKDTree_8query_ball_point (__pyx_v_self=__pyx_v_self@entry=0x7ffff5c33318, __pyx_v_x=__pyx_v_x@entry=<numpy.ndarray at remote 0x7ffff2221850>, __pyx_v_r=<numpy.ndarray at remote 0x7ffff21f0ad0>, __pyx_v_r@entry=<float at remote 0x7ffff25362d0>, 
    __pyx_v_p=<optimized out>, __pyx_v_eps=<optimized out>, __pyx_v_n_jobs=1, __pyx_v_return_sorted=<optimized out>, __pyx_v_return_length=<optimized out>) at scipy/spatial/ckdtree.cxx:11750
#13 0x00007ffff51c2a8e in __pyx_pw_5scipy_7spatial_7ckdtree_7cKDTree_9query_ball_point (__pyx_v_self=__pyx_v_self@entry=<scipy.spatial.ckdtree.cKDTree at remote 0x7ffff5c33318>, __pyx_args=__pyx_args@entry=(<numpy.ndarray at remote 0x7ffff2221850>, <float at remote 0x7ffff25362d0>), 
    __pyx_kwds=__pyx_kwds@entry={'p': <float at remote 0x7ffff2536348>, 'eps': 0}) at scipy/spatial/ckdtree.cxx:10273
#14 0x00007ffff7be4a84 in _PyMethodDef_RawFastCallKeywords (method=<optimized out>, self=<scipy.spatial.ckdtree.cKDTree at remote 0x7ffff5c33318>, args=<optimized out>, nargs=<optimized out>, kwnames=<optimized out>) at /usr/src/debug/python38-3.8.0~a4-2.fc31.x86_64/Objects/call.c:692
#15 0x00007ffff7be4ae3 in _PyCFunction_FastCallKeywords (func=<built-in method query_ball_point of scipy.spatial.ckdtree.cKDTree object at remote 0x7ffff5c33318>, args=<optimized out>, nargs=<optimized out>, kwnames=<optimized out>) at /usr/src/debug/python38-3.8.0~a4-2.fc31.x86_64/Objects/call.c:732
#16 0x00007ffff7bef23c in call_function (pp_stack=0x7fffffff7818, oparg=<optimized out>, kwnames=('p', 'eps')) at /usr/src/debug/python38-3.8.0~a4-2.fc31.x86_64/Python/ceval.c:4763
#17 0x00007ffff7c1bf7d in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at /usr/src/debug/python38-3.8.0~a4-2.fc31.x86_64/Python/ceval.c:3317
#18 0x00007ffff7ba7e7a in function_code_fastcall (globals=<optimized out>, nargs=1, args=<optimized out>, co=<optimized out>) at /usr/src/debug/python38-3.8.0~a4-2.fc31.x86_64/Objects/call.c:285
#19 _PyFunction_FastCallDict (func=<optimized out>, args=0x7fffffff7980, nargs=1, kwargs={}) at /usr/src/debug/python38-3.8.0~a4-2.fc31.x86_64/Objects/call.c:324
#20 0x00007ffff7bb69f6 in _PyObject_Call_Prepend (callable=<function at remote 0x7ffff2253740>, obj=<optimized out>, args=(), kwargs={}) at /usr/src/debug/python38-3.8.0~a4-2.fc31.x86_64/Objects/call.c:906
#21 0x00007ffff7bb279e in PyObject_Call (callable=<method at remote 0x7ffff5c0c8c8>, args=<optimized out>, kwargs=<optimized out>) at /usr/src/debug/python38-3.8.0~a4-2.fc31.x86_64/Objects/call.c:247
#22 0x00007ffff7c1aaca in do_call_core (kwdict={}, callargs=(), func=<method at remote 0x7ffff5c0c8c8>) at /usr/src/debug/python38-3.8.0~a4-2.fc31.x86_64/Python/ceval.c:4865
#23 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at /usr/src/debug/python38-3.8.0~a4-2.fc31.x86_64/Python/ceval.c:3361
#24 0x00007ffff7ba7141 in _PyEval_EvalCodeWithName (_co=<optimized out>, globals=<optimized out>, locals=<optimized out>, args=<optimized out>, argcount=<optimized out>, kwnames=0x0, kwargs=0x0, kwcount=<optimized out>, kwstep=2, defs=0x0, defcount=0, kwdefs=0x0, closure=0x0, name='pytest_pyfunc_call', 
```

Python traceback:

```
(gdb) py-bt
Traceback (most recent call first):
  <built-in method query_ball_point of scipy.spatial.ckdtree.cKDTree object at remote 0x7ffff5c33318>
  File "/home/vstinner/scipy-1.3.0/build/testenv/lib64/python3.8/site-packages/scipy/spatial/tests/test_kdtree.py", line 283, in test_in_ball
    l = self.T.query_ball_point(x, self.d, p=self.p, eps=self.eps)
  File "/home/vstinner/env/lib64/python3.8/site-packages/_pytest/python.py", line 179, in pytest_pyfunc_call
    testfunction(**testargs)
  File "/home/vstinner/env/lib64/python3.8/site-packages/pluggy/callers.py", line 443, in _multicall
  File "/home/vstinner/env/lib64/python3.8/site-packages/pluggy/manager.py", line 334, in <lambda>
    def after(outcome, hook_name, methods, kwargs):
  File "/home/vstinner/env/lib64/python3.8/site-packages/pluggy/manager.py", line 87, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/vstinner/env/lib64/python3.8/site-packages/pluggy/hooks.py", line 1057, in __call__
  File "/home/vstinner/env/lib64/python3.8/site-packages/_pytest/python.py", line 1467, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "/home/vstinner/env/lib64/python3.8/site-packages/_pytest/runner.py", line 122, in pytest_runtest_call
    item.runtest()
  File "/home/vstinner/env/lib64/python3.8/site-packages/pluggy/callers.py", line 443, in _multicall
  File "/home/vstinner/env/lib64/python3.8/site-packages/pluggy/manager.py", line 334, in <lambda>
    def after(outcome, hook_name, methods, kwargs):
  File "/home/vstinner/env/lib64/python3.8/site-packages/pluggy/manager.py", line 87, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/vstinner/env/lib64/python3.8/site-packages/pluggy/hooks.py", line 1057, in __call__
  File "/home/vstinner/env/lib64/python3.8/site-packages/_pytest/runner.py", line 197, in <lambda>
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
  File "/home/vstinner/env/lib64/python3.8/site-packages/_pytest/runner.py", line 225, in from_call
    result = func()
  File "/home/vstinner/env/lib64/python3.8/site-packages/_pytest/runner.py", line 452, in call_runtest_hook
  File "/home/vstinner/env/lib64/python3.8/site-packages/_pytest/runner.py", line 172, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
  File "/home/vstinner/env/lib64/python3.8/site-packages/_pytest/runner.py", line 92, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
  File "/home/vstinner/env/lib64/python3.8/site-packages/_pytest/runner.py", line 77, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File "/home/vstinner/env/lib64/python3.8/site-packages/pluggy/callers.py", line 443, in _multicall
  File "/home/vstinner/env/lib64/python3.8/site-packages/pluggy/manager.py", line 334, in <lambda>
    def after(outcome, hook_name, methods, kwargs):
  File "/home/vstinner/env/lib64/python3.8/site-packages/pluggy/manager.py", line 87, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/vstinner/env/lib64/python3.8/site-packages/pluggy/hooks.py", line 1057, in __call__
  File "/home/vstinner/env/lib64/python3.8/site-packages/_pytest/main.py", line 270, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File "/home/vstinner/env/lib64/python3.8/site-packages/pluggy/callers.py", line 443, in _multicall
  File "/home/vstinner/env/lib64/python3.8/site-packages/pluggy/manager.py", line 334, in <lambda>
    def after(outcome, hook_name, methods, kwargs):
  File "/home/vstinner/env/lib64/python3.8/site-packages/pluggy/manager.py", line 87, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/vstinner/env/lib64/python3.8/site-packages/pluggy/hooks.py", line 1057, in __call__
  File "/home/vstinner/env/lib64/python3.8/site-packages/_pytest/main.py", line 249, in _main
    config.hook.pytest_runtestloop(session=session)
  File "/home/vstinner/env/lib64/python3.8/site-packages/_pytest/main.py", line 205, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File "/home/vstinner/env/lib64/python3.8/site-packages/_pytest/main.py", line 242, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/home/vstinner/env/lib64/python3.8/site-packages/pluggy/callers.py", line 443, in _multicall
  File "/home/vstinner/env/lib64/python3.8/site-packages/pluggy/manager.py", line 334, in <lambda>
    def after(outcome, hook_name, methods, kwargs):
  File "/home/vstinner/env/lib64/python3.8/site-packages/pluggy/manager.py", line 87, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/vstinner/env/lib64/python3.8/site-packages/pluggy/hooks.py", line 1057, in __call__
  File "/home/vstinner/env/lib64/python3.8/site-packages/_pytest/config/__init__.py", line 847, in main
    self.pluginmanager.consider_env()
  File "/home/vstinner/scipy-1.3.0/build/testenv/lib64/python3.8/site-packages/scipy/_lib/_testutils.py", line 61, in __call__
    code = pytest.main(pytest_args)
  File "runtests.py", line 8474, in main
  File "runtests.py", line 732, in <module>
```

Versions:

```
$ pip freeze
atomicwrites==1.3.0
attrs==19.1.0
Cython==0.29.8
importlib-metadata==0.15
more-itertools==7.0.0
numpy==1.16.3
pluggy==0.12.0
py==1.8.0
pytest==4.5.0
scipy==1.3.0
six==1.12.0
wcwidth==0.1.7
zipp==0.5.1
```

**Comment by vstinner** [comment]
I recompiled scipy without compiler optimizations:

```
rm -rf build
CFLAGS="-O0" CXXFLAGS="-O0" python setup.py build 
```

gdb gives better info:

```
Program received signal SIGABRT, Aborted.
0x00007ffff7e383f5 in raise () from /lib64/libc.so.6

(gdb) up
#4  0x00007ffff4e3912b in __pyx_pf_5scipy_7spatial_7ckdtree_7cKDTree_16query_ball_point__thread_func (__pyx_self=<cython_function_or_method at remote 0x7ffff5afa040>, __pyx_v_start=0, __pyx_v_stop=1) at scipy/spatial/ckdtree.cxx:10709
fmrae
10709	      __pyx_v_cur = (&(__pyx_v_vvres[__pyx_v_i])->front());

(gdb) p __pyx_v_i
$1 = 0
(gdb) p **__pyx_v_vvres
$4 = std::vector of length 0, capacity 0


(gdb) l 10700
10695	      PyList_SET_ITEM(__pyx_t_13, 0, Py_None);
10696	      __pyx_t_14 = PyNumber_Multiply(__pyx_v_m, __pyx_t_13); if (unlikely(!__pyx_t_14)) __PYX_ERR(0, 943, __pyx_L4_error)
10697	      __Pyx_GOTREF(__pyx_t_14);
10698	      __Pyx_DECREF(__pyx_t_13); __pyx_t_13 = 0;
10699	      __Pyx_XDECREF_SET(__pyx_v_tmp, __pyx_t_14);
10700	      __pyx_t_14 = 0;
10701	
10702	      /* "scipy/spatial/ckdtree.pyx":945
10703	 *                     tmp = m * [None]
10704	 * 
(gdb) l
10705	 *                     cur = &vvres[i].front()             # <<<<<<<<<<<<<<
10706	 *                     for j in range(m):
10707	 *                         tmp[j] = cur[0]
10708	 */
10709	      __pyx_v_cur = (&(__pyx_v_vvres[__pyx_v_i])->front());
10710	
10711	      /* "scipy/spatial/ckdtree.pyx":946
10712	 * 
10713	 *                     cur = &vvres[i].front()
10714	 *                     for j in range(m):             # <<<<<<<<<<<<<<
(gdb) 
10715	 *                         tmp[j] = cur[0]
10716	 *                         cur += 1
10717	 */
10718	      __pyx_t_14 = __Pyx_PyObject_CallOneArg(__pyx_builtin_range, __pyx_v_m); if (unlikely(!__pyx_t_14)) __PYX_ERR(0, 946, __pyx_L4_error)
10719	      __Pyx_GOTREF(__pyx_t_14);
10720	      if (likely(PyList_CheckExact(__pyx_t_14)) || PyTuple_CheckExact(__pyx_t_14)) {
10721	        __pyx_t_13 = __pyx_t_14; __Pyx_INCREF(__pyx_t_13); __pyx_t_15 = 0;
10722	        __pyx_t_16 = NULL;
10723	      } else {
```

**Comment by charris** [comment]
IIRC, there is a fix needed for Cython https://github.com/cython/cython/issues/2938. Looks like Cython 0.29.8 was released yesterday, you might try that.

**Comment by vstinner** [comment]
I used Cython 0.29.8 :-)

**Comment by hroncok** [comment]
BTW the acceptable_failure_rate patch only ad a pytest hook and shall not be needed to reproduce this.

**Comment by vstinner** [comment]
Are you able to reproduce the bug? Cython 0.29.10 is now fully compatible with Python 3.8 and Python 3.8 beta1 has been released. It should be easier to reproduce the bug.

**Comment by tylerjereddy** [comment]
I tried reproducing this using a [rawhide Dockerfile](https://github.com/tylerjereddy/rawhide_scipy_issue_10227-) I started drafting based on the above.

However, NumPy < 1.17 doesn't seem to build with pip installed cython + Python 3.8 in my hands using that container. Maybe you can suggest adjustments needed to that Dockerfile so I can iterate on the issue. The issue seems related to the Cython code in mtrand (@bashtage or @mattip may know more if there are known issues with 3.8 + new Cython). It seems you've suggested this should no longer exist with Cython 0.29.10, but pinning to that version has no effect for me.

Also worth noting that the approach described above appears to use OpenBLAS `0.3.6`, which isn't going to work anyway--indeed there's a recent discussion about this with another Fedora maintainer here: https://github.com/xianyi/OpenBLAS/issues/2137

Still, that's likely a separate issue, but probably best to use the same OpenBLAS commit hash we use for building wheels--latest stable OpenBLAS is often not the right choice unless we're also using it for wheels.

**Comment by bashtage** [comment]
I haven't seen any failures reported from mtrand.  Note that mtrand has been completely replaced (rewritten) for NumPy 1.17 (current master) so it may behave very differently.

**Comment by mattip** [comment]
Where is a log of the failure for numpy + cython 0.29.10 + cpython 3.8?

**Comment by tylerjereddy** [comment]
In the linked Dockerfile repo running `docker build -t issue_10227 .` should suffice to reproduce the issue

**Comment by mattip** [comment]
The relevant error message is

```
numpy/random/mtrand/mtrand.c:311:11: error: too few arguments to function ‘PyCode_New’
      311 |           PyCode_New(a, k, l, s, f, code, c, n, v, fv, cell, fn, name, fline, lnos)
          |           ^~~~~~~~~~
```

which is taken from cython's [code for `PyCode_New`](https://github.com/cython/cython/blob/0.29.10/Cython/Utility/ModuleSetupCode.c#L384). Note that it seems somehow the python  is defining `PY_VERSION_HEX < 0x030800A4` but still has a post-v3.8.0a4 definition of `PyCode_New`, you want the one with `PyCode_New(a, 0, k, l, s, f, ...`. How can you determine the contents of `python/include/patchlevel.h` and `python/include/code.h` in the docker, they seems to conflict?

More details about the error:

<details>

```
    numpy/random/mtrand/mtrand.c:311:11: error: too few arguments to function ‘PyCode_New’
      311 |           PyCode_New(a, k, l, s, f, code, c, n, v, fv, cell, fn, name, fline, lnos)
          |           ^~~~~~~~~~
    numpy/random/mtrand/mtrand.c:44554:15: note: in expansion of macro ‘__Pyx_PyCode_New’
    44554 |     py_code = __Pyx_PyCode_New(
          |               ^~~~~~~~~~~~~~~~
    In file included from /usr/include/python3.8/compile.h:5,
                     from /usr/include/python3.8/Python.h:138,
                     from numpy/random/mtrand/mtrand.c:4:
    /usr/include/python3.8/code.h:122:28: note: declared here
      122 | PyAPI_FUNC(PyCodeObject *) PyCode_New(
          |                            ^~~~~~~~~~

```

**Comment by vstinner** [comment]
Cython 0.29.10 has been fixed to be updated for PyCode_New() new API. But there is no numpy release including regenerated Cython .c file yet.

Note: We are going to revert PyCode_New() API to Python 3.7 to avoid this issue: https://bugs.python.org/issue37221 And Cython will be modified to handle that for you ;-)

**Comment by pv** [comment]
Based on the traceback, this was fixed by gh-10567 --- please reopen if I'm wrong.
