### PR TITLE
DOC: clarify usage of options param in scipy.optimize.linprog

### LINKED ISSUE #14514: linprog kwargs not recognised
`scipy.optimize.linprog` is supposed to accept keywords `rr_method` and `autoscale`, but they are not recognised (c.1.7.0 at least), raising a TypeError

#### Reproducing code example:

```
result = linprog(np.array([1,1]), A_eq=np.array([[1,0]]), b_eq=1, A_ub=np.array([[0,1]]), b_ub=np.array([2]), rr_method="SVD")
# ERROR

result = linprog(np.array([1,1]), A_eq=np.array([[1,0]]), b_eq=1, A_ub=np.array([[0,1]]), b_ub=np.array([2]), autoscale=True)
# ERROR

```

#### Error message:

```
Traceback (most recent call last):
  File <REDACTED>, line 7, in <module>
    result = linprog(np.array([1,1]), A_eq=np.array([[1,0]]), b_eq=1, A_ub=np.array([[0,1]]), b_ub=np.array([2]), rr_method="SVD")
TypeError: linprog() got an unexpected keyword argument 'rr_method'

```
similarly for autoscale

#### Scipy/Numpy/Python version information:
```
1.7.0 1.20.1 sys.version_info(major=3, minor=8, micro=6, releaselevel='final', serial=0)
```

Also doesn't work on 1.6

### PR DESCRIPTION
**Pull request by eschanet**
#### Reference issue
Closes gh-14514.

#### What does this implement/fix?
Clarify how to use the `options` param in `scipy.optimize.linprog`.

#### Additional information
I added an example of how to use the `options` param (e.g. to print convergence messages) in the docs of `scipy.optimize.linprog`.

### CODE REVIEW

**Comment by mdhaber** [comment]
Thanks @eschanet!
@lucas-wilkins, would this resolve gh-14514 in your opinion?

**Comment by mdhaber** [comment]
@eschanet It looks like there are two lint errors (lines too long, whitespace on otherwise empty line) and doctest failure because the output didn't match exactly. There are ways around this, but the easiest thing might be to change `maxiter` (e.g. to 4) instead of showing `disp`.

**Comment by lucas-wilkins** [comment]
> Thanks @eschanet!
> @lucas-wilkins, would this resolve [gh-14514](https://github.com/scipy/scipy/issues/14514) in your opinion?

Sure, the example helps.

**Comment by eschanet** [comment]
@mdhaber I changed the example to use `maxiter` instead, this does indeed make it quite a bit easier to have the output match up. Linter should also be happy now.

File: scipy/optimize/_linprog.py [hunk 1]
```diff
@@ -575,6 +575,26 @@ def linprog(c, A_ub=None, b_ub=None, A_eq=None, b_eq=None,
...
+    You can use the ``options`` parameter, e.g.,
+    to restrict the maximum number of iterations.
+
+    >>> res = linprog(
+            c,
+            A_ub=A,
+            b_ub=b,
+            bounds=[x0_bounds, x1_bounds],
+            options={'maxiter': 4}
+        )
```
Comment (mdhaber) [inline scipy/optimize/_linprog.py:587]:
```suggestion
    You can use the ``options`` parameter, e.g.,
    to restrict the maximum number of iterations.

    >>> res = linprog(c, A_ub=A, b_ub=b, bounds=[x0_bounds, x1_bounds],
    ...               options={'maxiter': 4})
```
The `...` is needed to indicate line continuation in doctests.

File: scipy/optimize/_linprog.py [hunk 2]
```diff
@@ -575,6 +575,21 @@ def linprog(c, A_ub=None, b_ub=None, A_eq=None, b_eq=None,
...
+    ...               options={'maxiter': 4})
+    >>> print(res)
+        con: array([], dtype=float64)
+        fun: -21.35207150630408
+    message: 'The iteration limit was reached before the algorithm converged.'
+        nit: 4
+      slack: array([37.19406046,  0.5727398 ])
+     status: 1
+    success: False
+          x: array([ 9.4021973 , -2.98746855])
```
Comment (mdhaber) [inline scipy/optimize/_linprog.py:591]:
```suggestion
         con: array([], dtype=float64)
         fun: -21.35207150630407
     message: 'The iteration limit was reached before the algorithm converged.'
         nit: 4
       slack: array([37.19406046,  0.5727398 ])
      status: 1
     success: False
           x: array([ 9.4021973 , -2.98746855])
```

**Comment by mdhaber** [comment]
Thanks @eschanet @lucas-wilkins!
