### PR TITLE
MAINT: update supported versions of Python and NumPy to follow NEP29

### PR DESCRIPTION
**Pull request by tupui**
This PR does the work to follow [NEP29](https://numpy.org/neps/nep-0029-deprecation_policy.html) for the next release (1.11) which probably is going to be scheduled around June.

* Drop support for Python 3.8, hence NumPy >=1.22.4.
* Change the dev job to Python 12-dev instead of 11-dev. And bump all jobs 1 version up.
* Update ubuntu image from 20 to 22 (Focal to Jammy).

Not sure about a few things and could have forgot to update some lines, please check carefully.

Closes #17959

### CODE REVIEW

**Comment by andyfaff** [comment]
probably after #17950

**Comment by tupui** [comment]
Correct!

What is the link with your PR?

**Comment by andyfaff** [comment]
#17950 . There's a lot of overlap with the ci configs.

File: .github/workflows/linux_meson.yml [hunk 1]
```diff
@@ -59,12 +59,12 @@ jobs:
...
 
     - name: Install Python packages
-      if: matrix.python-version == '3.9'
+      if: matrix.python-version == '3.10'
       run: |
         python -m pip install numpy cython pytest pytest-xdist pytest-timeout pybind11 mpmath gmpy2 pythran ninja meson click rich-click doit pydevtool pooch
 
     - name: Install Python packages from repositories
-      if: matrix.python-version == '3.11-dev'
+      if: matrix.python-version == '3.12-dev'
```
Comment (rgommers) [inline .github/workflows/linux_meson.yml:67]: This is a few months too early probably - normally we start around May-June. I'd make this `3.11` and add a comment to switch it to `3.12-dev` in 4 months

File: doc/source/dev/toolchain.rst [hunk 2]
```diff
@@ -81,6 +81,7 @@ The table shows the NumPy versions suitable for each major Python version.
  1.9.0/1            >=3.8, <3.12                >=1.18.5, <1.25.0
  1.9.2              >=3.8, <3.12                >=1.18.5, <1.26.0
  1.10               >=3.8, <3.12                >=1.19.5, <1.26.0
+ 1.11               >=3.9, <3.13                >=1.22.4, <1.27.0
```
Comment (rgommers) [inline doc/source/dev/toolchain.rst:84]: Too early. `1.11.0` will not support Python 3.12 if it comes out around July.

File: pyproject.toml [hunk 3]
```diff
@@ -25,36 +25,25 @@ requires = [
...
 
     # default numpy requirements
-    "numpy==1.19.5; python_version=='3.8' and (platform_machine!='arm64' or platform_system!='Darwin') and platform_machine!='aarch64' and platform_machine!='loongarch64' and platform_python_implementation != 'PyPy'",
-    "numpy==1.19.5; python_version=='3.9' and (platform_machine!='arm64' or platform_system!='Darwin') and platform_machine!='loongarch64' and platform_python_implementation != 'PyPy'",
+    "numpy==1.22.4; python_version=='3.9' and (platform_machine!='arm64' or platform_system!='Darwin') and platform_machine!='loongarch64' and platform_python_implementation != 'PyPy'",
     # Note that 1.21.3 was the first version with a complete set of 3.10 wheels,
     # however macOS was broken and it's safe C API/ABI-wise to build against 1.21.6
     # (see oldest-supported-numpy issues gh-28 and gh-45)
-    "numpy==1.21.6; python_version=='3.10' and (platform_system!='Windows' and platform_machine!='loongarch64') and platform_python_implementation != 'PyPy'",
+    "numpy==1.22.4; python_version=='3.10' and (platform_system!='Windows' and platform_machine!='loongarch64') and platform_python_implementation != 'PyPy'",
```
Comment (rgommers) [inline pyproject.toml:38]: I don't understand most of the diff in this file. Why are there so many changes? All that should happen here is that the lines specific to Python 3.8 are dropped.

**Review by rgommers — CHANGES_REQUESTED** [review]
Thanks @tupui. A few initial comments.

The bump in NumPy versions from 1.19.5 to 1.22.4 (which is less than 9 months old) is quite aggressive. Unless there's a good reason for that, we should be more conservative and do a regular bump to 1.20.3 I'd say.

File: doc/source/dev/toolchain.rst (hunk 2 above)
Comment (tupui) [inline doc/source/dev/toolchain.rst:84]:
```suggestion
 1.11               >=3.9, <3.12                >=1.22.4, <1.27.0
```

File: pyproject.toml (hunk 3 above)
Comment (tupui) [reply pyproject.toml:38]: I removed lines with Python 3.8 and refs to NumPy bellow 1.22.4.

File: .github/workflows/linux_meson.yml (hunk 1 above)
Comment (tupui) [inline .github/workflows/linux_meson.yml:67]:
```suggestion
      if: matrix.python-version == '3.11'  # change to 3.12-dev when beta starts
```

**Review by tupui — COMMENTED** [review]
Thanks @rgommers 

> The bump in NumPy versions from 1.19.5 to 1.22.4 (which is less than 9 months old) is quite aggressive. Unless there's a good reason for that, we should be more conservative and do a regular bump to 1.20.3 I'd say.

I just think we should follow the NEP. 1.21 is supposed to be dropped around our release time in June.

```
On Apr 14, 2023 drop support for Python 3.8 (initially released on Oct 14, 2019)
On Jun 23, 2023 drop support for NumPy 1.21 (initially released on Jun 22, 2021)
```

Also, from what I have seen, our deps tend to update NumPy way faster than SciPy. By the time they update to 1.11, I don't think it would be an issue to require NumPy 1.21.

**Comment by tupui** [comment]
Not sure how to fix the failures otherwise (besides the linter)

File: azure-pipelines.yml [hunk 4]
```diff
@@ -177,29 +177,30 @@ stages:
             set -euo pipefail
             docker pull i386/ubuntu:bionic
             docker run -v $(pwd):/scipy i386/ubuntu:bionic /usr/bin/linux32 /bin/bash -c "cd scipy && \
```
Comment (tupui) [inline azure-pipelines.yml:179]: Maybe we could use this instead? https://hub.docker.com/r/i386/python

File: azure-pipelines.yml [hunk 5]
```diff
@@ -159,11 +159,11 @@ stages:
         tools/check_test_name.py
       displayName: 'Run Lint Checks'
       failOnStderr: true
-  - job: Linux_Python_38_32bit_full
+  - job: Linux_Python_39_32bit_full
     timeoutInMinutes: 90
     condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/main'))  # skip for PR merges
     pool:
-      vmImage: 'ubuntu-20.04'
+      vmImage: 'ubuntu-20.04'  # 22.04 does not have python3.9-dev
```
Comment (tupui) [inline azure-pipelines.yml:166]:
```suggestion
      vmImage: 'ubuntu-22.04'  # vm does not matter as we use docker
```

File: azure-pipelines.yml [hunk 6]
```diff
@@ -177,29 +177,30 @@ stages:
             set -euo pipefail
             docker pull i386/ubuntu:bionic
             docker run -v $(pwd):/scipy i386/ubuntu:bionic /usr/bin/linux32 /bin/bash -c "cd scipy && \
+            add-apt-repository ppa:deadsnakes/ppa && \
```
Comment (tupui) [inline azure-pipelines.yml:180]:
```suggestion
            docker pull i386/ubuntu:focal
            docker run -v $(pwd):/scipy i386/ubuntu:focal /usr/bin/linux32 /bin/bash -c "cd scipy && \
```

File: .github/workflows/linux_meson.yml [hunk 7]
```diff
@@ -33,12 +33,12 @@ jobs:
     runs-on: ubuntu-22.04
     strategy:
       matrix:
-        python-version: ['3.9', '3.11-dev']
+        python-version: ['3.10', '3.12-dev']
```
Comment (tupui) [inline .github/workflows/linux_meson.yml:36]:
```suggestion
        python-version: ['3.10', '3.11']  # change to 3.12-dev when beta starts
```

File: .github/workflows/linux_meson.yml [hunk 8]
```diff
@@ -33,12 +33,12 @@ jobs:
...
         maintenance-branch:
           - ${{ contains(github.ref, 'maintenance/') || contains(github.base_ref, 'maintenance/') }}
         exclude:
           - maintenance-branch: true
-            python-version: '3.11-dev'
+            python-version: '3.12-dev'
```
Comment (tupui) [inline .github/workflows/linux_meson.yml:41]:
```suggestion
            python-version: '3.11'
```

File: .github/workflows/linux_meson.yml [hunk 9]
```diff
@@ -59,12 +59,12 @@ jobs:
...
 
     - name: Install Python packages
-      if: matrix.python-version == '3.9'
+      if: matrix.python-version == '3.10'
       run: |
         python -m pip install numpy cython pytest pytest-xdist pytest-timeout pybind11 mpmath gmpy2 pythran ninja meson click rich-click doit pydevtool pooch
 
     - name: Install Python packages from repositories
-      if: matrix.python-version == '3.11-dev'
+      if: matrix.python-version == '3.11'  # change to 3.12-dev when beta starts
```
Comment (tupui) [inline .github/workflows/linux_meson.yml:67]:
```suggestion
      if: matrix.python-version == '3.11'
```

**Comment by tupui** [comment]
The Mypy error is a known bug and we would need to update mypy to work on Python 3.10. https://github.com/python/mypy/issues/13627

**Comment by tupui** [comment]
Locally I could bump mypy, there was just a very minor things to adjust. We could remove the mypy requirements file too. Not done yet in case we want to keep it for some reason.

**Comment by tupui** [comment]
@rgommers CI is mostly happy now, only 2 things remain.


- `scipy.scipy (Main Windows Python311-64bit-full-ilp64)` fails with:
```
scipy\_lib\_ccallback_c.c(198): fatal error C1083: Cannot open include file: 'longintrepr.h': No such file or directory
```

Not sure, some suggest to update Cython? Might be due to these lines `PyLong_AsVoidPtr(long(context_obj))`

- `macOS tests (setup.py) / macOS Test Matrix (3.9, --upgrade numpy) (pull_request)` fails with:

I don't know.

**Comment by mdhaber** [comment]
> I just think we should follow the NEP. 1.21 is supposed to be dropped around our release time in June.

Perhaps we can compromise. To get back on track with NEP 29 without a huge jump in one release: 

- Release SciPy 1.11.0 on or after June 23, 2023, and make NumPy 1.21 the minimum supported version for that release.
- Release SciPy 1.12.0 on or after January 1, 2024, and make NumPy 1.23 the minimum supported version for that release.

**Comment by rgommers** [comment]
> The Mypy error is a known bug and we would need to update mypy to work on Python 3.10. At least 0.981. [python/mypy#13627](https://github.com/python/mypy/issues/13627)
> 
> Not sure why we are pinning to 0.931. Also mypy 1.0 is out with great speed bump.

The exact version doesn't matter, a bump is usually fine. We do need to pin to an exact version because new Mypy versions very often have both regressions and changes in behavior. And even plain improvements result in errors, because `#type: ignore` commands for things that are supported in a newer version result in a complaint about an unnecessary skip IIRC.

**Comment by rgommers** [comment]
> `scipy.scipy (Main Windows Python311-64bit-full-ilp64)` fails with:

I suggest separating the problems here a bit. Just do not bump the version from 3.10 to 3.11 and open an issue for this one to fix in a separate PR.

File: pyproject.toml [hunk 10]
```diff
@@ -25,12 +25,10 @@ requires = [
 
     # now matches minimum supported version, keep here as separate requirement
     # to be able to sync more easily with oldest-supported-numpy
-    "numpy==1.19.5; python_version=='3.8' and platform_machine=='aarch64' and platform_python_implementation != 'PyPy'",
 
-    # arm64 on Darwin supports Python 3.8 and above requires numpy>=1.21.0
+    # arm64 on Darwin supports Python 3.9 and above requires numpy>=1.21.6
```
Comment (rgommers) [inline pyproject.toml:29]: The comment modification is incorrect, however this comment and the requirement below it can be deleted completely.

File: pyproject.toml [hunk 11]
```diff
@@ -41,8 +39,6 @@ requires = [
     "numpy==1.22.3; python_version=='3.10' and platform_system=='Windows' and platform_python_implementation != 'PyPy'",
 
     # default numpy requirements
-    "numpy==1.19.5; python_version=='3.8' and (platform_machine!='arm64' or platform_system!='Darwin') and platform_machine!='aarch64' and platform_machine!='loongarch64' and platform_python_implementation != 'PyPy'",
-    "numpy==1.19.5; python_version=='3.9' and (platform_machine!='arm64' or platform_system!='Darwin') and platform_machine!='loongarch64' and platform_python_implementation != 'PyPy'",
```
Comment (rgommers) [inline pyproject.toml:45]: You can't delete this line for Python 3.9, please revert this change.

**Review by rgommers — COMMENTED** [review]
Two more comments on the `pyproject.toml` changes.

File: pyproject.toml [hunk 12]
```diff
@@ -41,8 +35,7 @@ requires = [
...
+    "numpy==1.21.6; python_version=='3.9' and (platform_machine!='arm64' or platform_system!='Darwin') and platform_machine!='loongarch64' and platform_python_implementation != 'PyPy'",
```
Comment (rgommers) [inline pyproject.toml:38]: Still doesn't look 100% right. I didn't test, but I am fairly sure that `and (platform_machine!='arm64' or platform_system!='Darwin')` should now be removed here, because the alternative condition higher up was dropped. You need one, and exactly one, condition for every platform/OS/interpreter combo.

Comment (tupui) [reply pyproject.toml:38]:
```suggestion
    "numpy==1.21.6; python_version=='3.9' and platform_machine!='loongarch64' and platform_python_implementation != 'PyPy'",
```

**Comment by tupui** [comment]
2 remaining issues. I don't get what is missing.

For Azure I have no clue. For the macOS job, maybe linked to the pyproject.toml deps definition?? It seems to install but then fails in pip.

**Comment by rgommers** [comment]
gh-17950 is now merged, so this may need a tweak/rebase.

File: pyproject.toml [hunk 13]
```diff
@@ -25,12 +25,6 @@ requires = [
 
     # now matches minimum supported version, keep here as separate requirement
     # to be able to sync more easily with oldest-supported-numpy
-    "numpy==1.19.5; python_version=='3.8' and platform_machine=='aarch64' and platform_python_implementation != 'PyPy'",
-
-    # arm64 on Darwin supports Python 3.8 and above requires numpy>=1.21.0
-    # (first version with arm64 wheels available)
-    "numpy==1.21.0; python_version=='3.8' and platform_machine=='arm64' and platform_system=='Darwin'",
-    "numpy==1.21.0; python_version=='3.9' and platform_machine=='arm64' and platform_system=='Darwin'",
```
Comment (tupui) [inline pyproject.toml:28]:
```suggestion
    "numpy==1.21.6; python_version=='3.9' and platform_machine=='arm64' and platform_system=='Darwin'",
```

File: pyproject.toml [hunk 14]
```diff
@@ -25,13 +25,7 @@ requires = [
...
-
+    "numpy==1.21.6; python_version=='3.9' and platform_machine=='arm64' and platform_system=='Darwin'",
```
Comment (tupui) [inline pyproject.toml:28]:
```suggestion

```

**Comment by tupui** [comment]
@rgommers I did the rebase.

Seems like the macOS test is now ok (some timeout I think we just got a slow node seeing the runtime).

For the Azure one, still the same issue though.

File: azure-pipelines.yml [hunk 15]
```diff
@@ -175,31 +175,32 @@ stages:
             # the unusual install method. For the bug report about missing .pc
             # files: https://github.com/MacPython/openblas-libs/issues/74
             set -euo pipefail
-            docker pull i386/ubuntu:bionic
-            docker run -v $(pwd):/scipy i386/ubuntu:bionic /usr/bin/linux32 /bin/bash -c "cd scipy && \
+            docker pull i386/ubuntu:focal
+            docker run -v $(pwd):/scipy i386/ubuntu:focal /usr/bin/linux32 /bin/bash -c "cd scipy && \
+            export DEBIAN_FRONTEND=nonintercative && \
```
Comment (andyfaff) [inline azure-pipelines.yml:180]: spelling: `noninteractive`

File: azure-pipelines.yml [hunk 16]
```diff
@@ -175,31 +175,32 @@ stages:
...
             apt-get -y update && \
-            apt-get -y install curl python3.8-dev python3.8 python3-distutils pkg-config libpng-dev libjpeg8-dev libfreetype6-dev && \
+            apt-get -y install curl python3.9-dev python3.9 python3-distutils pkg-config libpng-dev libjpeg8-dev libfreetype6-dev && \
             curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && \
-            python3.8 get-pip.py && \
+            python3.9 get-pip.py && \
             pip3 --version && \
-            pip3 install setuptools==59.6.0 wheel numpy==1.19.5 cython==0.29.21 pybind11 pytest pytest-timeout pytest-xdist pytest-env pytest-cov Pillow mpmath pythran pooch && \
+            pip3 install setuptools==59.6.0 wheel numpy==1.21.6 cython==0.29.21 pybind11 pytest pytest-timeout pytest-xdist pytest-env pytest-cov Pillow mpmath pythran pooch && \
             apt-get -y install gcc-8 g++-8 gfortran-8 wget && \
```
Comment (andyfaff) [inline azure-pipelines.yml:187]: I think it'd be much easier to have:

```
apt-get -y install build-essential gfortran wget && \
```

and remove `CC=gcc-8 CXX=g++-8 F77=gfortran-8 F90=gfortran-8` on the `setup.py install` line.

File: azure-pipelines.yml [hunk 17]
```diff
@@ -175,31 +175,32 @@ stages:
...
+            target=\$(python3.9 ../scipy/tools/openblas_support.py) && \
             cp -r \$target/lib/* /usr/lib && \
             cp \$target/include/* /usr/include && \
             cd ../scipy && \
-            CC=gcc-8 CXX=g++-8 F77=gfortran-8 F90=gfortran-8 python3.8 setup.py install && \
-            python3.8 tools/openblas_support.py --check_version $(openblas_version) && \
-            python3.8 runtests.py -n --mode=full -- -n auto -s --junitxml=junit/test-results.xml --cov-config=.coveragerc --cov-report=xml --cov-report=html --durations=10 --timeout=60"
+            CC=gcc-8 CXX=g++-8 F77=gfortran-8 F90=gfortran-8 python3.9 setup.py install && \
+            python3.9 tools/openblas_support.py --check_version $(openblas_version) && \
+            python3.9 runtests.py -n --mode=full -- -n auto -s --junitxml=junit/test-results.xml --cov-config=.coveragerc --cov-report=xml --cov-report=html --durations=10 --timeout=60"
```
Comment (andyfaff) [inline azure-pipelines.yml:196]: I wonder why we chose the Linux 32 bit run (of all things) to generate the coverage reports.

File: doc/source/dev/toolchain.rst [hunk 18]
```diff
@@ -124,7 +125,7 @@ Currently, SciPy wheels are being built as follows:
  Platform          Azure Base Image [5]_     Compilers                    Comment
 ================  ========================  ===========================  ==============================
 Linux (nightly)    ``ubuntu-20.04``          GCC 6.5                      See ``azure-pipelines.yml``
-Linux (release)    ``ubuntu-18.04``          GCC 7.5                      Built in separate repo [6]_
+Linux (release)    ``ubuntu-22.04``          GCC 8                        Built in separate repo [6]_
```
Comment (andyfaff) [inline doc/source/dev/toolchain.rst:128]: this all needs to be re-written at some point, because we know do all the wheel build in `wheels.yml`, in this repo, with cibuildwheel, with more recent compilers, on a macOS-11 image, etc. Probably not something for this PR.

**Comment by andyfaff** [comment]
I've just replicated the issue with the azure pipelines job in a `i386/ubuntu:focal` docker container on my own computer.
I can get it to work with more recent build tools:

```
apt-get install -y build-essential gfortran
```

I don't know about why gcc-8 is used here, can we transfer to a more recent set of build tools? I think gcc-9 is the default on focal.

Furthermore, it may be cleaner to transfer this job to Github Actions. The current script has a whole bunch of `&& \` to squeeze the job into a single multiline string. I personally find the `azure-pipelines.yml` way of scripting quite complicated to follow.

We should be able to do something like this in GHA:
```
jobs:
  Linux_Python_38_32bit_full:
    runs-on: ubuntu-latest
    container:
      image: "i386/ubuntu:focal"
    steps:
      - run: |
        # do the test run
```

File: azure-pipelines.yml (hunk 17 above)
Comment (tupui) [reply azure-pipelines.yml:196]: Plus I think we don't use this one since we have this job `prerelease_deps_coverage_64bit_blas` (which btw I had a PR to move to GH actions #15958 but stalled)

**Comment by tupui** [comment]
Thanks for the help @andyfaff. I updated Cython and GCC. Let's see how it goes. If that passes, we will be left with the macOS job.

**Comment by tupui** [comment]
@rgommers all is running. Now the CI failure is with 2 tests in spectral
```	
FAILED ../../signal/tests/test_spectral.py::TestPeriodogram::test_nd_axis_m1
FAILED ../../signal/tests/test_spectral.py::TestPeriodogram::test_nd_axis_0

_______________________ TestPeriodogram.test_nd_axis_m1 ________________________
[gw0] linux -- Python 3.9.5 /usr/bin/python3.9
/usr/local/lib/python3.9/dist-packages/scipy-1.11.0.dev0+unknown.unknown-py3.9-linux-i686.egg/scipy/signal/tests/test_spectral.py:105: in test_nd_axis_m1
    assert_array_almost_equal_nulp(p0[np.newaxis,:], p[1,:], 60)
E   AssertionError: X and Y are not equal to 60 ULP (max is 4.10548e+18)
...
________________________ TestPeriodogram.test_nd_axis_0 ________________________
[gw0] linux -- Python 3.9.5 /usr/bin/python3.9
/usr/local/lib/python3.9/dist-packages/scipy-1.11.0.dev0+unknown.unknown-py3.9-linux-i686.egg/scipy/signal/tests/test_spectral.py:115: in test_nd_axis_0
    assert_array_almost_equal_nulp(p0, p[:,1,0])
E   AssertionError: X and Y are not equal to 1 ULP (max is 4.10548e+18)
...
```

**Comment by rgommers** [comment]
> What should we do? xfail on 32bits?

It looks like the test needs tweak. The `_nulp` assert seems to be failing on comparing `0` and `3.0...e-34`. So changing it to use a different test function with `atol=1e-33` is probably fine. Not 100% sure though without spending more time - for signal processing functions such small absolute numbers are sometimes relevant.

So how about skipping (not xfailing) the test here, and then opening a follow-up PR changing to `assert_allclose`? That way we can get this merged, and get some help from the `signal` experts on a much smaller PR.

**Comment by tupui** [comment]
@rgommers CI is green.

**Comment by tupui** [comment]
Mistake rebased push the wrong thing, hopefully I did not break anything 😒

**Comment by tupui** [comment]
Azure did not like the rebase, but seems all good otherwise.

**Comment by tupui** [comment]
Anything else to do here?

File: azure-pipelines.yml (hunk 17 above)
Comment (rgommers) [reply azure-pipelines.yml:196]: No particular reason I think, just an accident of history. Can easily be moved.

**Review by rgommers — APPROVED** [review]
This LGTM now, let's give it a go. Thanks @tupui! And thanks @andyfaff for the reviews

File: azure-pipelines.yml (hunk 17 above)
Comment (tupui) [reply azure-pipelines.yml:196]: I would do that in a follow up to not delay this one more.

**Comment by tupui** [comment]
Thanks all 😃
