### ISSUE TITLE
BUG: Scipy 1.12 does not expose scipy.histogram() and it is not listed in the breaking changes for the release

### ISSUE THREAD

**Issue by pgunn** [scipy/scipy#20113]
### Describe your issue.

Scipy 1.11.x and earlier exposed scipy.stats._stats_py._histogram() as scipy.histogram(), and with the release of 1.12.0 this was broken; it is still possible to use the private function to get that implementation as an alternative to pinning scipy at an older version for software that depends on this, but it'd be nice to get this sorted out.

### Reproducing Code Example

```python
$ python
>>> import scipy
>>> scipy.histogram

(works on 1.11.3, does not work on 1.12.0)
```

### Error message

```shell
AttributeError: Module 'scipy' has no attribute 'histogram'
```

### SciPy/NumPy/Python version and system information

```shell
1.12.0 1.26.4 sys.version_info(major=3, minor=12, micro=2, releaselevel='final', serial=0)
/home/pgunn/miniconda3/envs/scipy112/lib/python3.12/site-packages/scipy/__config__.py:154: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)
{
  "Compilers": {
    "c": {
      "name": "gcc",
      "linker": "ld.bfd",
      "version": "12.3.0",
      "commands": "/home/conda/feedstock_root/build_artifacts/scipy-split_1706041474046/_build_env/bin/x86_64-conda-linux-gnu-cc",
      "args": "-march=nocona, -mtune=haswell, -ftree-vectorize, -fPIC, -fstack-protector-strong, -fno-plt, -O2, -ffunction-sections, -pipe, -isystem, /home/pgunn/miniconda3/envs/scipy112/include, -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/scipy-split_1706041474046/work=/usr/local/src/conda/scipy-split-1.12.0, -fdebug-prefix-map=/home/pgunn/miniconda3/envs/scipy112=/usr/local/src/conda-prefix, -march=nocona, -mtune=haswell, -ftree-vectorize, -fPIC, -fstack-protector-strong, -fno-plt, -O2, -ffunction-sections, -pipe, -isystem, /home/pgunn/miniconda3/envs/scipy112/include, -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/scipy-split_1706041474046/work=/usr/local/src/conda/scipy-split-1.12.0, -fdebug-prefix-map=/home/pgunn/miniconda3/envs/scipy112=/usr/local/src/conda-prefix, -DNDEBUG, -D_FORTIFY_SOURCE=2, -O2, -isystem, /home/pgunn/miniconda3/envs/scipy112/include, -DNDEBUG, -D_FORTIFY_SOURCE=2, -O2, -isystem, /home/pgunn/miniconda3/envs/scipy112/include",
      "linker args": "-Wl,-O2, -Wl,--sort-common, -Wl,--as-needed, -Wl,-z,relro, -Wl,-z,now, -Wl,--disable-new-dtags, -Wl,--gc-sections, -Wl,--allow-shlib-undefined, -Wl,-rpath,/home/pgunn/miniconda3/envs/scipy112/lib, -Wl,-rpath-link,/home/pgunn/miniconda3/envs/scipy112/lib, -L/home/pgunn/miniconda3/envs/scipy112/lib, -Wl,-O2, -Wl,--sort-common, -Wl,--as-needed, -Wl,-z,relro, -Wl,-z,now, -Wl,--disable-new-dtags, -Wl,--gc-sections, -Wl,--allow-shlib-undefined, -Wl,-rpath,/home/pgunn/miniconda3/envs/scipy112/lib, -Wl,-rpath-link,/home/pgunn/miniconda3/envs/scipy112/lib, -L/home/pgunn/miniconda3/envs/scipy112/lib, -march=nocona, -mtune=haswell, -ftree-vectorize, -fPIC, -fstack-protector-strong, -fno-plt, -O2, -ffunction-sections, -pipe, -isystem, /home/pgunn/miniconda3/envs/scipy112/include, -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/scipy-split_1706041474046/work=/usr/local/src/conda/scipy-split-1.12.0, -fdebug-prefix-map=/home/pgunn/miniconda3/envs/scipy112=/usr/local/src/conda-prefix, -march=nocona, -mtune=haswell, -ftree-vectorize, -fPIC, -fstack-protector-strong, -fno-plt, -O2, -ffunction-sections, -pipe, -isystem, /home/pgunn/miniconda3/envs/scipy112/include, -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/scipy-split_1706041474046/work=/usr/local/src/conda/scipy-split-1.12.0, -fdebug-prefix-map=/home/pgunn/miniconda3/envs/scipy112=/usr/local/src/conda-prefix, -DNDEBUG, -D_FORTIFY_SOURCE=2, -O2, -isystem, /home/pgunn/miniconda3/envs/scipy112/include, -DNDEBUG, -D_FORTIFY_SOURCE=2, -O2, -isystem, /home/pgunn/miniconda3/envs/scipy112/include"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.7",
      "commands": "cython"
    },
    "c++": {
      "name": "gcc",
      "linker": "ld.bfd",
      "version": "12.3.0",
      "commands": "/home/conda/feedstock_root/build_artifacts/scipy-split_1706041474046/_build_env/bin/x86_64-conda-linux-gnu-c++",
      "args": "-fvisibility-inlines-hidden, -fmessage-length=0, -march=nocona, -mtune=haswell, -ftree-vectorize, -fPIC, -fstack-protector-strong, -fno-plt, -O2, -ffunction-sections, -pipe, -isystem, /home/pgunn/miniconda3/envs/scipy112/include, -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/scipy-split_1706041474046/work=/usr/local/src/conda/scipy-split-1.12.0, -fdebug-prefix-map=/home/pgunn/miniconda3/envs/scipy112=/usr/local/src/conda-prefix, -fvisibility-inlines-hidden, -fmessage-length=0, -march=nocona, -mtune=haswell, -ftree-vectorize, -fPIC, -fstack-protector-strong, -fno-plt, -O2, -ffunction-sections, -pipe, -isystem, /home/pgunn/miniconda3/envs/scipy112/include, -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/scipy-split_1706041474046/work=/usr/local/src/conda/scipy-split-1.12.0, -fdebug-prefix-map=/home/pgunn/miniconda3/envs/scipy112=/usr/local/src/conda-prefix, -DNDEBUG, -D_FORTIFY_SOURCE=2, -O2, -isystem, /home/pgunn/miniconda3/envs/scipy112/include, -DNDEBUG, -D_FORTIFY_SOURCE=2, -O2, -isystem, /home/pgunn/miniconda3/envs/scipy112/include",
      "linker args": "-Wl,-O2, -Wl,--sort-common, -Wl,--as-needed, -Wl,-z,relro, -Wl,-z,now, -Wl,--disable-new-dtags, -Wl,--gc-sections, -Wl,--allow-shlib-undefined, -Wl,-rpath,/home/pgunn/miniconda3/envs/scipy112/lib, -Wl,-rpath-link,/home/pgunn/miniconda3/envs/scipy112/lib, -L/home/pgunn/miniconda3/envs/scipy112/lib, -Wl,-O2, -Wl,--sort-common, -Wl,--as-needed, -Wl,-z,relro, -Wl,-z,now, -Wl,--disable-new-dtags, -Wl,--gc-sections, -Wl,--allow-shlib-undefined, -Wl,-rpath,/home/pgunn/miniconda3/envs/scipy112/lib, -Wl,-rpath-link,/home/pgunn/miniconda3/envs/scipy112/lib, -L/home/pgunn/miniconda3/envs/scipy112/lib, -fvisibility-inlines-hidden, -fmessage-length=0, -march=nocona, -mtune=haswell, -ftree-vectorize, -fPIC, -fstack-protector-strong, -fno-plt, -O2, -ffunction-sections, -pipe, -isystem, /home/pgunn/miniconda3/envs/scipy112/include, -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/scipy-split_1706041474046/work=/usr/local/src/conda/scipy-split-1.12.0, -fdebug-prefix-map=/home/pgunn/miniconda3/envs/scipy112=/usr/local/src/conda-prefix, -fvisibility-inlines-hidden, -fmessage-length=0, -march=nocona, -mtune=haswell, -ftree-vectorize, -fPIC, -fstack-protector-strong, -fno-plt, -O2, -ffunction-sections, -pipe, -isystem, /home/pgunn/miniconda3/envs/scipy112/include, -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/scipy-split_1706041474046/work=/usr/local/src/conda/scipy-split-1.12.0, -fdebug-prefix-map=/home/pgunn/miniconda3/envs/scipy112=/usr/local/src/conda-prefix, -DNDEBUG, -D_FORTIFY_SOURCE=2, -O2, -isystem, /home/pgunn/miniconda3/envs/scipy112/include, -DNDEBUG, -D_FORTIFY_SOURCE=2, -O2, -isystem, /home/pgunn/miniconda3/envs/scipy112/include"
    },
    "fortran": {
      "name": "gcc",
      "linker": "ld.bfd",
      "version": "12.3.0",
      "commands": "/home/conda/feedstock_root/build_artifacts/scipy-split_1706041474046/_build_env/bin/x86_64-conda-linux-gnu-gfortran",
      "args": "-march=nocona, -mtune=haswell, -ftree-vectorize, -fPIC, -fstack-protector-strong, -fno-plt, -O2, -ffunction-sections, -pipe, -isystem, /home/pgunn/miniconda3/envs/scipy112/include, -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/scipy-split_1706041474046/work=/usr/local/src/conda/scipy-split-1.12.0, -fdebug-prefix-map=/home/pgunn/miniconda3/envs/scipy112=/usr/local/src/conda-prefix",
      "linker args": "-Wl,-O2, -Wl,--sort-common, -Wl,--as-needed, -Wl,-z,relro, -Wl,-z,now, -Wl,--disable-new-dtags, -Wl,--gc-sections, -Wl,--allow-shlib-undefined, -Wl,-rpath,/home/pgunn/miniconda3/envs/scipy112/lib, -Wl,-rpath-link,/home/pgunn/miniconda3/envs/scipy112/lib, -L/home/pgunn/miniconda3/envs/scipy112/lib, -Wl,-O2, -Wl,--sort-common, -Wl,--as-needed, -Wl,-z,relro, -Wl,-z,now, -Wl,--disable-new-dtags, -Wl,--gc-sections, -Wl,--allow-shlib-undefined, -Wl,-rpath,/home/pgunn/miniconda3/envs/scipy112/lib, -Wl,-rpath-link,/home/pgunn/miniconda3/envs/scipy112/lib, -L/home/pgunn/miniconda3/envs/scipy112/lib, -march=nocona, -mtune=haswell, -ftree-vectorize, -fPIC, -fstack-protector-strong, -fno-plt, -O2, -ffunction-sections, -pipe, -isystem, /home/pgunn/miniconda3/envs/scipy112/include, -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/scipy-split_1706041474046/work=/usr/local/src/conda/scipy-split-1.12.0, -fdebug-prefix-map=/home/pgunn/miniconda3/envs/scipy112=/usr/local/src/conda-prefix"
    },
    "pythran": {
      "version": "0.15.0",
      "include directory": "../../_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.12/site-packages/pythran"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "linux"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "linux"
    },
    "cross-compiled": false
  },
  "Build Dependencies": {
    "blas": {
      "name": "blas",
      "found": true,
      "version": "3.9.0",
      "detection method": "pkgconfig",
      "include directory": "/home/pgunn/miniconda3/envs/scipy112/include",
      "lib directory": "/home/pgunn/miniconda3/envs/scipy112/lib",
      "openblas configuration": "unknown",
      "pc file directory": "/home/pgunn/miniconda3/envs/scipy112/lib/pkgconfig"
    },
    "lapack": {
      "name": "lapack",
      "found": true,
      "version": "3.9.0",
      "detection method": "pkgconfig",
      "include directory": "/home/pgunn/miniconda3/envs/scipy112/include",
      "lib directory": "/home/pgunn/miniconda3/envs/scipy112/lib",
      "openblas configuration": "unknown",
      "pc file directory": "/home/pgunn/miniconda3/envs/scipy112/lib/pkgconfig"
    },
    "pybind11": {
      "name": "pybind11",
      "version": "2.11.1",
      "detection method": "pkgconfig",
      "include directory": "/home/pgunn/miniconda3/envs/scipy112/include"
    }
  },
  "Python Information": {
    "path": "/home/pgunn/miniconda3/envs/scipy112/bin/python",
    "version": "3.12"
  }
}
>>>
```

**Comment by lucascolley** [comment]
`scipy.histogram` exposed `numpy.histogram` before 1.12 - this was removed after a long deprecation in gh-19067. Please just use `numpy.histogram` instead!

We are aware that this missed the release notes, this is currently tracked in gh-19974.

**Comment by rkern** [comment]
I don't think that we ever did expose that particular function as `scipy.histogram()`. We did import `np.histogram` and expose it as `scipy.histogram` (along with everything else in the `numpy` namespace), but we've been deprecating those usages for a long time. For example, on `scipy 1.8.0`, an old installation that I have conveniently on hand, `scipy.histogram` is the same as `np.histogram` (albeit wrapped to issue a deprecation message). I'm not seeing any version in our history where `scipy/__init__.py` exposes anything but `np.histogram` as `scipy.histogram`.

You can probably safely update your code to use `np.histogram()`. If you really want the widened default range provided by `scipy.stats._stats_py._histogram`, I'd probably recommend just vendoring that into your codebase. I don't think we want to support it as part of the public API. It certainly will not return as `scipy.histogram()`.

**Comment by pgunn** [comment]
Ah, my bad, I mixed up some much older environments I had with the 1.11.3 environment I have. Still would've been nice to have had this listed as a breaking change, but oh well. The route forward for our code is pretty clear. Thanks for the fast response.
