### ISSUE TITLE
BUG: scipy.optimize imports numpy testing tools which overwrites logging.root

### ISSUE THREAD

**Issue by AlexRiina** [scipy/scipy#18044]
### Describe your issue.

https://github.com/scipy/scipy/blob/main/scipy/optimize/_constraints.py#L8 imports from numpy.testing which triggers numpy to overwrite the root logger (`logging.root`). Their logger behaves slightly differently from logging.RootLogger and, for example, does not allow a `exc_info` parameter. Because of this, `logging.warning("hi", exc_info=True)` will pass before scipy.optimize is imported, but will fail after.

In numpy, I believe the relevant line is https://github.com/numpy/numpy/blob/main/numpy/distutils/log.py#L46

### Reproducing Code Example

```python
import logging
logging.root  # <RootLogger root (WARNING)>
logging.warning("hi", exc_info=True)

import scipy.optimize
logging.root  # <Log root (WARNING)> from numpy.distutils.log
logging.warning("hi", exc_info=True)
# TypeError: _log() got an unexpected keyword argument 'exc_info'
```

### Error message

```shell
TypeError                                 Traceback (most recent call last)
<ipython-input-2-53a8aebdb3aa> in <module>
      1 import scipy.optimize
      2 logging.root  # <Log root (WARNING)> from numpy.distutils.log
----> 3 logging.warning("hi", exc_info=True)

~/.pyenv/versions/3.8.16/lib/python3.8/logging/__init__.py in warning(msg, *args, **kwargs)
   2065     if len(root.handlers) == 0:
   2066         basicConfig()
-> 2067     root.warning(msg, *args, **kwargs)
   2068 
   2069 def warn(msg, *args, **kwargs):

~/.pyenv/versions/3.8.16/lib/python3.8/logging/__init__.py in warning(self, msg, *args, **kwargs)
   1456         """
   1457         if self.isEnabledFor(WARNING):
-> 1458             self._log(WARNING, msg, args, **kwargs)
   1459 
   1460     def warn(self, msg, *args, **kwargs):

TypeError: _log() got an unexpected keyword argument 'exc_info'
```

### SciPy/NumPy/Python version information

(I believe this affects the current main branch of scipy with the current main branch of numpy, but for completeness of this report)
scipy==1.7.3
numpy==1.22.0
python 3.8.16

**Comment by AlexRiina** [comment]
Hm, this may actually be an issue with setuptools actually. After recreating my virtualenvironment, I noticed that I was no longer able to reproduce the issue but noticed that the distutils.log was actually coming from setuptools. After a bit more testing, I can generate the error on setuptools==67.4.0 but everything seems to work on 65.5.0.

Happy to close this issue and reopen with either setuptools or numpy. I'm not sure it's a good idea to import from `numpy.testing` though given the doc string for [numpy/testing/__init__.py](https://github.com/numpy/numpy/blob/main/numpy/testing/__init__.py) included below.

> Common test support for all numpy test scripts.
> This single module should provide all the common functionality for numpy tests
in a single location, so that test scripts can just import it and work right
away.

**Comment by tupui** [comment]
Thanks for following up!

Yeah I mean this line is 4 years old. So seems like it's not breaking that people often if we did not change that yet. Let's close for now.
