### ISSUE TITLE
BUG: find_peaks_cwt `wavelet` parameter needs more parameters than described in docs

### ISSUE THREAD

**Issue by EfremBraun** [scipy/scipy#15094]
### Describe your issue.

Per the docs:
```
wavelet: callable, optional
Should take two parameters and return a 1-D array to convolve with vector. The first parameter determines the number of points of the returned wavelet array, the second parameter is the scale (width) of the wavelet. Should be normalized and symmetric. Default is the ricker wavelet.
```

However, when I put in my own wavelet, it also needs a `window_size` parameter. The shim introduced in fd966a4 where the `window_size`parameter is used just for the ricker wavelet may need to be done for other wavelets too (or maybe there's a better way to fix this).

Maybe related to #12739.

### Reproducing Code Example

```python
import numpy as np
from scipy import signal
xs = np.arange(0, np.pi, 0.05)
data = np.sin(xs)
peakind = signal.find_peaks_cwt(data, np.arange(1,10), wavelet=lambda points, a: -1 * signal.wavelets.ricker(points, a))
#peakind = signal.find_peaks_cwt(data, np.arange(1,10), wavelet=lambda points, a, window_size: -1 * signal.wavelets.ricker(points, a)) #this is the workaround needed
```

### Error message

```shell
Traceback (most recent call last):
  File "example.py", line 5, in <module>
    peakind = signal.find_peaks_cwt(data, np.arange(1,10), wavelet=lambda points, a: -1 * signal.wavelets.ricker(points, a))
  File "/Users/edbraun/opt/anaconda3/lib/python3.8/site-packages/scipy/signal/_peak_finding.py", line 1293, in find_peaks_cwt
    cwt_dat = cwt(vector, wavelet, widths, window_size=window_size)
  File "/Users/edbraun/opt/anaconda3/lib/python3.8/site-packages/scipy/signal/wavelets.py", line 463, in cwt
    if np.asarray(wavelet(1, widths[0], **kwargs)).dtype.char in 'FDG':
TypeError: <lambda>() got an unexpected keyword argument 'window_size'
```

### SciPy/NumPy/Python version information

1.7.1 1.21.4 sys.version_info(major=3, minor=8, micro=5, releaselevel='final', serial=0)
