### PR TITLE
remove inspect.getargspec and test python 3.5 on Travis CI

### PR DESCRIPTION
**Pull request by ev-br**
Let's see how we fare with the latest and greatest :-).

### CODE REVIEW

**Comment by ev-br** [comment]
Doing good, it seems: There seems ot be an incredible amount of noise from deprecating `inspect.getargspec` (https://github.com/scipy/scipy/pull/4928), but that's pretty much it.

**Comment by ev-br** [comment]
OK, a naive attempt at replacing getargspec fails miserably. Will look into this.

**Comment by ev-br** [comment]
Travis is all green, yay!
(stats/distributions took a bit of a back-and-forth)

I did not touch `doc/source/scipyoptdoc.py` or `_lib/decorators.py`, and the latter does produce some noise under python 3.5. Maybe the right thing is to vendor the current version of https://github.com/micheles/decorator but this can be done in a separate PR.

If merged, this supersedes and closes gh-4928

**Comment by rgommers** [comment]
This PR looks very good, so I have closed gh-4928.

**Comment by rgommers** [comment]
Vendoring the latest ``decorator`` and using the function added here in ``scipyoptdoc.py`` seems like the way to go. I agree that that can be done in a separate PR though, so merging this. Thanks @ev-br!

**Comment by ev-br** [comment]
Maybe it's worth to backport this one, so that 0.16.1 is less noisy under python 3.5. But it's not a big deal in any case. (Anyway, nice to see you back online Ralf :-)).

**Comment by rgommers** [comment]
thanks, it's good to be back:)

**Comment by rgommers** [comment]
Agreed. I'll do the backporting in one go for all the ``backport-candidate`` labeled PRs.

**Comment by adryr83** [comment]
Hi, please can you help me? I'm learning Python and I installed last version of nltk (3.2.1), but with Python 3.5.2 it doesn't work.
When I try to launch a program (Chatterbot 0.4.6) that uses nltk, a message of Deprecated Warning (nltk/decorators.python - Line 59, inspect.getargspec) compares.

Please help me. I don't know how to solve. 
I installed nltk with upgrade (pip...).
I used os x el capitan.

Thanks a lot!

**Comment by pv** [comment]
@adryr83: this is the wrong place to ask that question. If the problem is with nltk, ask nltk, if with chatterbot, ask them.

**Comment by adryr83** [comment]
Sorry. I considered my problem similar to this ticket because the
Deprecated Warning is for inspect.getargspec in ntlk/decorators.py

I installed last version of nltk but I don't solve my problem. I already
opened a ticket for ntlk and Chatterbot, but I didn't have answer so I
searched another ticket similar to my problem.
Thanks

Il 03/Set/2016 12:10, "Pauli Virtanen" <notifications@github.com> ha
scritto:

**Comment by sunset001** [comment]
Trying to run my script that invokes Pandas and keep getting decorator.py (line 55: inspect.getargspec(f) ) error "module  object has no attribute "getargspec".  I have Python 2.7.14 with the latest version of scipy and numpy.
Please, advise.

**Comment by rgommers** [comment]
@sunset001 if your issue is in pandas, please open an issue on the pandas issue tracker rather than here. And include a reproducible example of what is failing for you, otherwise it's very hard to help you.

**Comment by sunset001** [comment]
Thanks Ralf for your reply.

It is not Pandas issue -  it is issue with decorator.py in scipy (as there are cross-dependencies between all site_packages, i.e. pandas, numpy, scipy, scikit, etc).

For this simple code as

 

import pandas as pd

 

doc = []

 

with open("dates.txt") as f:

     for line in f:

         doc.append(line)

 

df = pd.Series(doc)

df.head(10)

 

I’m getting traceback: Traceback (most recent call last):

  File "test1.py", line 1, in <module>

    import pandas as pd

  File "c:\python27\lib\site-packages\pandas\__init__.py", line 23, in <module>

    from pandas.compat.numpy import *

  File "c:\python27\lib\site-packages\pandas\compat\__init__.py", line 38, in <m

odule>

    import inspect

  File "C:\Python27\Lib\inspect.py", line 39, in <module>

    import tokenize

  File "C:\Python27\Lib\tokenize.py", line 31, in <module>

    from token import *

  File "C:\Python27\Scripts\token.py", line 1, in <module>

    from nltk.tokenize import regexp_tokenize

  File "c:\python27\lib\site-packages\nltk\__init__.py", line 114, in <module>

    from nltk.collocations import *

  File "c:\python27\lib\site-packages\nltk\collocations.py", line 39, in <module

> 

    from nltk.metrics import ContingencyMeasures, BigramAssocMeasures, TrigramAs

socMeasures

  File "c:\python27\lib\site-packages\nltk\metrics\__init__.py", line 16, in <mo

dule>

    from nltk.metrics.scores import          (accuracy, precision, recall, f_mea

sure,

  File "c:\python27\lib\site-packages\nltk\metrics\scores.py", line 18, in <modu

le>

    from scipy.stats.stats import betai

  File "c:\python27\lib\site-packages\scipy\stats\__init__.py", line 348, in <mo

dule>

    from .stats import *

  File "c:\python27\lib\site-packages\scipy\stats\stats.py", line 175, in <modul

e>

    import scipy.special as special

  File "c:\python27\lib\site-packages\scipy\special\__init__.py", line 648, in <

module>

    from ._ellip_harm import ellip_harm, ellip_harm_2, ellip_normal

  File "c:\python27\lib\site-packages\scipy\special\_ellip_harm.py", line 7, in

<module>

    from ._ellip_harm_2 import _ellipsoid, _ellipsoid_norm

  File "scipy\special\_ellip_harm_2.pyx", line 5, in init scipy.special._ellip_h

arm_2 (scipy\special\_ellip_harm_2.c:8501)

  File "c:\python27\lib\site-packages\scipy\integrate\__init__.py", line 59, in

<module>

    from ._bvp import solve_bvp

  File "c:\python27\lib\site-packages\scipy\integrate\_bvp.py", line 10, in <mod

ule>

    from scipy.sparse.linalg import splu

  File "c:\python27\lib\site-packages\scipy\sparse\linalg\__init__.py", line 113

, in <module>

    from .isolve import *

  File "c:\python27\lib\site-packages\scipy\sparse\linalg\isolve\__init__.py", l

ine 6, in <module>

    from .iterative import *

  File "c:\python27\lib\site-packages\scipy\sparse\linalg\isolve\iterative.py",

line 10, in <module>

    from scipy._lib.decorator import decorator

  File "c:\python27\lib\site-packages\scipy\_lib\decorator.py", line 51, in <mod

ule>

    class getfullargspec(object):

  File "c:\python27\lib\site-packages\scipy\_lib\decorator.py", line 65, in getf

ullargspec

    getargspec = inspect.getargspec

AttributeError: 'module' object has no attribute 'getargspec'

 

Will appreciate your help with this issue. (I heard that deprecating inspect.getargspec in  numpy made some problem in other packages). 

 

 

Regards

Inna

**Comment by rgommers** [comment]
@sunset001 there's something really weird about your Python 2.7 install. The cause is:

    import inspect
    inspect.getargspec

That should work on Python 2.7. Try to reproduce by just typing those 2 lines in the Python interpreter. It's unrelated to Scipy.

**Comment by sunset001** [comment]
It is related.

Please, read entire thread about inspect.getargspec being deprecated in numpy.
 
Thanks

**Comment by anagouveia1** [comment]
How did I end up here?

**Comment by rgommers** [comment]
@anagouveia1 no idea. There's an "Unsubscribe" button in the right sidebar. Or maybe you're watching the whole scipy repository?

**Comment by rgommers** [comment]
@sunset001 please don't ask me to read more when I've explained to you what your problem is. I've made a suggestion to help you debug, please try it.

If your problem really was in scipy and triggered by a simple ``pd.head(10)``, then hundreds of people would be complaining by now.

**Comment by sunset001** [comment]
Same piece of code works fine in Python shell...Issue is when it runs as a script, so, most likely, it is not installation problem...ThanksSent from XFINITY Connect Mobile App------ Original Message ------From: Ralf GommersTo: scipy/scipyCc: sunset001, MentionSent: September 11, 2017 at 1:15 PMSubject: Re: [scipy/scipy] remove inspect.getargspec and test python 3.5 on Travis CI (#5248)@sunset001 there's something really weird about your Python 2.7 install. The cause is:import inspectinspect.getargspecThat should work on Python 2.7. Try to reproduce by just typing those 2 lines in the Python interpreter. It's unrelated to Scipy.— You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.￼

**Comment by WarrenWeckesser** [comment]
@sunset001 The traceback that you posted earlier shows something strange going on:

```
File "c:\python27\lib\site-packages\pandas\compat\__init__.py", line 38, in <module>
  import inspect
File "C:\Python27\Lib\inspect.py", line 39, in <module>
  import tokenize
File "C:\Python27\Lib\tokenize.py", line 31, in <module>
  from token import *
File "C:\Python27\Scripts\token.py", line 1, in <module>
  from nltk.tokenize import regexp_tokenize 
```
So Pandas does `import inspect`;  the standard library `inspect` does `import tokenize`; the standard library `tokenize` does `from token import *`; but then we see those last two lines:

```
File "C:\Python27\Scripts\token.py", line 1, in <module>
  from nltk.tokenize import regexp_tokenize 
```

Why is `from token import *`, executing in `tokenize.py` in the standard library, triggering an import from `"C:\Python27\Scripts\token.py"`, which then imports from `nltk`?  I don't use Windows, so I can't really help debug this.  You might look into where the file `token.py` in `"C:\Python27\Scripts"` comes from.  If the directory `"C:\Python27\Scripts"` is in the Python path on Windows (is it? I don't know), and if you or some other package put that file in the `Scripts` directory, that would cause a problem.

**Comment by sunset001** [comment]
Thanks Warren !

I renamed my project file “token.py” and error is gone !

 

Regards

**Comment by WarrenWeckesser** [comment]
Great!
