### PR TITLE
BLD: Fix error message for f2py generation fail

### PR DESCRIPTION
**Pull request by bnavigator**
#### What does this implement/fix?

I am currently packaging the openSUSE rpm for 1.13 and see a build failure for the HPC build with numpy 2.0.0rc1. I still have to investigate why the generation fails, but the current error message is not helpful:

```python
[   45s]   [177/1475] Generating scipy/linalg/fblas_module with a custom command
[   45s]   FAILED: scipy/linalg/_fblasmodule.c
[   45s]   /usr/bin/python3.11 /home/abuild/rpmbuild/BUILD/scipy-1.13.0/tools/generate_f2pymod.py ../scipy/linalg/fblas.pyf.src -o scipy/linalg
[   45s]   Traceback (most recent call last):
[   45s]     File "/home/abuild/rpmbuild/BUILD/scipy-1.13.0/tools/generate_f2pymod.py", line 299, in <module>
[   45s]       main()
[   45s]     File "/home/abuild/rpmbuild/BUILD/scipy-1.13.0/tools/generate_f2pymod.py", line 293, in main
[   45s]       raise RuntimeError(f"Writing {args.outfile} with f2py failed!\n"
[   45s]                                     ^^^^^^^^^^^^
[   45s]   AttributeError: 'Namespace' object has no attribute 'outfile'
[   45s]   [178/1475] Generating scipy/linalg/flapack_module with a custom command
[   45s]   FAILED: scipy/linalg/_flapackmodule.c
[   45s]   /usr/bin/python3.11 /home/abuild/rpmbuild/BUILD/scipy-1.13.0/tools/generate_f2pymod.py ../scipy/linalg/flapack.pyf.src -o scipy/linalg
[   45s]   Traceback (most recent call last):
[   45s]     File "/home/abuild/rpmbuild/BUILD/scipy-1.13.0/tools/generate_f2pymod.py", line 299, in <module>
[   45s]       main()
[   45s]     File "/home/abuild/rpmbuild/BUILD/scipy-1.13.0/tools/generate_f2pymod.py", line 293, in main
[   45s]       raise RuntimeError(f"Writing {args.outfile} with f2py failed!\n"
[   45s]                                     ^^^^^^^^^^^^
[   45s]   AttributeError: 'Namespace' object has no attribute 'outfile'
[   46s]   [179/1475] Generating 'scipy/special/cython_special.cpython-310-x86_64-linux-gnu.so.p/cython_special.c'
[   47s]   [180/1475] Compiling C++ object scipy/special/cython_special.cpython-310-x86_64-linux-gnu.so.p/specfun_wrappers.cpp.o
[   47s]   [181/1475] Linking target scipy/special/_test_internal.cpython-310-x86_64-linux-gnu.so
[   47s]   [182/1475] Linking target scipy/special/_ufuncs.cpython-310-x86_64-linux-gnu.so
[   47s]   ninja: build stopped: subcommand failed.
[   47s]   error: subprocess-exited-with-error
```

This PR fixes the error message with the missing attribute.

### CODE REVIEW

**Comment by rgommers** [comment]
The failures with numpy's `main` branch in one CI job are unrelated:
```
FAILED scipy/optimize/tests/test__root.py::TestRoot::test_tol_parameter - UserWarning: LowRankMatrix is scipy-internal code, `copy` should only be None but was True (not handled)
FAILED scipy/linalg/tests/test_decomp.py::TestOverwrite::test_eig_banded - AssertionError: 
Arrays are not equal
call modified inputs [<class 'numpy.complex64'>, <class 'scipy.linalg._testutils._FakeMatrix2'>]
Mismatched elements: 1 / 6 (16.7%)
Max absolute difference among violations: 0.6253038
Max relative difference among violations: 2.
 ACTUAL: array([[ 0.471435+0.j, -1.190976+0.j],
       [ 1.432707+0.j,  0.312652+0.j],
       [-0.720589+0.j,  0.887163+0.j]], dtype=complex64)
 DESIRED: array([[ 0.471435+0.j, -1.190976+0.j],
       [ 1.432707+0.j, -0.312652+0.j],
       [-0.720589+0.j,  0.887163+0.j]], dtype=complex64)
```

**Review by rgommers — APPROVED** [review]
Thanks @bnavigator, LGTM. I gave it another slight tweak to say "Processing" rather than "Writing" the input file to `f2py`.
