### ISSUE TITLE
BUG: Build fails on latest commit

### ISSUE THREAD

**Issue by Pranavchiku** [scipy/scipy#19132]
### Describe your issue.

I am trying to build SciPy, it worked well, now it throws the following error when I try to build.

### Reproducing Code Example

```
git clone https://github.com/scipy/scipy
cd scipy
git checkout 41c61b2de9a2dbef6705f961fe6836f1b5916d31
mamba env create -f environment.yml --force
conda activate scipy-dev
git submodule update --init
python dev.py build
```

### Error message

```console
% python dev.py build
💻  meson setup /Users/pranavchiku/repos/scipy/build --prefix /Users/pranavchiku/repos/scipy/build-install
The Meson build system
Version: 1.2.1
Source dir: /Users/pranavchiku/repos/scipy
Build dir: /Users/pranavchiku/repos/scipy/build
Build type: native build
Project name: SciPy
Project version: 1.12.0.dev0
C compiler for the host machine: arm64-apple-darwin20.0.0-clang (clang 15.0.7 "clang version 15.0.7")
C linker for the host machine: arm64-apple-darwin20.0.0-clang ld64 609
C++ compiler for the host machine: arm64-apple-darwin20.0.0-clang++ (clang 15.0.7 "clang version 15.0.7")
C++ linker for the host machine: arm64-apple-darwin20.0.0-clang++ ld64 609
Cython compiler for the host machine: cython (cython 3.0.1)
Host machine cpu family: aarch64
Host machine cpu: aarch64
Program python3 found: YES (/Users/pranavchiku/mambaforge/envs/scipy-dev/bin/python3.11)
Found pkg-config: /Users/pranavchiku/mambaforge/envs/scipy-dev/bin/pkg-config (0.29.2)
Run-time dependency python found: YES 3.11
Program cython found: YES (/Users/pranavchiku/mambaforge/envs/scipy-dev/bin/cython)
Compiler for C supports arguments -Wno-unused-but-set-variable: YES 
Compiler for C supports arguments -Wno-unused-function: YES 
Compiler for C supports arguments -Wno-conversion: YES 
Compiler for C supports arguments -Wno-misleading-indentation: YES 
Library m found: YES
Fortran compiler for the host machine: /Users/pranavchiku/mambaforge/envs/scipy-dev/bin/arm64-apple-darwin20.0.0-gfortran (gcc 12.3.0 "GNU Fortran (GCC) 12.3.0")
Fortran linker for the host machine: /Users/pranavchiku/mambaforge/envs/scipy-dev/bin/arm64-apple-darwin20.0.0-gfortran ld64 609
Compiler for Fortran supports arguments -Wno-conversion: YES 
Checking if "-Wl,--version-script" : links: NO 
Program pythran found: YES (/Users/pranavchiku/mambaforge/envs/scipy-dev/bin/pythran)
Did not find CMake 'cmake'
Found CMake: NO
Run-time dependency xsimd found: NO (tried pkgconfig, framework and cmake)
Run-time dependency threads found: YES
Library npymath found: YES
Library npyrandom found: YES
Run-time dependency pybind11 found: YES 2.11.1
Run-time dependency openblas found: YES 0.3.23
Dependency openblas found: YES 0.3.23 (cached)
Compiler for C supports arguments -Wno-maybe-uninitialized: NO 
Compiler for C supports arguments -Wno-discarded-qualifiers: NO 
Compiler for C supports arguments -Wno-empty-body: YES 
Compiler for C supports arguments -Wno-implicit-function-declaration: YES 
Compiler for C supports arguments -Wno-parentheses: YES 
Compiler for C supports arguments -Wno-switch: YES 
Compiler for C supports arguments -Wno-unused-label: YES 
Compiler for C supports arguments -Wno-unused-variable: YES 
Compiler for C supports arguments -Wno-incompatible-pointer-types: YES 
Compiler for C++ supports arguments -Wno-cpp: YES 
Compiler for C++ supports arguments -Wno-deprecated-declarations: YES 
Compiler for C++ supports arguments -Wno-class-memaccess: NO 
Compiler for C++ supports arguments -Wno-format-truncation: NO 
Compiler for C++ supports arguments -Wno-non-virtual-dtor: YES 
Compiler for C++ supports arguments -Wno-sign-compare: YES 
Compiler for C++ supports arguments -Wno-switch: YES 
Compiler for C++ supports arguments -Wno-terminate: NO 
Compiler for C++ supports arguments -Wno-unused-but-set-variable: YES 
Compiler for C++ supports arguments -Wno-unused-function: YES 
Compiler for C++ supports arguments -Wno-unused-local-typedefs: YES 
Compiler for C++ supports arguments -Wno-unused-variable: YES 
Compiler for C++ supports arguments -Wno-int-in-bool-context: YES 
Compiler for Fortran supports arguments -Wno-argument-mismatch: YES 
Compiler for Fortran supports arguments -Wno-conversion: YES (cached)
Compiler for Fortran supports arguments -Wno-intrinsic-shadow: YES 
Compiler for Fortran supports arguments -Wno-maybe-uninitialized: YES 
Compiler for Fortran supports arguments -Wno-surprising: YES 
Compiler for Fortran supports arguments -Wno-uninitialized: YES 
Compiler for Fortran supports arguments -Wno-unused-dummy-argument: YES 
Compiler for Fortran supports arguments -Wno-unused-label: YES 
Compiler for Fortran supports arguments -Wno-unused-variable: YES 
Compiler for Fortran supports arguments -Wno-tabs: YES 
Compiler for Fortran supports arguments -Wno-argument-mismatch: YES (cached)
Compiler for Fortran supports arguments -Wno-conversion: YES (cached)
Compiler for Fortran supports arguments -Wno-maybe-uninitialized: YES (cached)
Compiler for Fortran supports arguments -Wno-unused-dummy-argument: YES (cached)
Compiler for Fortran supports arguments -Wno-unused-label: YES (cached)
Compiler for Fortran supports arguments -Wno-unused-variable: YES (cached)
Compiler for Fortran supports arguments -Wno-tabs: YES (cached)
Checking if "Check atomic builtins without -latomic" : links: YES 
Configuring __config__.py using configuration
Checking for function "open_memstream" : YES 
Configuring messagestream_config.h using configuration
Compiler for Fortran supports arguments -w: YES 
Checking for size of "void*" : 8 
Compiler for C supports arguments -Wno-unused-variable: YES (cached)
Compiler for C supports arguments -Wno-parentheses: YES (cached)
Compiler for C supports arguments -Wno-unused-label: YES (cached)
Compiler for C supports arguments -Wno-implicit-function-declaration: YES (cached)
Compiler for C supports arguments -Wno-switch: YES (cached)
Compiler for Fortran supports arguments -w: YES (cached)
Checking for size of "void*" : 8 (cached)
Build targets in project: 244

SciPy 1.12.0.dev0

  User defined options
    prefix: /Users/pranavchiku/repos/scipy/build-install

Found ninja-1.11.1 at /Users/pranavchiku/mambaforge/envs/scipy-dev/bin/ninja
Meson build setup OK
💻  ninja -C /Users/pranavchiku/repos/scipy/build -j8
ninja: Entering directory `/Users/pranavchiku/repos/scipy/build'
[12/1588] Linking target scipy/_lib/_fpumode.cpython-311-darwin.so
ld: warning: -pie being ignored. It is only used when linking a main executable
[13/1588] Linking target scipy/_lib/_test_ccallback.cpython-311-darwin.so
ld: warning: -pie being ignored. It is only used when linking a main executable
[52/1588] Compiling C object scipy/special/libcephes.a.p/cephes_airy.c.o
../scipy/special/cephes/airy.c:256:5: warning: a function definition without a prototype is deprecated in all versions of C and is not supported in C2x [-Wdeprecated-non-prototype]
int airy(x, ai, aip, bi, bip)
    ^
.....
WARNING: Overriding pythran description with argspec information for: numpy.random.standard_normal
WARNING: Overriding pythran description with argspec information for: numpy.random.uniform
WARNING: Overriding pythran description with argspec information for: numpy.random.weibull
[1202/1588] Compiling C object scipy/signal/_upfirdn_apply.cpython-311-darwin.so.p/meson-generated__upfirdn_apply.c.o
FAILED: scipy/signal/_upfirdn_apply.cpython-311-darwin.so.p/meson-generated__upfirdn_apply.c.o 
arm64-apple-darwin20.0.0-clang -Iscipy/signal/_upfirdn_apply.cpython-311-darwin.so.p -Iscipy/signal -I../scipy/signal -I../../../mambaforge/envs/scipy-dev/lib/python3.11/site-packages/numpy/core/include -I/Users/pranavchiku/mambaforge/envs/scipy-dev/include/python3.11 -fvisibility=hidden -fcolor-diagnostics -Wall -Winvalid-pch -std=c99 -O2 -g -Wno-unused-but-set-variable -Wno-unused-function -Wno-conversion -Wno-misleading-indentation -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem /Users/pranavchiku/mambaforge/envs/scipy-dev/include -D_FORTIFY_SOURCE=2 -isystem /Users/pranavchiku/mambaforge/envs/scipy-dev/include -DCYTHON_CCOMPLEX=0 -Wno-cpp -MD -MQ scipy/signal/_upfirdn_apply.cpython-311-darwin.so.p/meson-generated__upfirdn_apply.c.o -MF scipy/signal/_upfirdn_apply.cpython-311-darwin.so.p/meson-generated__upfirdn_apply.c.o.d -o scipy/signal/_upfirdn_apply.cpython-311-darwin.so.p/meson-generated__upfirdn_apply.c.o -c scipy/signal/_upfirdn_apply.cpython-311-darwin.so.p/_upfirdn_apply.c
scipy/signal/_upfirdn_apply.cpython-311-darwin.so.p/_upfirdn_apply.c:26466:25: error: initializing '__pyx_t_float_complex' with an expression of incompatible type 'int'
  __pyx_t_float_complex __pyx_v_cval = 0;
                        ^              ~
scipy/signal/_upfirdn_apply.cpython-311-darwin.so.p/_upfirdn_apply.c:26944:20: error: assigning to '__pyx_t_float_complex' from incompatible type 'int'
      __pyx_v_cval = 0;
                   ^ ~
scipy/signal/_upfirdn_apply.cpython-311-darwin.so.p/_upfirdn_apply.c:27598:26: error: initializing '__pyx_t_double_complex' with an expression of incompatible type 'int'
  __pyx_t_double_complex __pyx_v_cval = 0;
                         ^              ~
scipy/signal/_upfirdn_apply.cpython-311-darwin.so.p/_upfirdn_apply.c:28076:20: error: assigning to '__pyx_t_double_complex' from incompatible type 'int'
      __pyx_v_cval = 0;
                   ^ ~
4 errors generated.
[1209/1588] Compiling C object scipy/signal/_sosfilt.cpython-311-darwin.so.p/meson-generated__sosfilt.c.o
ninja: build stopped: subcommand failed.
Build failed!
```

### SciPy/NumPy/Python version and system information

```shell
Apple mac m2 air
```

**Comment by tylerjereddy** [comment]
Cython `3.0.1` was released 7 hours ago, but not yet on PyPI it seems, but you are using it above.

I confirmed locally that we build with `3.0.0` but not `3.0.1` in standard Ubuntu Linux `venv`. We've had Cython folks helping us out recently so I imagine we can ping someone.

**Comment by tylerjereddy** [comment]
cc @matusvalo  perhaps

**Comment by matusvalo** [comment]
> cc @matusvalo perhaps

I will try to have a look. Adding also @da-woods

**Comment by da-woods** [comment]
I'm away from a computer for the next few days I'm afraid. Nothing obvious is jumping to mind as a possible cause. I'll have a look on Monday (if it's still unsolved then)

**Comment by ilayn** [comment]
The operation is typically allowed which is upcasting `0` to `0.0f+0.0fj`. So either a flag is overzealous or you might want to give it another go after `git clean -xdf`

**Comment by WarrenWeckesser** [comment]
I can reproduce the issue on Linux with Cython 3.0.1 (which is available on PyPI now).

Back in https://github.com/scipy/scipy/pull/18975, the following line was added to `meson.build`

    cython_c_args = ['-DCYTHON_CCOMPLEX=0'] # see gh-18975 for why we need this

which disables the use of a C native complex type in the code generated by Cython.  The complex type `__pyx_t_float_complex` in the code generated by Cython is then a C struct that looks like

    typedef struct { float real, imag; } __pyx_t_float_complex;

An instance of such a struct cannot be initialized by assigning 0 to it. That is why we get the compiler error

```
scipy/signal/_upfirdn_apply.cpython-311-x86_64-linux-gnu.so.p/_upfirdn_apply.c: In function ‘__pyx_fuse_1__pyx_f_5scipy_6signal_14_upfirdn_apply__pad_test’:
scipy/signal/_upfirdn_apply.cpython-311-x86_64-linux-gnu.so.p/_upfirdn_apply.c:26466:40: error: invalid initializer
26466 |   __pyx_t_float_complex __pyx_v_cval = 0;
      |                                        ^

```

So this looks like a bug in Cython 3.0.1.

**Comment by tylerjereddy** [comment]
I did a `git bisect` of Cython between tags `3.0.0` and `3.0.1`, on the ability to build SciPy `main`:

```
6776c96f66fc799c62be4d6d4022903a5e36cbb2 is the first bad commit
commit 6776c96f66fc799c62be4d6d4022903a5e36cbb2
Author: da-woods <dw-git@d-woods.co.uk>
Date:   Fri Aug 4 10:48:50 2023 +0100

    Fix using NULL as pointer default value for fused function arguments (#5578)
    
    In general, there is no need to go through a temp if the node is literal.
    
    Fixes https://github.com/cython/cython/issues/5554

 Cython/Compiler/FusedNode.py | 12 +++++++++---
 tests/run/fused_types.pyx    | 29 +++++++++++++++++++++++++++++
 2 files changed, 38 insertions(+), 3 deletions(-)
```

**Comment by certik** [comment]
To fix this bug at our CI, we simply maintain a custom branch for SciPy and applied the following patch:
```diff
--- a/environment.yml
+++ b/environment.yml
@@ -8,7 +8,7 @@ channels:
   - conda-forge
 dependencies:
   - python
-  - cython
+  - cython=3.0.0
   - compilers  # Currently unavailable for Windows. Comment out this line and download Rtools and add <path>\ucrt64\bin\ to your path: https://cran.r-project.org/bin/windows/Rtools/rtools40.html
   - meson
   - meson-python

```
We should probably fix the exact versions for all dependencies, to make the build very robust.

**Comment by WarrenWeckesser** [comment]
There is only one place where the bug is causing the build to fail, and that is the use of the default value `cval=0` in the function signature of the private function `_pad_test`:

https://github.com/scipy/scipy/blob/d2ab591e734c656c5f91214b0850323bd2a9a35c/scipy/signal/_upfirdn_apply.pyx#L236-L237

That function is only called in two places in [test_upfirdn.py](https://github.com/scipy/scipy/blob/main/scipy/signal/tests/test_upfirdn.py), and in both cases, the `cval` parameter is not given, so the default value 0 is always used.  To get CI passing again without pinning Cython to 3.0.0 and without waiting for a Cython bug fix, we could simply remove that parameter from `_pad_test`.  `_pad_test` is a private function that is only used in tests, so we can change it however we like.  We can restore that parameter whenever it is convenient after Cython is fixed, but there is actually no need to restore it until someone also writes some tests that actually use it.

**Comment by WarrenWeckesser** [comment]
Cython bug report: https://github.com/cython/cython/issues/5644

**Comment by ilayn** [comment]
It should resolve if we replace `0` with `0.` I think. I mean that much of flexibility should be allowed to ask from C.

**Comment by WarrenWeckesser** [comment]
@ilayn, that doesn't work.  It still generates code that tries to assign the value to a struct, and that is not valid C.  For valid C, the assignment would have to be something like

```
__pyx_t_float_complex __pyx_v_cval = {0.0, 0.0};
```

**Comment by ilayn** [comment]
I mean, a man can only dream I guess

**Comment by WarrenWeckesser** [comment]
The "flexibility" that you want would not work.  A C struct can contain arbitrary fields, such as character, pointers, floats, arrays of things, etc.  Assigning `0.0` to a struct just doesn't make sense.

The thing we should really be dreaming about is standardized, universally implemented complex types, so we wouldn't have to use a C struct to create a complex variable in the first place.  The biggest player preventing this dream from being realized has been Microsoft.

**Comment by ilayn** [comment]
Ah yes, MSVC crippled many shortcuts but before the C generated code I don't mean that part but instead Cython could have been handling this one.

**Comment by rgommers** [comment]
Thanks for working around the problem @WarrenWeckesser! Looks like the problem in SciPy is addressed and there's an upstream bug report, so we can close this issue.

> The thing we should really be dreaming about is standardized, universally implemented complex types

Dreaming, and continue to ask Microsoft each time they proudly announce how they're doing on C/C++ standard compliance:)

> We should probably fix the exact versions for all dependencies, to make the build very robust.

We can't do that for our actual dependencies in `pyproject.toml`, that's bad practice for a library. We could provide locked versions for dev setups, and I think that's what you meant? There's pros and cons - the "getting started" experience would be a little better probably, at the cost of finding these bugs later and the overhead of frequent lock file updates. In the end someone still has to report and fix bugs like these. 

I'm keeping an eye on [pixi](https://prefix.dev/docs/pixi/overview) for this though, it has real promise.

**Comment by certik** [comment]
@rgommers right, I think in `pyproject.toml` for a library you don't want to fix the dependencies, because you want to be flexible and allow users to use any versions they need.

At the same time, for our use case, the SciPy build simply started failing out of the blue at our CI. So I think we need to pick exact versions of SciPy dependencies that worked for us, and stick to that. Only upgrade manually when needed.

Yes, we would not find this bug if we already fixed the versions. In a way, it's a downside for you, but an upside for us. :)

**Comment by rgommers** [comment]
> So I think we need to pick exact versions of SciPy dependencies that worked for us, and stick to that. Only upgrade manually when needed.

That should be a little more robust I think. It's fairly rare for us to bump lower bounds of dependencies, and very rare to bump them so far to go over the most recent working version of them as of right now.

**Comment by matusvalo** [comment]
BTW Cython 3.0.2 was released with the issue fixed: https://github.com/cython/cython/releases/tag/3.0.2
