### ISSUE TITLE
BUG: build on pypy3.8-v7.3.7 fail

### ISSUE THREAD

**Issue by vmarunov** [scipy/scipy#15429]
### Describe your issue.

Build scipy on pypy3.8-v7.3.7 fail

pypy version:
```
Python 3.8.12 (9ef55f6fc369, Oct 24 2021, 20:11:54)
[PyPy 7.3.7 with GCC 7.3.1 20180303 (Red Hat 7.3.1-5)] on linux
Type "help", "copyright", "credits" or "license" for more information.
```

Trying with Cython version:
- 3.0.0a10
- 0.29.26
- 0.29.25
- 0.29.24

### Reproducing Code Example

```python
pip install scipy==1.7.3
```

### Error message

```shell
scipy/optimize/_highs/cython/src/_highs_wrapper.cxx:21737:1: error: too many initializers for ‘PyTypeObject’ {aka ‘_typeobject’}
  21737 | };
        | ^
  scipy/optimize/_highs/cython/src/_highs_wrapper.cxx:21859:1: error: too many initializers for ‘PyTypeObject’ {aka ‘_typeobject’}
  21859 | };
        | ^
  scipy/optimize/_highs/cython/src/_highs_wrapper.cxx:22123:1: error: too many initializers for ‘PyTypeObject’ {aka ‘_typeobject’}
  22123 | };
        | ^
  scipy/optimize/_highs/cython/src/_highs_wrapper.cxx:22272:1: error: too many initializers for ‘PyTypeObject’ {aka ‘_typeobject’}
  22272 | };
        | ^
```

### SciPy/NumPy/Python version information

numpy: 1.22.0, sys.version_info(major=3, minor=8, micro=12, releaselevel='final', serial=0)

**Comment by mattip** [comment]
This was fixed in [cython 0.29.27](https://docs.cython.org/en/stable/src/changes.html#id3). Please update.
