### ISSUE TITLE
BLD: pip install build issue with meson in Ubuntu virtualenv

### ISSUE THREAD

**Issue by tylerjereddy** [scipy/scipy#16300]
For non-editable `python -m pip install .` followed by `make html-scipyorg` I see the error below the fold working in a Python 3.10 virtualenv on Ubuntu. I can use the old `python setup.py install` for iterating locally for now, but @rgommers suggested we should fix before the `1.9.0rc1`.

<details>

```
mkdir -p build/html build/doctrees
LANG=C python3 -msphinx -WT --keep-going -t scipyorg  -b html -d build/doctrees  source build/html-scipyorg 
Running Sphinx v4.5.0

Traceback (most recent call last):
  File "/home/treddy/python_virtual_envs/python_310_scipy_general/lib/python3.10/site-packages/sphinx/config.py", line 332, in eval_config_file
    exec(code, namespace)
  File "/home/treddy/github_projects/scipy/doc/source/conf.py", line 22, in <module>
    import scipy._lib.uarray as ua
  File "/home/treddy/python_virtual_envs/python_310_scipy_general/lib/python3.10/site-packages/scipy/__init__.py", line 148, in <module>
    from scipy._lib._ccallback import LowLevelCallable
  File "/home/treddy/python_virtual_envs/python_310_scipy_general/lib/python3.10/site-packages/scipy/_lib/_ccallback.py", line 1, in <module>
    from . import _ccallback_c
ImportError: cannot import name '_ccallback_c' from 'scipy._lib' (/home/treddy/python_virtual_envs/python_310_scipy_general/lib/python3.10/site-packages/scipy/_lib/__init__.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/treddy/python_virtual_envs/python_310_scipy_general/lib/python3.10/site-packages/sphinx/cmd/build.py", line 272, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/home/treddy/python_virtual_envs/python_310_scipy_general/lib/python3.10/site-packages/sphinx/application.py", line 202, in __init__
    self.config = Config.read(self.confdir, confoverrides or {}, self.tags)
  File "/home/treddy/python_virtual_envs/python_310_scipy_general/lib/python3.10/site-packages/sphinx/config.py", line 165, in read
    namespace = eval_config_file(filename, tags)
  File "/home/treddy/python_virtual_envs/python_310_scipy_general/lib/python3.10/site-packages/sphinx/config.py", line 345, in eval_config_file
    raise ConfigError(msg % traceback.format_exc()) from exc
sphinx.errors.ConfigError: There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/home/treddy/python_virtual_envs/python_310_scipy_general/lib/python3.10/site-packages/sphinx/config.py", line 332, in eval_config_file
    exec(code, namespace)
  File "/home/treddy/github_projects/scipy/doc/source/conf.py", line 22, in <module>
    import scipy._lib.uarray as ua
  File "/home/treddy/python_virtual_envs/python_310_scipy_general/lib/python3.10/site-packages/scipy/__init__.py", line 148, in <module>
    from scipy._lib._ccallback import LowLevelCallable
  File "/home/treddy/python_virtual_envs/python_310_scipy_general/lib/python3.10/site-packages/scipy/_lib/_ccallback.py", line 1, in <module>
    from . import _ccallback_c
ImportError: cannot import name '_ccallback_c' from 'scipy._lib' (/home/treddy/python_virtual_envs/python_310_scipy_general/lib/python3.10/site-packages/scipy/_lib/__init__.py)


Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/home/treddy/python_virtual_envs/python_310_scipy_general/lib/python3.10/site-packages/sphinx/config.py", line 332, in eval_config_file
    exec(code, namespace)
  File "/home/treddy/github_projects/scipy/doc/source/conf.py", line 22, in <module>
    import scipy._lib.uarray as ua
  File "/home/treddy/python_virtual_envs/python_310_scipy_general/lib/python3.10/site-packages/scipy/__init__.py", line 148, in <module>
    from scipy._lib._ccallback import LowLevelCallable
  File "/home/treddy/python_virtual_envs/python_310_scipy_general/lib/python3.10/site-packages/scipy/_lib/_ccallback.py", line 1, in <module>
    from . import _ccallback_c
ImportError: cannot import name '_ccallback_c' from 'scipy._lib' (/home/treddy/python_virtual_envs/python_310_scipy_general/lib/python3.10/site-packages/scipy/_lib/__init__.py)
```
<details>

**Comment by rgommers** [comment]
Just to make sure, if instead of `make html-scipyorg` you run `python -c "import scipy; scipy.test()"`, does that work?

**Comment by tylerjereddy** [comment]
Here is the result of running `python -c "import scipy; scipy.test()"`

```
(python_310_scipy_general) treddy@adobe:~/github_projects/scipy/doc$ python -c "import scipy; scipy.test()"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/treddy/python_virtual_envs/python_310_scipy_general/lib/python3.10/site-packages/scipy/__init__.py", line 148, in <module>
    from scipy._lib._ccallback import LowLevelCallable
  File "/home/treddy/python_virtual_envs/python_310_scipy_general/lib/python3.10/site-packages/scipy/_lib/_ccallback.py", line 1, in <module>
    from . import _ccallback_c
ImportError: cannot import name '_ccallback_c' from 'scipy._lib' (/home/treddy/python_virtual_envs/python_310_scipy_general/lib/python3.10/site-packages/scipy/_lib/__init__.py)

```

If I do `cd /tmp` and then `python -m pytest --pyargs scipy` I get:

```
===================================================================================================================================== ERRORS =====================================================================================================================================
_________________________________________________________________________________________________________________________ ERROR collecting test session __________________________________________________________________________________________________________________________
/usr/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1050: in _gcd_import
    ???
<frozen importlib._bootstrap>:1027: in _find_and_load
    ???
<frozen importlib._bootstrap>:992: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:241: in _call_with_frames_removed
    ???
<frozen importlib._bootstrap>:1050: in _gcd_import
    ???
<frozen importlib._bootstrap>:1027: in _find_and_load
    ???
<frozen importlib._bootstrap>:1006: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:688: in _load_unlocked
    ???
<frozen importlib._bootstrap_external>:883: in exec_module
    ???
<frozen importlib._bootstrap>:241: in _call_with_frames_removed
    ???
/home/treddy/python_virtual_envs/python_310_scipy_general/lib/python3.10/site-packages/scipy/__init__.py:148: in <module>
    from scipy._lib._ccallback import LowLevelCallable
/home/treddy/python_virtual_envs/python_310_scipy_general/lib/python3.10/site-packages/scipy/_lib/_ccallback.py:1: in <module>
    from . import _ccallback_c
E   ImportError: cannot import name '_ccallback_c' from 'scipy._lib' (/home/treddy/python_virtual_envs/python_310_scipy_general/lib/python3.10/site-packages/scipy/_lib/__init__.py)
============================================================================================================================ short test summary info =============================================================================================================================
ERROR  - ImportError: cannot import name '_ccallback_c' from 'scipy._lib' (/home/treddy/python_virtual_envs/python_310_scipy_general/lib/python3.10/site-packages/scipy/_lib/__init__.py)
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
================================================================================================================================ 1 error in 0.15s ================================================================================================================================
```

The (PyPI wheel based) NumPy suite runs "ok" via `python -m pytest --pyargs numpy` in the same env.

**Comment by rgommers** [comment]
> `ImportError: cannot import name '_ccallback_c' from 'scipy._lib'`

This is the very first extension module that gets imported. There's a lot of reports floating around, and typically it means that the whole build/install is broken. We should improve the error message to say that.

@tylerjereddy are there any extension modules (`.so`'s) in your `python_310_scipy_general/lib/python3.10/site-packages/scipy/` install? If so, are they working if you import them like:
```
$ cd python_310_scipy_general/lib/python3.10/site-packages/scipy/_lib/
$ ipython
>>> import _ccallback_c
>>> import _fpumode
```
?

**Comment by rgommers** [comment]
I'm actually not sure what happened here, but we should and a `venv`-based CI job. I'll try to do that today.

**Comment by rgommers** [comment]
> This is the very first extension module that gets imported. There's a lot of reports floating around, and typically it means that the whole build/install is broken. We should improve the error message to say that.

Done in gh-16304

**Comment by tylerjereddy** [comment]
Your extension import test works just fine for `python setup.py install` and predictably fails for `python -m pip install -v .`, but maybe not for the reason you'd think--the extension files aren't even there!

- `cd /home/treddy/python_virtual_envs/python_310_scipy_general/lib/python3.10/site-packages/scipy/_lib/`
- `ls`

```
_bunch.py  _ccallback.py  decorator.py  deprecation.py  _disjoint_set.py  doccer.py  _docscrape.py  _gcutils.py  __init__.py  _pep440.py  __pycache__  tests  _testutils.py  _threadsafety.py  _tmpdirs.py  _uarray  uarray.py  _util.py
```
Here is the build log from the problematic `pip install . -v` redirected to a file: 
[build_log.txt](https://github.com/scipy/scipy/files/8793516/build_log.txt)

**Comment by rgommers** [comment]
Hmm, interesting. The build output looks fine, ending with:
```
  [1573/1573] Linking target scipy/optimize/_highs/_highs_wrapper.cpython-310-x86_64-linux-gnu.so
```
Installing `.so` files starts out okay, e.g.:
```
  Installing scipy/linalg/_matfuncs_expm.cpython-310-x86_64-linux-gnu.so to /home/treddy/github_projects/scipy/.mesonpy-j3f51rro/install/usr/lib/python3/dist-packages/scipy/linalg
  Stripping target 'scipy/linalg/_matfuncs_expm.cpython-310-x86_64-linux-gnu.so'.
  Installing scipy/linalg/_cythonized_array_utils.cpython-310-x86_64-linux-gnu.so to /home/treddy/github_projects/scipy/.mesonpy-j3f51rro/install/usr/lib/python3/dist-packages/scipy/linalg
```
Then we get to the next stage here:
```
  + meson setup --native-file=/home/treddy/github_projects/scipy/.mesonpy-native-file.ini -Ddebug=false -Dstrip=true -Doptimization=2 --prefix=/usr /home/treddy/github_projects/scipy /home/treddy/github_projects/scipy/.mesonpy-j3f51rro/build
  + meson compile
  + meson install --destdir /home/treddy/github_projects/scipy/.mesonpy-j3f51rro/install
  WARNING Using heuristics to map files to wheel, this may result in incorrect locations
  WARNING File matched Debian heuristic (scipy/__config__.py): /home/treddy/github_projects/scipy/.mesonpy-j3f51rro/install/usr/lib/python3/dist-packages/scipy/__config__.py (/usr/lib/python3/dist-packages/scipy/__config__.py)
  WARNING Could not tell if file was meant for purelib or platlib, so it was mapped to platlib: /home/treddy/github_projects/scipy/.mesonpy-j3f51rro/install/usr/lib/python3/dist-packages/scipy/__config__.py (/usr/lib/python3/dist-packages/scipy/__config__.py)
```
So far so good I think (the above warnings seem expected), but then here is where things go haywire:
```
  WARNING File could not be mapped to an equivalent wheel directory: /home/treddy/github_projects/scipy/.mesonpy-j3f51rro/install/usr/lib/python3/dist-packages/scipy/_lib/_ccallback_c.cpython-310-x86_64-linux-gnu.so ({moduledir_shared}/_ccallback_c.cpython-310-x86_64-linux-gnu.so)
...
  WARNING File could not be mapped to an equivalent wheel directory: /home/treddy/github_projects/scipy/.mesonpy-j3f51rro/install/usr/lib/python3/dist-packages/scipy/io/matlab/_mio5_utils.cpython-310-x86_64-linux-gnu.so ({moduledir_shared}/_mio5_utils.cpython-310-x86_64-linux-gnu.so)
  Copying files to wheel...
  [0/1105] scipy/__config__.py
...
  [1105/1105] scipy/io/_harwell_boeing/tests/test_hb.py
  Preparing metadata (pyproject.toml): finished with status 'done'
```
So it ends up including only pure Python files into the wheel.

Now the question is why. I'm pushing a working Ubuntu venv-based CI job PR in a minute - it works fine in a clean env/checkout. @tylerjereddy did you perhaps do `pip install .` after having already run `dev.py` or similar? I'm thinking perhaps the install `prefix` is messed up here.

**Comment by tylerjereddy** [comment]
Are there any meson/build artifacts that don't get cleaned by `git clean -xfd` combined with `python -m pip uninstall scipy` repeated until it can't find `scipy`?

**Comment by rgommers** [comment]
No, that should do it. I'm going to test `virtualenv` instead of `venv`.

**Comment by ev-br** [comment]
I wonder if it's a meson-python issue (dev.py build works for me locally on py3. 8)

**Comment by rgommers** [comment]
`virtualenv` works fine on Arch Linux too, I don't see a difference with `venv`. Should work on Debian/Ubuntu too, but would be good if @ev-br can confirm. Steps I took:
```
$ pip install virtualenv
$  virtualenv venv
$  source venv/bin/activate
$ pip install -U pip
$ pip install . -vv
```

Note that there are currently `1218` install targets; if you see `1105` then you're missing the extensions:
```
  Copying files to wheel...
  [0/1218] scipy/__config__.py
  [1/1218] scipy/version.py
  [2/1218] scipy/_lib/_ccallback_c.cpython-310-x86_64-linux-gnu.so
...
```

> I wonder if it's a meson-python issue (dev.py build works for me locally on py3. 8)

The above test uses `meson-python`.

**Comment by rgommers** [comment]
It's indeed the case though that this line is coming from `meson-python`:
```
WARNING File could not be mapped to an equivalent wheel directory: /home/treddy/github_projects/scipy/.mesonpy-j3f51rro/install/usr/lib/python3/dist-packages/scipy/_lib/_ccallback_c.cpython-310-x86_64-linux-gnu.so ({moduledir_shared}/_ccallback_c.cpython-310-x86_64-linux-gnu.so)
```
The [_map_from_heuristics](https://github.com/FFY00/meson-python/blob/main/mesonpy/__init__.py#L200) has Debian-specific handling, I just don't understand why it's going wrong here. Either way, it shouldn't silently discard install targets. @FFY00 can you enlighten us here?

**Comment by tylerjereddy** [comment]
I just reproduced the same issue with a fresh `venv` so I'm going to dump a bunch of info below the fold on my environment--I'll edit this comment shortly.

**Comment by rgommers** [comment]
GitHub Actions is on Ubuntu `20.04 LTS` still, while you are on `22.04 LTS`. That is likely to matter. The compiler version and installed Python packages won't matter; it's about paths to Python and what `sysconfig` contains.

**Comment by rgommers** [comment]
Ah, `22.04` is available (in beta), let me try that: https://github.com/actions/virtual-environments#available-environments

**Comment by tylerjereddy** [comment]
Also, *not* reproducible if I switch from the system Python `3.10.4` to Python `3.9.12` from `spack` (still using a fresh `venv`)--that might be helpful to know. (Same OS of course)

**Comment by rgommers** [comment]
Hmm, the GitHub action `setup-python` is unhelpful, it installs a custom Python into:
```
/opt/hostedtoolcache/Python/3.9.13/x64/bin/python
```
rather than the system one that has the problematic `dist-packages`. That's an annoying catch I didn't realize - need to use `apt` rather than the action.

**Comment by tylerjereddy** [comment]
Do you want this to be considered a blocker for branching or just something that would be good to backport during the rc phase (assuming an upstream Debian handling update doesn't just get automatically applied, depending on what meson stuff we have pinned on a release branch)?

**Comment by rgommers** [comment]
It only affects installs from source on one particular OS, so I think it's fine to create the release branch. I'll try to figure out what's up in the next few hours though, so it may pay off to wait that long.

**Comment by rgommers** [comment]
I can reproduce this in CI now: https://github.com/rgommers/scipy/runs/6644682267?check_suite_focus=true

**Comment by rgommers** [comment]
Extracting some more possibly relevant parts from CI:
```
 Program python3 found: YES (/home/runner/work/scipy/venvs/scipy-venv/bin/python)
...
   SciPy 1.9.0.dev0

    User defined options
      Native files: /tmp/pip-req-build-nkrtllrb/.mesonpy-native-file.ini
      debug       : false
      optimization: 2
      prefix      : /usr
      strip       : true
```

```
meson setup --native-file=/tmp/pip-req-build-nkrtllrb/.mesonpy-native-file.ini -Ddebug=false -Dstrip=true -Doptimization=2 --prefix=/usr /tmp/pip-req-build-nkrtllrb /tmp/pip-req-build-nkrtllrb/.mesonpy-vpgoe8v6/build
...
    Installing scipy/_lib/_ccallback_c.cpython-38-x86_64-linux-gnu.so to /tmp/pip-req-build-nkrtllrb/.mesonpy-q60hxu79/install/usr/lib/python3/dist-packages/scipy/_lib
    Stripping target 'scipy/_lib/_ccallback_c.cpython-38-x86_64-linux-gnu.so'.
...
    + meson setup --native-file=/tmp/pip-req-build-nkrtllrb/.mesonpy-native-file.ini -Ddebug=false -Dstrip=true -Doptimization=2 --prefix=/usr /tmp/pip-req-build-nkrtllrb /tmp/pip-req-build-nkrtllrb/.mesonpy-q60hxu79/build
    + meson compile
    + meson install --destdir /tmp/pip-req-build-nkrtllrb/.mesonpy-q60hxu79/install
    WARNING Using heuristics to map files to wheel, this may result in incorrect locations
    WARNING File matched Debian heuristic (scipy/__config__.py): /tmp/pip-req-build-nkrtllrb/.mesonpy-q60hxu79
...
    WARNING File could not be mapped to an equivalent wheel directory: /tmp/pip-req-build-nkrtllrb/.mesonpy-q60hxu79/install/usr/lib/python3/dist-packages/scipy/_lib/_ccallback_c.cpython-38-x86_64-linux-gnu.so ({moduledir_shared}/_ccallback_c.cpython-38-x86_64-linux-gnu.so)
```

**Comment by ev-br** [comment]
Indeed, repro locally on 

```
$ uname -a
Linux gonzales 5.13.0-41-generic #46~20.04.1-Ubuntu SMP Wed Apr 20 13:16:21 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
$ gcc --version
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

in a fresh virtualenv:

```
$ mkvirtualenv scrtch
(scrtch)$ pip install --upgrade pip
(scrtch)$ pip install .
```

leads to a broken build, reports  1105 targets.

**Comment by rgommers** [comment]
@tylerjereddy I won't be able to figure it out today. Fairly sure that it has to be fixed in `meson-python` though, and no changes needed in SciPy. So go ahead with creating the release branch I'd say.

**Comment by tylerjereddy** [comment]
Understood, branching tomorrow (Monday) is almost certain then.

**Comment by ev-br** [comment]
Given that meson >= 0.62 correctly handles debian derivatives including venvs with its `venv='auto'` switch, I actually wonder why pep517 wrapper even needs to handle it separately, and if it can does for some reason, whether it can just reuse relevant logic from meson itself.

**Comment by rgommers** [comment]
This was fixed in `meson-python` 0.6.0; it would still be good to finish the CI job I had in progress for this so we verify that it stays working.
