### ISSUE TITLE
ImportError: cannot import name 'factorial'

### ISSUE THREAD

**Issue by lambdaphy** [scipy/scipy#10252]
`from scipy.misc import factorial`

After upgrading to Scipy 1.3 from 1.1, the above import statement gives an error:

`ImportError: cannot import name 'factorial'`

Some packages depend on factorial function(e.g. statsmodels), so is this a bug?

**Comment by ilayn** [comment]
Hi @lambdaphy as mentioned on the 1.1 docs most of the `misc` module is deprecated. See the top warning here 

https://docs.scipy.org/doc/scipy-1.1.0/reference/generated/scipy.misc.factorial.html#scipy.misc.factorial
