### PR TITLE
CI: test distro Python install on Ubuntu Jammy (22.04 LTS)

### LINKED ISSUE #16300: BLD: pip install build issue with meson in Ubuntu virtualenv
For non-editable `python -m pip install .` followed by `make html-scipyorg` I see the error below the fold working in a Python 3.10 virtualenv on Ubuntu. I can use the old `python setup.py install` for iterating locally for now, but @rgommers suggested we should fix before the `1.9.0rc1`.

<details>

```
mkdir -p build/html build/doctrees
LANG=C python3 -msphinx -WT --keep-going -t scipyorg  -b html -d build/doctrees  source build/html-scipyorg 
Running Sphinx v4.5.0

Traceback (most recent call last):
  File "/home/treddy/python_virtual_envs/python_310_scipy_general/lib/python3.10/site-packages/sphinx/config.py", line 332, in eval_config_file
    exec(code, namespace)
  File "/home/treddy/github_projects/scipy/doc/source/conf.py", line 22, in <module>
    import scipy._lib.uarray as ua
  File "/home/treddy/python_virtual_envs/python_310_scipy_general/lib/python3.10/site-packages/scipy/__init__.py", line 148, in <module>
    from scipy._lib._ccallback import LowLevelCallable
  File "/home/treddy/python_virtual_envs/python_310_scipy_general/lib/python3.10/site-packages/scipy/_lib/_ccallback.py", line 1, in <module>
    from . import _ccallback_c
ImportError: cannot import name '_ccallback_c' from 'scipy._lib' (/home/treddy/python_virtual_envs/python_310_scipy_general/lib/python3.10/site-packages/scipy/_lib/__init__.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/treddy/python_virtual_envs/python_310_scipy_general/lib/python3.10/site-packages/sphinx/cmd/build.py", line 272, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/home/treddy/python_virtual_envs/python_310_scipy_general/lib/python3.10/site-packages/sphinx/application.py", line 202, in __init__
    self.config = Config.read(self.confdir, confoverrides or {}, self.tags)
  File "/home/treddy/python_virtual_envs/python_310_scipy_general/lib/python3.10/site-packages/sphinx/config.py", line 165, in read
    namespace = eval_config_file(filename, tags)
  File "/home/treddy/python_virtual_envs/python_310_scipy_general/lib/python3.10/site-packages/sphinx/config.py", line 345, in eval_config_file
    raise ConfigError(msg % traceback.format_exc()) from exc
sphinx.errors.ConfigError: There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/home/treddy/python_virtual_envs/python_310_scipy_general/lib/python3.10/site-packages/sphinx/config.py", line 332, in eval_config_file
    exec(code, namespace)
  File "/home/treddy/github_projects/scipy/doc/source/conf.py", line 22, in <module>
    import scipy._lib.uarray as ua
  File "/home/treddy/python_virtual_envs/python_310_scipy_general/lib/python3.10/site-packages/scipy/__init__.py", line 148, in <module>
    from scipy._lib._ccallback import LowLevelCallable
  File "/home/treddy/python_virtual_envs/python_310_scipy_general/lib/python3.10/site-packages/scipy/_lib/_ccallback.py", line 1, in <module>
    from . import _ccallback_c
ImportError: cannot import name '_ccallback_c' from 'scipy._lib' (/home/treddy/python_virtual_envs/python_310_scipy_general/lib/python3.10/site-packages/scipy/_lib/__init__.py)


Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/home/treddy/python_virtual_envs/python_310_scipy_general/lib/python3.10/site-packages/sphinx/config.py", line 332, in eval_config_file
    exec(code, namespace)
  File "/home/treddy/github_projects/scipy/doc/source/conf.py", line 22, in <module>
    import scipy._lib.uarray as ua
  File "/home/treddy/python_virtual_envs/python_310_scipy_general/lib/python3.10/site-packages/scipy/__init__.py", line 148, in <module>
    from scipy._lib._ccallback import LowLevelCallable
  File "/home/treddy/python_virtual_envs/python_310_scipy_general/lib/python3.10/site-packages/scipy/_lib/_ccallback.py", line 1, in <module>
    from . import _ccallback_c
ImportError: cannot import name '_ccallback_c' from 'scipy._lib' (/home/treddy/python_virtual_envs/python_310_scipy_general/lib/python3.10/site-packages/scipy/_lib/__init__.py)
```
<details>

### PR DESCRIPTION
**Pull request by rgommers**
This fixes the intent (using system Python) of this CI job, which was first added in gh-16309. Builds on Debian/Ubuntu are "special", because those distros patch `distutils`/`sysconfig` in ways that are quite unhelpful. The build was broken until `meson-python` 0.6.0

We want to keep this job running to guard against regressions. It's pretty quick to run, so costs little.

Closes gh-16300

### CODE REVIEW

**Comment by tupui** [comment]
From your description, did you want to change the Ubuntu distribution in `test_venv_install` instead of `test_meson`?

**Review by tupui — APPROVED** [review]
LGTM, `test_venv_install` is green. Thanks Ralf.

Related to your previous commit. Should we be concerned about the failure on `test_meson` when we have `ubuntu-22.04`?

**Comment by rgommers** [comment]
> Related to your previous commit. Should we be concerned about the failure on `test_meson` when we have `ubuntu-22.04`?

No, that was only due to `-Werror` usage in that job, which isn't a significant concern. We only use that flag on purpose in a single configuration, it's not doable to use it everywhere. Warnings with newer compilers are nice to tackle, but at our leisure.
