### PR TITLE
DOC: Add pybind11 requirment to HACKING.rst.txt

### PR DESCRIPTION
**Pull request by Kai-Striega**
The addition of the scipy.fft module (#10238) adds pybind11 as an additional
build time dependency. This has already been documented in
INSTALL.rst.txt (#10348) but not in HACKING.rst.txt. This commit adds
pybind11 to the required dependencies.

### CODE REVIEW

**Comment by Kai-Striega** [comment]
@larsoner if this seems OK would you merge this?

I'm not sure if you're the correct person to ask but it's a straight forward one-line change and you merged the INSTALL.rst.txt.

**Comment by larsoner** [comment]
@mdhaber okay with you to add this? It will require more work on your part to sort out in #10286.

Alternatively, if #10286 is 99% ready to go, you could just add this [there](https://github.com/scipy/scipy/pull/10286/files#diff-ff7a395fc10e317f57cd03639d848aebR26), or @Kai-Striega could make a PR into your branch.

**Comment by Kai-Striega** [comment]
@larsmans sorry I haven't kept up with #10286. I'll be happy to follow @mdhaber's lead on this one.

**Comment by mdhaber** [comment]
Thanks for catching this @larsoner. Yes I can work that into the rest of the documentation. @Kai-Striega I'll keep you posted.

**Comment by Kai-Striega** [comment]
Adding wontfix label as it will be added in #10286. I'll defer closing the PR until that PR has been merged.

**Comment by pv** [comment]
It probably should say what version of pybind11 is required.
It doesn't seem to build on pybind11 2.0.1 (the version on Debian stable).

**Comment by rgommers** [comment]
@peterbell10 do you know what the minimum requires version for `pybind11` is? Any released version is fine I think; for Cython we regularly require the latest version too. But if 2.1 or 2.2.x works, that'd be better given that 2.3.0 is less than a month old.

**Comment by peterbell10** [comment]
I've had a look at the changelog and I think the minimum is 2.2.0 because it uses `PYBIND11_MODULE`. However, I've been listing the minimum as 2.2.4 (September 2018) since that was the version used for development:
https://github.com/scipy/scipy/blob/1238d2d52eaf988cdd43b2173dd527c433d1818c/pyproject.toml#L9
https://github.com/scipy/scipy/blob/1238d2d52eaf988cdd43b2173dd527c433d1818c/setup.py#L474

Do these not actually change the setup behaviour?

**Comment by rgommers** [comment]
Thanks, 2.2.4 sounds good. Requiring the latest bugfix release of 2.2 (or any minor release) sounds like a healthy idea.

The `pyproject.toml` one is only involved when you'd do `pip install .` or `pip install -e .`

The `setup.py` one is correct and also helps when using `pip`, but doesn't actually do anything for `python setup.py build_ext -i`. If I uninstall pybind11 and run that, the failure shows up later:
```
scipy/fft/_pocketfft/pypocketfft.cxx:13:10: fatal error: 'pybind11/pybind11.h' file not found
#include <pybind11/pybind11.h>
         ^~~~~~~~~~~~~~~~~~~~~
1 error generated.
error: Command "g++ -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Users/rgommers/anaconda3/include -arch x86_64 -I/Users/rgommers/anaconda3/include -arch x86_64 -I/Users/rgommers/.local/include/python3.6m -I/Users/rgommers/anaconda3/include/python3.6m -I/Users/rgommers/anaconda3/lib/python3.6/site-packages/numpy/core/include -I/Users/rgommers/anaconda3/include/python3.6m -c scipy/fft/_pocketfft/pypocketfft.cxx -o build/temp.macosx-10.7-x86_64-3.6/scipy/fft/_pocketfft/pypocketfft.o -MMD -MF build/temp.macosx-10.7-x86_64-3.6/scipy/fft/_pocketfft/pypocketfft.o.d --std=c++14 -fvisibility=hidden -mmacosx-version-min=10.7 -stdlib=libc++" failed with exit status 1
```

Anyway, the code is fine, so if the docs say 2.2.4 we've done all we can do here I think - the rest is just Python build system annoyances
