### ISSUE TITLE
Build for master broken on OS X

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#7553]
Crap, missed something here in one of the ``ndimage`` refactoring PRs - the build is broken on OS X as of commit 9b576070d (Python 3.5, NumPy 1.13.0, OS X 10.12, Clang 8.1.0):

        scipy/ndimage/src/ni_morphology.c:470:13: warning: comparison of integers of different signs: 'npy_uint' (aka 'unsigned int') and 'int' [-Wsign-compare]
                    CASE_ERODE_POINT2(NPY_UINT, npy_uint,
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        scipy/ndimage/src/ni_morphology.c:317:55: note: expanded from macro 'CASE_ERODE_POINT2'
                if (_to != _bf_value && *(_type *)(_pi + _to) == _true) {             \
                                        ~~~~~~~~~~~~~~~~~~~~~ ^  ~~~~~
        scipy/ndimage/src/ni_morphology.c:476:13: warning: comparison of integers of different signs: 'npy_ulong' (aka 'unsigned long') and 'int' [-Wsign-compare]
                    CASE_ERODE_POINT2(NPY_ULONG, npy_ulong,
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        scipy/ndimage/src/ni_morphology.c:317:55: note: expanded from macro 'CASE_ERODE_POINT2'
                if (_to != _bf_value && *(_type *)(_pi + _to) == _true) {             \
                                        ~~~~~~~~~~~~~~~~~~~~~ ^  ~~~~~
        scipy/ndimage/src/ni_morphology.c:482:13: warning: comparison of integers of different signs: 'npy_ulonglong' (aka 'unsigned long long') and 'int' [-Wsign-compare]
                    CASE_ERODE_POINT2(NPY_ULONGLONG, npy_ulonglong,
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        scipy/ndimage/src/ni_morphology.c:317:55: note: expanded from macro 'CASE_ERODE_POINT2'
                if (_to != _bf_value && *(_type *)(_pi + _to) == _true) {             \
                                        ~~~~~~~~~~~~~~~~~~~~~ ^  ~~~~~
        In file included from scipy/ndimage/src/ni_morphology.c:32:
        In file included from scipy/ndimage/src/ni_support.h:42:
        In file included from scipy/ndimage/src/nd_image.h:38:
        In file included from /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/numpy/core/include/numpy/arrayobject.h:4:
        In file included from /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/numpy/core/include/numpy/ndarrayobject.h:27:
        /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/numpy/core/include/numpy/__multiarray_api.h:1453:1: warning: unused function '_import_array' [-Wunused-function]
        _import_array(void)
        ^
        4 warnings generated.
        /usr/bin/clang -bundle -undefined dynamic_lookup -arch i386 -arch x86_64 -g build/temp.macosx-10.6-intel-3.5/scipy/ndimage/src/nd_image.o build/temp.macosx-10.6-intel-3.5/scipy/ndimage/src/ni_filters.o build/temp.macosx-10.6-intel-3.5/scipy/ndimage/src/ni_fourier.o build/temp.macosx-10.6-intel-3.5/scipy/ndimage/src/ni_interpolation.o build/temp.macosx-10.6-intel-3.5/scipy/ndimage/src/ni_measure.o build/temp.macosx-10.6-intel-3.5/scipy/ndimage/src/ni_morphology.o build/temp.macosx-10.6-intel-3.5/scipy/ndimage/src/ni_support.o -Lbuild/temp.macosx-10.6-intel-3.5 -o scipy/ndimage/_nd_image.cpython-35m-darwin.so
        duplicate symbol __scipy_ndimage_ARRAY_API in:
            build/temp.macosx-10.6-intel-3.5/scipy/ndimage/src/nd_image.o
            build/temp.macosx-10.6-intel-3.5/scipy/ndimage/src/ni_filters.o
        duplicate symbol __scipy_ndimage_ARRAY_API in:
            build/temp.macosx-10.6-intel-3.5/scipy/ndimage/src/nd_image.o
            build/temp.macosx-10.6-intel-3.5/scipy/ndimage/src/ni_fourier.o
        duplicate symbol __scipy_ndimage_ARRAY_API in:
            build/temp.macosx-10.6-intel-3.5/scipy/ndimage/src/nd_image.o
            build/temp.macosx-10.6-intel-3.5/scipy/ndimage/src/ni_interpolation.o
        duplicate symbol __scipy_ndimage_ARRAY_API in:
            build/temp.macosx-10.6-intel-3.5/scipy/ndimage/src/nd_image.o
            build/temp.macosx-10.6-intel-3.5/scipy/ndimage/src/ni_measure.o
        duplicate symbol __scipy_ndimage_ARRAY_API in:
            build/temp.macosx-10.6-intel-3.5/scipy/ndimage/src/nd_image.o
            build/temp.macosx-10.6-intel-3.5/scipy/ndimage/src/ni_support.o
        duplicate symbol __scipy_ndimage_ARRAY_API in:
            build/temp.macosx-10.6-intel-3.5/scipy/ndimage/src/nd_image.o
            build/temp.macosx-10.6-intel-3.5/scipy/ndimage/src/ni_morphology.o
        ld: 6 duplicate symbols for architecture i386
        clang: error: linker command failed with exit code 1 (use -v to see invocation)
        duplicate symbol __scipy_ndimage_ARRAY_API in:
            build/temp.macosx-10.6-intel-3.5/scipy/ndimage/src/nd_image.o
            build/temp.macosx-10.6-intel-3.5/scipy/ndimage/src/ni_filters.o
        duplicate symbol __scipy_ndimage_ARRAY_API in:
            build/temp.macosx-10.6-intel-3.5/scipy/ndimage/src/nd_image.o
            build/temp.macosx-10.6-intel-3.5/scipy/ndimage/src/ni_fourier.o
        duplicate symbol __scipy_ndimage_ARRAY_API in:
            build/temp.macosx-10.6-intel-3.5/scipy/ndimage/src/nd_image.o
            build/temp.macosx-10.6-intel-3.5/scipy/ndimage/src/ni_interpolation.o
        duplicate symbol __scipy_ndimage_ARRAY_API in:
            build/temp.macosx-10.6-intel-3.5/scipy/ndimage/src/nd_image.o
            build/temp.macosx-10.6-intel-3.5/scipy/ndimage/src/ni_measure.o
        duplicate symbol __scipy_ndimage_ARRAY_API in:
            build/temp.macosx-10.6-intel-3.5/scipy/ndimage/src/nd_image.o
            build/temp.macosx-10.6-intel-3.5/scipy/ndimage/src/ni_support.o
        duplicate symbol __scipy_ndimage_ARRAY_API in:
            build/temp.macosx-10.6-intel-3.5/scipy/ndimage/src/nd_image.o
            build/temp.macosx-10.6-intel-3.5/scipy/ndimage/src/ni_morphology.o
        ld: 6 duplicate symbols for architecture i386
        clang: error: linker command failed with exit code 1 (use -v to see invocation)
        error: Command "/usr/bin/clang -bundle -undefined dynamic_lookup -arch i386 -arch x86_64 -g build/temp.macosx-10.6-intel-3.5/scipy/ndimage/src/nd_image.o build/temp.macosx-10.6-intel-3.5/scipy/ndimage/src/ni_filters.o build/temp.macosx-10.6-intel-3.5/scipy/ndimage/src/ni_fourier.o build/temp.macosx-10.6-intel-3.5/scipy/ndimage/src/ni_interpolation.o build/temp.macosx-10.6-intel-3.5/scipy/ndimage/src/ni_measure.o build/temp.macosx-10.6-intel-3.5/scipy/ndimage/src/ni_morphology.o build/temp.macosx-10.6-intel-3.5/scipy/ndimage/src/ni_support.o -Lbuild/temp.macosx-10.6-intel-3.5 -o scipy/ndimage/_nd_image.cpython-35m-darwin.so" failed with exit status 1

Will investigate tomorrow. Works fine on Linux, not clear what the difference is.

Also some warnings about unsigned int comparisons (more of the same that I didn't copy in).

**Comment by jaimefrio** [comment]
I have just rebuilt both numpy and scipy from scratch, both with Python 2.7 and 3.5, on OSX 10.12.5 with clang 8.1.0. SciPy was current master, NumPY a recent-ish master. 

I saw the same warning as you did, probably due to those uints I turned into ints that you spotted in #7549. Will send a PR shortly to silence those and other warnings.

But I had no problems building, which is weird because our setups are almost identical. The error is related to the changes introduced in #7537, and the way `PY_ARRAY_UNIQUE_SYMBOL` and `NO_IMPORT_ARRAY` are used there.

The mechanism is as follows:

`nd_image.o` is generated from compiling `nd_image.c`, which includes `nd_image.h` directly, which does a `#define PY_ARRAY_UNIQUE_SYMBOL _scipy_ndimage_ARRAY_API` before including `numpy/arrayobject.h`. As described in numpy/numpy#9309 this means that the NumPy API is declared there as `void *_scipy_ndimage_ARRAY_API;`.

All the other `*.o` files, which are generated from the corresponding `*.c` files, include `ni_support.h`, which does a `#define NO_IMPORT_ARRAY` before including `nd_image.h`. These means that, when the dust settles, the NumPy API should be declared as `extern void *_scipy_ndimage_ARRAY_API;` there, and the conflict should not happen.

Since I can't reproduce it I cannot debug it any further. If this is a real issue and not a byproduct of some old leftover files in your build, it should have started happening in https://github.com/scipy/scipy/pull/7537/commits/983a93de59425f6ae48900eb827a1b84e231b13e, perhaps you can git bisect before that one to confirm?

**Comment by rgommers** [comment]
It's a real issue, commit 983a93d is the first offending commit.

**Comment by jaimefrio** [comment]
How exactly did you build the code? I would like to reproduce it myself. Could it be related to the `-arch i386` thing? Will take a closer look tonight...

**Comment by rgommers** [comment]
$ git clean -xdf
    $ python setup.py build_ext -i

**Comment by rgommers** [comment]
> Could it be related to the `-arch i386` thing?

Could be. That's common for Python builds on OS X though.

**Comment by matthew-brett** [comment]
For the wheel builds, I think I gave up on i386 builds, on the basis that they were taking too long, and no-one was using them.

**Comment by rgommers** [comment]
I think that's a good idea, but unfortunately you get ``i386`` by default for some installers (like the one from python.org) for a basic ``python setup.py xxx``.

**Comment by rgommers** [comment]
The probably crucial detail:

    $ python
    Python 3.5.0 (v3.5.0:374f501f4567, Sep 12 2015, 11:00:19) 
    [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin

ran out of time for today

**Comment by jaimefrio** [comment]
I cannot reproduce the failure, but my build seems to only be doing the `-arch x86_64`.

There is something fishy, though... Here's a warning I'm seeing:

```
creating build/temp.macosx-10.5-x86_64-3.5/scipy/ndimage
creating build/temp.macosx-10.5-x86_64-3.5/scipy/ndimage/src
compile options: '-DNPY_NO_DEPRECATED_API=NPY_1_9_API_VERSION -DNO_ATLAS_INFO=3 -DHAVE_CBLAS -Iscipy/ndimage/src -I/Users/jaimefrio/miniconda/envs/numpydev35/lib/python3.5/site-packages/numpy-1.14.0.dev0+7a85008-py3.5-macosx-10.5-x86_64.egg/numpy/core/include -Iscipy/_lib/src -I/Users/jaimefrio/miniconda/envs/numpydev35/lib/python3.5/site-packages/numpy-1.14.0.dev0+7a85008-py3.5-macosx-10.5-x86_64.egg/numpy/core/include -I/Users/jaimefrio/miniconda/envs/numpydev35/include/python3.5m -c'
gcc: scipy/ndimage/src/ni_interpolation.c
In file included from scipy/ndimage/src/ni_interpolation.c:32:
In file included from scipy/ndimage/src/ni_support.h:42:
In file included from scipy/ndimage/src/nd_image.h:38:
In file included from /Users/jaimefrio/miniconda/envs/numpydev35/lib/python3.5/site-packages/numpy-1.14.0.dev0+7a85008-py3.5-macosx-10.5-x86_64.egg/numpy/core/include/numpy/arrayobject.h:4:
In file included from /Users/jaimefrio/miniconda/envs/numpydev35/lib/python3.5/site-packages/numpy-1.14.0.dev0+7a85008-py3.5-macosx-10.5-x86_64.egg/numpy/core/include/numpy/ndarrayobject.h:27:
/Users/jaimefrio/miniconda/envs/numpydev35/lib/python3.5/site-packages/numpy-1.14.0.dev0+7a85008-py3.5-macosx-10.5-x86_64.egg/numpy/core/include/numpy/__multiarray_api.h:1453:1: warning: unused function '_import_array' [-Wunused-function]
_import_array(void)
^
1 warning generated.
```

Here is some code created by [`generate_numpy_api.py`](https://github.com/numpy/numpy/blob/master/numpy/core/code_generators/generate_numpy_api.py):

```
#if defined(PY_ARRAY_UNIQUE_SYMBOL)
#define PyArray_API PY_ARRAY_UNIQUE_SYMBOL
#endif
#if defined(NO_IMPORT) || defined(NO_IMPORT_ARRAY)
extern void **PyArray_API;
#else
#if defined(PY_ARRAY_UNIQUE_SYMBOL)
void **PyArray_API;
#else
static void **PyArray_API=NULL;
#endif
#endif

...

#if !defined(NO_IMPORT_ARRAY) && !defined(NO_IMPORT)
static int
_import_array(void)
{
...
```

In theory things work as expected because we have `#define NO_IMPORT_ARRAY` and thus the numpy API is declared as `extern void **PyArray_API;`. But if `NO_IMPORT_ARRAY` is defined, then `_import_array` should not be defined, and we shouldn't be getting that warning.

**Comment by jaimefrio** [comment]
Hmmm... And I just did a clean build after removing the `#define NO_IMPORT_ARRAY` in `ni_support.h` and it completed successfully, so it seems it's being ignored, although I fail to understand why...

**Comment by jaimefrio** [comment]
If it wasn't so sad, the fix for this problem would be funny...
