### ISSUE TITLE
BLD:meson: Version 1.4.0 of meson leads to build error on Windows

### ISSUE THREAD

**Issue by ilayn** [scipy/scipy#20433]
When upgraded to `meson==1.4.0` from `meson==1.3.1` using pip the (clean) build failed with the following message

```bash
C:\Users\ilhan\Documents\GitHub\scipy [main ≡]> python dev.py build -j 8
>  ninja -C C:\Users\ilhan\Documents\GitHub\scipy\build -j 8
ninja: Entering directory `C:\Users\ilhan\Documents\GitHub\scipy\build'
[155/1477] Compiling C++ object scipy/special/_specfun.cp312-win_amd64.pyd.p/meson-generated__specfun.cpp.obj
scipy/special/_specfun.cp312-win_amd64.pyd.p/_specfun.cpp: In function 'PyTypeObject* __Pyx_ImportType_3_0_8(PyObject*, const char*, const char*, size_t, size_t, __Pyx_ImportType_CheckSize_3_0_8)':
scipy/special/_specfun.cp312-win_amd64.pyd.p/_specfun.cpp:11175:24: warning: unknown conversion type character 'z' in format [-Wformat=]
11175 |             "Expected %zd from C header, got %zd from PyObject",
      |                        ^
scipy/special/_specfun.cp312-win_amd64.pyd.p/_specfun.cpp:11175:47: warning: unknown conversion type character 'z' in format [-Wformat=]
11175 |             "Expected %zd from C header, got %zd from PyObject",
      |                                               ^
scipy/special/_specfun.cp312-win_amd64.pyd.p/_specfun.cpp:11174:13: warning: too many arguments for format [-Wformat-extra-args]
11174 |             "%s.%s size changed, may indicate binary incompatibility. "
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
11175 |             "Expected %zd from C header, got %zd from PyObject",
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[171/1477] Generating scipy/linalg/cython_linalg with a custom command (wrapped by meson to set env)
FAILED: scipy/linalg/cython_blas.pyx scipy/linalg/cython_lapack.pyx scipy/linalg/cython_blas.pxd scipy/linalg/cython_lapack.pxd scipy/linalg/_blas_subroutines.h scipy/linalg/_lapack_subroutines.h
"C:\Users\ilhan\AppData\Local\Programs\Python\Python312\Scripts\meson" "--internal" "exe" "--unpickle" "C:\Users\ilhan\Documents\GitHub\scipy\build\meson-private\meson_exe_python.exe_cc02ddd19a8d9360f52a2bd52c02a7b939a70bfb.dat"
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\ilhan\AppData\Local\Programs\Python\Python312\Scripts\meson.exe\__main__.py", line 7, in <module>
  File "C:\Users\ilhan\AppData\Local\Programs\Python\Python312\Lib\site-packages\mesonbuild\mesonmain.py", line 286, in main
    return run(sys.argv[1:], launcher)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ilhan\AppData\Local\Programs\Python\Python312\Lib\site-packages\mesonbuild\mesonmain.py", line 274, in run
    return run_script_command(args[1], args[2:])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ilhan\AppData\Local\Programs\Python\Python312\Lib\site-packages\mesonbuild\mesonmain.py", line 215, in run_script_command
    return module.run(script_args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ilhan\AppData\Local\Programs\Python\Python312\Lib\site-packages\mesonbuild\scripts\meson_exe.py", line 112, in run
    return run_exe(exe)
           ^^^^^^^^^^^^
  File "C:\Users\ilhan\AppData\Local\Programs\Python\Python312\Lib\site-packages\mesonbuild\scripts\meson_exe.py", line 35, in run_exe
    child_env = exe.env.get_env(child_env)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ilhan\AppData\Local\Programs\Python\Python312\Lib\site-packages\mesonbuild\utils\core.py", line 142, in get_env
    for name in self.unset_vars:
                ^^^^^^^^^^^^^^^
AttributeError: 'EnvironmentVariables' object has no attribute 'unset_vars'
[177/1477] Compiling C object scipy/special/_ufuncs.cp312-win_amd64.pyd.p/meson-generated__ufuncs.c.obj
```

Downgrading to 1.3.1 lead to a successful build. I don't know the cause and I don't have any bandwidth to investigate so just a heads up.

**Comment by rgommers** [comment]
Thanks for the report @ilayn. This looks like a Windows-specific regression due to https://github.com/mesonbuild/meson/pull/12357. I'll open an issue upstream.

Since it has to do with virtualenv & co somehow, can you tell me:
- how you installed Python?
- how you set up your build environment? (venv, conda env, or no separate env at all)

**Comment by rgommers** [comment]
Also, a hunch, since this problem does not occur for our nightly wheel builds on Windows - can you check if this fixes the problem:
```diff
diff --git a/dev.py b/dev.py
index fa198a1bc..0990fc90e 100644
--- a/dev.py
+++ b/dev.py
@@ -506,7 +506,7 @@ class Build(Task):
         """
         Build a dev version of the project.
         """
-        cmd = ["ninja", "-C", str(dirs.build)]
+        cmd = ["meson", "compile", "-C", str(dirs.build)]
         if args.parallel is None:
             # Use number of physical cores rather than ninja's default of 2N+2,
             # to avoid out of memory issues (see gh-17941 and gh-18443)

**Comment by ilayn** [comment]
> how you installed Python?

Just basic download from python.org and using the installer for 3.12.1. 

> how you set up your build environment? (venv, conda env, or no separate env at all)

No separate env. Just cloning the repo and using system wide installed Python

>  can you check if this fixes the problem

I will do that later in the day when I can get an access to my machine

**Comment by ilayn** [comment]
@rgommers  Upgraded to 1.4 again and used your fix and build passed without any problems.

**Comment by rgommers** [comment]
Great, thanks @ilayn. I'll open a PR with a more elaborate version of this change then. Still a regression, but at least we have a workaround.

**Comment by rgommers** [comment]
@ilayn, sorry one more request. Could you check in `build/build.ninja` what the lines that call `scipy/linalg/_generate_pyx.py` look like, with and without the patch above?

For me it looks like (on Linux):
```ninja
build scipy/linalg/cython_blas.pyx scipy/linalg/cython_lapack.pyx scipy/linalg/cython_blas.pxd scipy/linalg/cython_lapack.pxd scipy/linalg/_blas_subroutines.h scipy/linalg/_lapack_subroutines.h: CUSTOM_COMMAND ../scipy/linalg/_generate_pyx.py | ../scipy/linalg/cython_blas_signatures.txt ../scipy/linalg/cython_lapack_signatures.txt /home/rgommers/mambaforge/envs/scipy-dev/bin/python3.11
 COMMAND = env PYTHONPATH=/home/rgommers/code/scipy/scipy/_build_utils /home/rgommers/mambaforge/envs/scipy-dev/bin/python3.11 ../scipy/linalg/_generate_pyx.py -o scipy/linalg
 description = Generating$ scipy/linalg/cython_linalg$ with$ a$ custom$ command$ (wrapped$ by$ meson$ to$ set$ env)
```

Yours will contain this part:
```
"C:\Users\ilhan\AppData\Local\Programs\Python\Python312\Scripts\meson" "--internal" "exe" "--unpickle"
```
I'm curious about the difference here when invoking `ninja` vs. `meson compile` in `dev.py` - that should explain why it breaks I think.

**Comment by ilayn** [comment]
Oh my, I accidentally did `git clean -xdf` instead of the `meson setup --wipe build` now I cannot replicate any of this. 


This is the successful build with your fix applied 

```bash
build scipy/linalg/cython_blas.pyx scipy/linalg/cython_lapack.pyx scipy/linalg/cython_blas.pxd scipy/linalg/cython_lapack.pxd scipy/linalg/_blas_subroutines.h scipy/linalg/_lapack_subroutines.h: CUSTOM_COMMAND ../scipy/linalg/_generate_pyx.py | ../scipy/linalg/cython_blas_signatures.txt ../scipy/linalg/cython_lapack_signatures.txt C$:/Users/ilhan/AppData/Local/Programs/Python/Python312/python.exe
 COMMAND = "C:\Users\ilhan\AppData\Local\Programs\Python\Python312\Scripts\meson" "--internal" "exe" "--unpickle" "C:\Users\ilhan\Documents\GitHub\scipy\build\meson-private\meson_exe_python.exe_cc02ddd19a8d9360f52a2bd52c02a7b939a70bfb.dat"
 description = Generating$ scipy/linalg/cython_linalg$ with$ a$ custom$ command$ (wrapped$ by$ meson$ to$ set$ env)
```

My apologies I don't know what happened in between.

**Comment by rgommers** [comment]
No worries, that happens. In that case let's close this issue and leave `dev.py` unchanged. I'd like to see if anyone else will run into this. If not, then it was some weird way in which your environment became inconsistent and started picking up the wrong `meson` somehow.

**Comment by rgommers** [comment]
Okay, I think I figured out what happened. The discussion in https://github.com/mesonbuild/meson/pull/12357#issuecomment-2049973050 was helpful. gh-20450 should make things more robust.
