### PR TITLE
BLD: add back pyproject.toml

### PR DESCRIPTION
**Pull request by rgommers**
Closes gh-8734 (see that issue for details).

Want to add this now so we can test it for a while before the next release.

Note that I expect CI to fail at the moment, because of old `pip` versions. Will update those, want to see the failures first. Pip versions installed at the moment:
- TravisCI: pip 18.1
- Azure: pip 9.0.1
- CircleCI: pip 10.0.1
- Appveyor: 19.0.3

### CODE REVIEW

**Comment by rgommers** [comment]
Azure (with pip 9.0) failed with:
```
Exception: Building SciPy requires Cython >= 0.29.2
Cythonizing sources
Traceback (most recent call last):
  File "setup.py", line 488, in <module>
    setup_package()
  File "setup.py", line 472, in setup_package
    generate_cython()
  File "setup.py", line 249, in generate_cython
    raise RuntimeError("Running cythonize failed!")
RuntimeError: Running cythonize failed!
```

The CircleCI build with pip 10.0.1 looks fine (slightly unexpected to me).

I think it would be good to raise a more informative error when the build fails, e.g. by importing `pip` and checking its version number.

There are probably a lot of people still running pip 9.0, however they mostly won't be building from source. So I think it's fine adding `pyproject.toml` back.

**Comment by rgommers** [comment]
Next batch of Azure failures: on Linux it can't find `python3` (?), on Windows it says `Exception: Building SciPy requires Cython >= 0.29.2, found 0.28.5`. For the latter, we were specifying 0.28.5 before, bumping that to be consistent with `pyproject.toml`.

**Comment by rgommers** [comment]
Next Azure Linux error: `/usr/bin/python3: No module named ensurepip`. Apparently installing ensurepip is optional

**Comment by rgommers** [comment]
Can upgrade pip apparently, but then not use it:
```
Collecting pip
  Downloading https://files.pythonhosted.org/packages/d8/f3/413bab4ff08e1fc4828dfc59996d721917df8e8583ea85385d51125dceff/pip-19.0.3-py2.py3-none-any.whl (1.4MB)
Installing collected packages: pip
  Found existing installation: pip 9.0.1
    Not uninstalling pip at /usr/lib/python3/dist-packages, outside environment /usr
Successfully installed pip-19.0.3
Traceback (most recent call last):
  File "/usr/bin/pip3", line 9, in <module>
    from pip import main
ImportError: cannot import name 'main'
```

**Comment by rgommers** [comment]
Next issue, can't import `distutils.util` (https://github.com/pypa/get-pip/issues/43). Apparently the Ubuntu `python3.6` issue doesn't include distutils. Unbelievable how much of a mess Ubuntu makes of Python.

**Comment by rgommers** [comment]
This finally turned green. Squashed the last few commits, should be good to go now.

**Comment by larsoner** [comment]
I can take a look tomorrow. Need to learn about what this is and why it's useful first :( But it looks like that should be easy enough from the linked issues.

**Comment by rgommers** [comment]
> EDIT: sad face was meant to be happy

Sad faces are entirely appropriate for anything packaging related :)

The summary is: this is the way to add build requirements, pip uses those to build scipy against those exact dependencies in a fully isolated build environment (some tmpdir). Amongst the benefits:
- `easy_install` no longer gets invoked when using `setup_requires`
- scenarios like "user has numpy 1.16 installed, builds scipy, then installs numpy 1.15" will no longer result in a broken scipy install (because now it always gets built against the oldest numpy we support).

**Review by larsoner — APPROVED** [review]
Looks good to me, +1 for merge

**Comment by ilayn** [comment]
Looks good to me too, especially more informative warning/error printing parts so fingers crossed! Thanks @rgommers

**Comment by tacaswell** [comment]
This breaks building scipy with python 3.7+, it looks like the isolated env is hitting issues with changes to cpython internals (which goes back to 
https://github.com/cython/cython/issues/1955).  My guess is that the sdist for numpy contains pre-cythonized files which do not support py37.

Adding `--no-use-pep517` to the install incantation lets it install again.

The best fix may be to get numpy to put up a py37 wheel for 13.3.3

----

bisect


<details>

```
ea61eeb4a46edc30c7b9f2a93da8fef67af8b5f8 is the first bad commit
commit ea61eeb4a46edc30c7b9f2a93da8fef67af8b5f8
Author: Ralf Gommers <ralf.gommers@gmail.com>
Date:   Fri Mar 8 22:22:07 2019 -0800

    BLD: add back pyproject.toml.  Closes gh-8734

:000000 100644 0000000000000000000000000000000000000000 af59fc1bdb276c25b1c2b60c02a211274d78b79f A      pyproject.toml
```

</details>

build failure
<details>

```
      gcc: numpy/random/mtrand/mtrand.c
      numpy/random/mtrand/mtrand.c: In function ‘__Pyx__ExceptionSave’:
      numpy/random/mtrand/mtrand.c:45208:21: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_type’; did you mean ‘curexc_type’?
           *type = tstate->exc_type;
                           ^~~~~~~~
                           curexc_type
      numpy/random/mtrand/mtrand.c:45209:22: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_value’; did you mean ‘curexc_value’?
           *value = tstate->exc_value;
                            ^~~~~~~~~
                            curexc_value
      numpy/random/mtrand/mtrand.c:45210:19: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_traceback’; did you mean ‘curexc_traceback’?
           *tb = tstate->exc_traceback;
                         ^~~~~~~~~~~~~
                         curexc_traceback
      numpy/random/mtrand/mtrand.c: In function ‘__Pyx__ExceptionReset’:
      numpy/random/mtrand/mtrand.c:45217:24: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_type’; did you mean ‘curexc_type’?
           tmp_type = tstate->exc_type;
                              ^~~~~~~~
                              curexc_type
      numpy/random/mtrand/mtrand.c:45218:25: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_value’; did you mean ‘curexc_value’?
           tmp_value = tstate->exc_value;
                               ^~~~~~~~~
                               curexc_value
      numpy/random/mtrand/mtrand.c:45219:22: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_traceback’; did you mean ‘curexc_traceback’?
           tmp_tb = tstate->exc_traceback;
                            ^~~~~~~~~~~~~
                            curexc_traceback
      numpy/random/mtrand/mtrand.c:45220:13: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_type’; did you mean ‘curexc_type’?
           tstate->exc_type = type;
                   ^~~~~~~~
                   curexc_type
      numpy/random/mtrand/mtrand.c:45221:13: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_value’; did you mean ‘curexc_value’?
           tstate->exc_value = value;
                   ^~~~~~~~~
                   curexc_value
      numpy/random/mtrand/mtrand.c:45222:13: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_traceback’; did you mean ‘curexc_traceback’?
           tstate->exc_traceback = tb;
                   ^~~~~~~~~~~~~
                   curexc_traceback
      numpy/random/mtrand/mtrand.c: In function ‘__Pyx__GetException’:
      numpy/random/mtrand/mtrand.c:45277:24: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_type’; did you mean ‘curexc_type’?
           tmp_type = tstate->exc_type;
                              ^~~~~~~~
                              curexc_type
      numpy/random/mtrand/mtrand.c:45278:25: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_value’; did you mean ‘curexc_value’?
           tmp_value = tstate->exc_value;
                               ^~~~~~~~~
                               curexc_value
      numpy/random/mtrand/mtrand.c:45279:22: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_traceback’; did you mean ‘curexc_traceback’?
           tmp_tb = tstate->exc_traceback;
                            ^~~~~~~~~~~~~
                            curexc_traceback
      numpy/random/mtrand/mtrand.c:45280:13: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_type’; did you mean ‘curexc_type’?
           tstate->exc_type = local_type;
                   ^~~~~~~~
                   curexc_type
      numpy/random/mtrand/mtrand.c:45281:13: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_value’; did you mean ‘curexc_value’?
           tstate->exc_value = local_value;
                   ^~~~~~~~~
                   curexc_value
      numpy/random/mtrand/mtrand.c:45282:13: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_traceback’; did you mean ‘curexc_traceback’?
           tstate->exc_traceback = local_tb;
                   ^~~~~~~~~~~~~
                   curexc_traceback
      numpy/random/mtrand/mtrand.c: In function ‘__Pyx__ExceptionSave’:
      numpy/random/mtrand/mtrand.c:45208:21: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_type’; did you mean ‘curexc_type’?
           *type = tstate->exc_type;
                           ^~~~~~~~
                           curexc_type
      numpy/random/mtrand/mtrand.c:45209:22: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_value’; did you mean ‘curexc_value’?
           *value = tstate->exc_value;
                            ^~~~~~~~~
                            curexc_value
      numpy/random/mtrand/mtrand.c:45210:19: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_traceback’; did you mean ‘curexc_traceback’?
           *tb = tstate->exc_traceback;
                         ^~~~~~~~~~~~~
                         curexc_traceback
      numpy/random/mtrand/mtrand.c: In function ‘__Pyx__ExceptionReset’:
      numpy/random/mtrand/mtrand.c:45217:24: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_type’; did you mean ‘curexc_type’?
           tmp_type = tstate->exc_type;
                              ^~~~~~~~
                              curexc_type
      numpy/random/mtrand/mtrand.c:45218:25: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_value’; did you mean ‘curexc_value’?
           tmp_value = tstate->exc_value;
                               ^~~~~~~~~
                               curexc_value
      numpy/random/mtrand/mtrand.c:45219:22: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_traceback’; did you mean ‘curexc_traceback’?
           tmp_tb = tstate->exc_traceback;
                            ^~~~~~~~~~~~~
                            curexc_traceback
      numpy/random/mtrand/mtrand.c:45220:13: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_type’; did you mean ‘curexc_type’?
           tstate->exc_type = type;
                   ^~~~~~~~
                   curexc_type
      numpy/random/mtrand/mtrand.c:45221:13: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_value’; did you mean ‘curexc_value’?
           tstate->exc_value = value;
                   ^~~~~~~~~
                   curexc_value
      numpy/random/mtrand/mtrand.c:45222:13: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_traceback’; did you mean ‘curexc_traceback’?
           tstate->exc_traceback = tb;
                   ^~~~~~~~~~~~~
                   curexc_traceback
      numpy/random/mtrand/mtrand.c: In function ‘__Pyx__GetException’:
      numpy/random/mtrand/mtrand.c:45277:24: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_type’; did you mean ‘curexc_type’?
           tmp_type = tstate->exc_type;
                              ^~~~~~~~
                              curexc_type
      numpy/random/mtrand/mtrand.c:45278:25: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_value’; did you mean ‘curexc_value’?
           tmp_value = tstate->exc_value;
                               ^~~~~~~~~
                               curexc_value
      numpy/random/mtrand/mtrand.c:45279:22: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_traceback’; did you mean ‘curexc_traceback’?
           tmp_tb = tstate->exc_traceback;
                            ^~~~~~~~~~~~~
                            curexc_traceback
      numpy/random/mtrand/mtrand.c:45280:13: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_type’; did you mean ‘curexc_type’?
           tstate->exc_type = local_type;
                   ^~~~~~~~
                   curexc_type
      numpy/random/mtrand/mtrand.c:45281:13: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_value’; did you mean ‘curexc_value’?
           tstate->exc_value = local_value;
                   ^~~~~~~~~
                   curexc_value
      numpy/random/mtrand/mtrand.c:45282:13: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_traceback’; did you mean ‘curexc_traceback’?
           tstate->exc_traceback = local_tb;
                   ^~~~~~~~~~~~~
                   curexc_traceback
      error: Command "gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1 -D_LARGEFILE64_SOURCE=1 -Inumpy/core/include -Ibuild/src.linux-x86_64-3.8/numpy/core/include/numpy -Inumpy/core/src/private -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/home/tcaswell/.virtualenvs/bleeding/include -I/home/tcaswell/source/other_source/cpython/Include -I/home/tcaswell/source/other_source/cpython -Ibuild/src.linux-x86_64-3.8/numpy/core/src/private -Ibuild/src.linux-x86_64-3.8/numpy/core/src/npymath -Ibuild/src.linux-x86_64-3.8/numpy/core/src/private -Ibuild/src.linux-x86_64-3.8/numpy/core/src/npymath -Ibuild/src.linux-x86_64-3.8/numpy/core/src/private -Ibuild/src.linux-x86_64-3.8/numpy/core/src/npymath -c numpy/random/mtrand/mtrand.c -o build/temp.linux-x86_64-3.8/numpy/random/mtrand/mtrand.o -MMD -MF build/temp.linux-x86_64-3.8/numpy/random/mtrand/mtrand.o.d" failed with exit status 1
      Running setup.py install for numpy: finished with status 'error'


```

</details>

**Comment by charris** [comment]
Hmm, not sure if 1.13.3 works with 3.7+, although it may be that just a later cython is needed.

**Comment by tacaswell** [comment]
numpy v1.13.3 seems to build from source and passes all but 3 warning-related tests on py3.7.2.

**Comment by rgommers** [comment]
>This breaks building scipy with python 3.7+, it looks like the isolated env is hitting issues with changes to cpython internals (which goes back to
cython/cython#1955). 

To be sure: you mean 3.7 itself as well right, not just 3.8-dev?

> My guess is that the sdist for numpy contains pre-cythonized files which do not support py37.

Yes, sdists contains cythonized sources.

> Hmm, not sure if Numpy 1.13.3 works with 3.7+, although it may be that just a later cython is needed.

This has always worked AFAIK, and @tacaswell's check confirms it.

The first NumPy release that officially supports Python 3.7 is 1.15.0. Bumping to 1.15.4 isn't a good idea, because that's less than 6 months old. So we should do something about the 1.13.x issue.

> The best fix may be to get numpy to put up a py37 wheel for 13.3.3

That's not a complete fix, given that we cannot produce wheels for all platforms. And most 1.14.x releases also don't have py37 wheels, the first one that does is 1.14.5 which was released on 30 June 2018.

Also, I'd prefer not to add wheels for a release that do not correspond to the sdist for that same release.

The official Python 3.7 release date was [27 June 2018](https://www.python.org/dev/peps/pep-0537/#id10), so NumPy cut a release with support (1.14.5) for it right after. Therefore I think the right fix is to simply bump the minimum version for 3.7.

**Comment by tacaswell** [comment]
> To be sure: you mean 3.7 itself as well right, not just 3.8-dev?

Yes, fails on 3.7 and 3.8-dev (sorry for being slow to respond).
