### PR TITLE
MAINT: fixes XCode 12/ python 3.9.0 build for 1.5.x maint branch

### LINKED ISSUE #12860: BUG: Build failure with Xcode 12
Xcode 12 for OS X was just released, and I can't build scipy with it. The command `pip3 install . -v --user` fails, ending with
```
  error: Command "clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -DUSE_VENDOR_BLAS=1 -Iscipy/sparse/linalg/dsolve/SuperLU/SRC -I/private/var/folders/cp/n8wtqs490tq5psknff1hv9qr0000gn/T/pip-build-env-k4q2ai5g/overlay/lib/python3.8/site-packages/numpy/core/include -c scipy/sparse/linalg/dsolve/SuperLU/SRC/clacon2.c -o build/temp.macosx-10.15-x86_64-3.8/scipy/sparse/linalg/dsolve/SuperLU/SRC/clacon2.o -MMD -MF build/temp.macosx-10.15-x86_64-3.8/scipy/sparse/linalg/dsolve/SuperLU/SRC/clacon2.o.d" failed with exit status 1
  Building wheel for scipy (PEP 517): finished with status 'error'
  ERROR: Failed building wheel for scipy
Failed to build scipy
ERROR: Could not build wheels for scipy which use PEP 517 and cannot be installed directly
```

This may be the same issue as https://github.com/scipy/scipy/issues/12656 — at least the error at the end is the same — but that issue was closed while only providing the suggestion to use a different compiler. 

I am using Xcode 12, plus homebrew's Python 3.8, pip3, and gfortran. Unfortunately, I am really trying to figure out how to get this to build in Sage (sagemath.org), and using a gcc toolchain instead of clang would be, at the least, very inconvenient.

### LINKED ISSUE #12935: Failure to build with Python 3.9.0 on macOS
While rebuilding packages with Python 3.9.0 on macOS Homebrew (https://github.com/Homebrew/homebrew-core/pull/62560), we are seeing a failure to build scipy 1.5.2.

#### Reproducing code example:

```
/usr/local/opt/python@3.9/bin/python3 setup.py build --fcompiler=gnu95
```

#### Error message:

```
scipy/sparse/linalg/dsolve/SuperLU/SRC/clacon2.c:175:5: error: implicit declaration of function 'ccopy_' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
scipy/sparse/linalg/dsolve/SuperLU/SRC/dmach.c:62:9: error: implicitly declaring library function 'strncmp' with type 'int (const char *, const char *, unsigned long)' [-Werror,-Wimplicit-function-declaration]
scipy/sparse/linalg/dsolve/SuperLU/SRC/ilu_cdrop_row.c:196:3: error: implicit declaration of function 'scopy_' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
scipy/sparse/linalg/dsolve/SuperLU/SRC/ilu_zdrop_row.c:196:3: error: implicit declaration of function 'dcopy_' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
scipy/sparse/linalg/dsolve/SuperLU/SRC/smach.c:62:9: error: implicitly declaring library function 'strncmp' with type 'int (const char *, const char *, unsigned long)' [-Werror,-Wimplicit-function-declaration]
scipy/sparse/linalg/dsolve/SuperLU/SRC/zlacon2.c:175:5: error: implicit declaration of function 'zcopy_' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
scipy/sparse/linalg/dsolve/SuperLU/SRC/slacon2.c:160:16: error: implicit declaration of function 'idamax_' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
```

### PR DESCRIPTION
**Pull request by rlucas7**
#### Reference issue
Fixes #12935 Fixes #12860

#### What does this implement/fix?
Fixes compiler/build issue with python 3.9.0 

#### Additional information
see #12935 
This is a bit late for the 1.5.3 release but if we decide to do a 1.5.4 release this PR will fix the issue noted in associated github issue. 

Note: The issue mentioned in #12935 is fixed on master branch for 1.6.0 release, this PR ***does not*** need to be included in a 1.6.0 release.

### CODE REVIEW

**Comment by tylerjereddy** [comment]
Thanks, let's hold off on merging until I'm ready because we would want to bump the version on the maintenance branch first and I'm still doing release work there.

**Comment by rlucas7** [comment]
Yes, agreed 100%. Let me know if I can help, when we get there or in the interim.

Sincerely, 

-Lucas Roberts

**Comment by tylerjereddy** [comment]
Just a note for us to remember the situation--we may need to adopt a patch similar to this one to fix the XCode 12 + SciPy build issue: https://github.com/scipy/scipy/issues/12860#issuecomment-711096661 

Probably one of us should check before/after using patch on MacOS / XCode 12 locally.

File: scipy/spatial/qhull_src/src/libqhull_r.h [hunk 1]
```diff
@@ -37,6 +37,7 @@
 #include <limits.h>
 #include <time.h>
 #include <stdio.h>
+#include <string.h>
```
Comment (tylerjereddy) [inline scipy/spatial/qhull_src/src/libqhull_r.h:40]: @rlucas7 I've pushed in the larger patch that was recommended. I confirmed locally on a Mac with XCode 12 that there was a failure before/pass after applying this changeset.

However, I believe way may not need the qhull-related shims since I think I already backported something @pv reviewed a few weeks ago about this.

Maybe I'll find some time to try trimming this off the patch and seeing if a clean build still works..

Comment (rlucas7) [reply scipy/spatial/qhull_src/src/libqhull_r.h:40]: > @rlucas7 I've pushed in the larger patch that was recommended. I confirmed locally on a Mac with XCode 12 that there was a failure before/pass after applying this changeset.

@tylerjereddy  Good to hear that is a possible fix. 

> However, I believe way may not need the qhull-related shims since I think I already backported something @pv reviewed a few weeks ago about this.

I think when I tested this locally I had a branch off the maintenance branch 1.5.x so it already had some of the patches from other merged PRs that partially fixed. 
I didn't check the diff of the the maintenance/1.5.x branch against master though so there might be other stuff needed too. 
When I was suggesting the other patch I was referring to this one:
https://git.sagemath.org/sage.git/tree/build/pkgs/scipy/patches/extern_decls.patch?id=711fe05025795e44b84233e065d240859ccae5bd
which is linked here:
https://github.com/scipy/scipy/issues/12860#issuecomment-695172570
it looks like parts (maybe all?) of that patch would fix and it's a little more comprehensive than this one :) 
not sure if that's the patch you're looking at or not.  

> Maybe I'll find some time to try trimming this off the patch and seeing if a clean build still works.

Yeah I'm pretty busy with work this week, I might get some time the upcoming weekend on Sunday to take a look but depends on if I can get other things done quickly.

Comment (tylerjereddy) [reply scipy/spatial/qhull_src/src/libqhull_r.h:40]: Uhh, that is the patch that's applied here, yes. I'm saying we may not need the qhull part of it, that is all.

Comment (pv) [reply scipy/spatial/qhull_src/src/libqhull_r.h:40]: The qhull part was gh-12864

Comment (pv) [reply scipy/spatial/qhull_src/src/libqhull_r.h:40]: I didn't notice at the time that the PR closed the issue, even though some changes were left out, sorry.

Comment (rlucas7) [reply scipy/spatial/qhull_src/src/libqhull_r.h:40]: > Uhh, that is the patch that's applied here, yes. I'm saying we may not need the qhull part of it, that is all.

ok makes sense.

**Comment by tylerjereddy** [comment]
@andyfaff I've tried pulling in your CI changes to add Python 3.9 + XCode 12 MacOS here to see if this branch can pass; we are more confident in the patch for the `1.5.x` maintenance branch so fingers crossed on this one.

If this does work/pass the CI we can revisit `master` a little later so that I can focus on the release first.

I removed the qhull shims from the `sage` patch as well--that worked locally to transition from fail/succeed on XCode 12 build.

**Comment by tylerjereddy** [comment]
No wonder there's a problem I can't reproduce locally with this new CI--@andyfaff--I'm seeing it trying to build its own version of SciPy separate from the one under test:

```
Collecting scipy>=1.0.0rc1
  Downloading scipy-1.5.3.tar.gz (25.2 MB)
  Installing build dependencies: started
  Installing build dependencies: still running...
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
```

**Comment by tylerjereddy** [comment]
Looks like we've figured out the CI issue in gh-12937; once that is cleaned up and merged in I'll backport the CI change to `1.5.x` maintenance branch and we'll hopefully see the CI failure there & then confirm fix from a patch applied here after rebasing (already confirmed locally in any case, but good to see in CI as well).

**Comment by tylerjereddy** [comment]
The XCode 12 build bug is clearly fixed by this PR as shown by the CI now (vs. the maintenance branch CI) & concurs with local testing on XCode 12.1.

Most of the CI failures have fixes waiting/labelled for backporting. 

Some of the Travis CI fails are a bit strange though, and I believe @andyfaff and I saw (some of) those in gh-12937, at least for the pre-release NumPy wheels entries.

**Comment by tylerjereddy** [comment]
Ok, all CI failures are "ok" here because there are backports targeted for them in `1.5.4`.  The one exception is a sporadic precision issue that has already been discussed with Ralf as something we can ignore here: https://github.com/scipy/scipy/pull/12906#issuecomment-706767409
