### PR TITLE
BUG: fft: fix array-like input

### LINKED ISSUE #21207: BUG: `fft.hfftn` fails on list inputs
### Describe your issue.

The `fft.hfftn` function is documented to work on "array_like" inputs. My understanding of "array_like" is that it means anything that `numpy.array` can transform into a numpy array, including plain old Python lists.

The example below shows that `fft.hfftn` raises an `AttributeError: 'list' object has no attribute 'shape'`. If you change the example by adding `x = np.array(x)`, then it works fine.

As a first step toward debugging this: The change was introduced by https://github.com/scipy/scipy/pull/19263. In the parent commit of this PR, no error is raised, but after the PR, the error is raised.

### Reproducing Code Example

```python
from scipy.fft import hfftn

x = [[[1.0, 1.0], [1.0, 1.0]], [[1.0, 1.0], [1.0, 1.0]], [[1.0, 1.0], [1.0, 1.0]]]
hfftn(x)
```

### Error message

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/scipy/scipy/fft/_backend.py", line 28, in __ua_function__
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/scipy/scipy/fft/_basic_backend.py", line 154, in hfftn
    return _pocketfft.hfftn(x, s, axes, norm, overwrite_x, workers, plan=plan)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/scipy/scipy/fft/_pocketfft/basic.py", line 206, in c2rn
    shape[-1] = (x.shape[axes[-1]] - 1) * 2
                 ^^^^^^^
AttributeError: 'list' object has no attribute 'shape'
```

### SciPy/NumPy/Python version and system information

```shell
1.15.0.dev0+1043.bbe993d 1.26.4 sys.version_info(major=3, minor=12, micro=3, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /root/conda/envs/scipy-dev/include
    lib directory: /root/conda/envs/scipy-dev/lib
    name: openblas
    openblas configuration: USE_64BITINT=0 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK=0 NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP=0 PRESCOTT MAX_THREADS=128
    pc file directory: /root/conda/envs/scipy-dev/lib/pkgconfig
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /root/conda/envs/scipy-dev/include
    lib directory: /root/conda/envs/scipy-dev/lib
    name: openblas
    openblas configuration: USE_64BITINT=0 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK=0 NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP=0 PRESCOTT MAX_THREADS=128
    pc file directory: /root/conda/envs/scipy-dev/lib/pkgconfig
    version: 0.3.27
  pybind11:
    detection method: pkgconfig
    include directory: /root/conda/envs/scipy-dev/include
    name: pybind11
    version: 2.12.0
Compilers:
  c:
    args: -march=nocona, -mtune=haswell, -ftree-vectorize, -fPIC, -fstack-protector-strong,
      -fno-plt, -O2, -ffunction-sections, -pipe, -isystem, /root/conda/envs/scipy-dev/include,
      -DNDEBUG, -D_FORTIFY_SOURCE=2, -O2, -isystem, /root/conda/envs/scipy-dev/include
    commands: /root/conda/envs/scipy-dev/bin/x86_64-conda-linux-gnu-cc
    linker: ld.bfd
    linker args: -Wl,-O2, -Wl,--sort-common, -Wl,--as-needed, -Wl,-z,relro, -Wl,-z,now,
      -Wl,--disable-new-dtags, -Wl,--gc-sections, -Wl,--allow-shlib-undefined, -Wl,-rpath,/root/conda/envs/scipy-dev/lib,
      -Wl,-rpath-link,/root/conda/envs/scipy-dev/lib, -L/root/conda/envs/scipy-dev/lib,
      -march=nocona, -mtune=haswell, -ftree-vectorize, -fPIC, -fstack-protector-strong,
      -fno-plt, -O2, -ffunction-sections, -pipe, -isystem, /root/conda/envs/scipy-dev/include,
      -DNDEBUG, -D_FORTIFY_SOURCE=2, -O2, -isystem, /root/conda/envs/scipy-dev/include
    name: gcc
    version: 12.3.0
  c++:
    args: -fvisibility-inlines-hidden, -fmessage-length=0, -march=nocona, -mtune=haswell,
      -ftree-vectorize, -fPIC, -fstack-protector-strong, -fno-plt, -O2, -ffunction-sections,
      -pipe, -isystem, /root/conda/envs/scipy-dev/include, -DNDEBUG, -D_FORTIFY_SOURCE=2,
      -O2, -isystem, /root/conda/envs/scipy-dev/include
    commands: /root/conda/envs/scipy-dev/bin/x86_64-conda-linux-gnu-c++
    linker: ld.bfd
    linker args: -Wl,-O2, -Wl,--sort-common, -Wl,--as-needed, -Wl,-z,relro, -Wl,-z,now,
      -Wl,--disable-new-dtags, -Wl,--gc-sections, -Wl,--allow-shlib-undefined, -Wl,-rpath,/root/conda/envs/scipy-dev/lib,
      -Wl,-rpath-link,/root/conda/envs/scipy-dev/lib, -L/root/conda/envs/scipy-dev/lib,
      -fvisibility-inlines-hidden, -fmessage-length=0, -march=nocona, -mtune=haswell,
      -ftree-vectorize, -fPIC, -fstack-protector-strong, -fno-plt, -O2, -ffunction-sections,
      -pipe, -isystem, /root/conda/envs/scipy-dev/include, -DNDEBUG, -D_FORTIFY_SOURCE=2,
      -O2, -isystem, /root/conda/envs/scipy-dev/include
    name: gcc
    version: 12.3.0
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.10
  fortran:
    args: -march=nocona, -mtune=haswell, -ftree-vectorize, -fPIC, -fstack-protector-strong,
      -fno-plt, -O2, -ffunction-sections, -pipe, -isystem, /root/conda/envs/scipy-dev/include
    commands: /root/conda/envs/scipy-dev/bin/x86_64-conda-linux-gnu-gfortran
    linker: ld.bfd
    linker args: -Wl,-O2, -Wl,--sort-common, -Wl,--as-needed, -Wl,-z,relro, -Wl,-z,now,
      -Wl,--disable-new-dtags, -Wl,--gc-sections, -Wl,--allow-shlib-undefined, -Wl,-rpath,/root/conda/envs/scipy-dev/lib,
      -Wl,-rpath-link,/root/conda/envs/scipy-dev/lib, -L/root/conda/envs/scipy-dev/lib,
      -march=nocona, -mtune=haswell, -ftree-vectorize, -fPIC, -fstack-protector-strong,
      -fno-plt, -O2, -ffunction-sections, -pipe, -isystem, /root/conda/envs/scipy-dev/include
    name: gcc
    version: 12.3.0
  pythran:
    include directory: ../../../root/conda/envs/scipy-dev/lib/python3.12/site-packages/pythran
    version: 0.15.0
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
  cross-compiled: false
  host:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
Python Information:
  path: /root/conda/envs/scipy-dev/bin/python3.12
  version: '3.12'
```

### PR DESCRIPTION
**Pull request by lucascolley**
[skip cirrus]

#### Reference issue
Closes gh-21207

#### What does this implement/fix?
I have not ran the tests yet, just a guess. Maybe we want to check correctness in the unit test, too.

### CODE REVIEW

**Comment by lucascolley** [comment]
we should check the other functions in the `fft` submodule too

File: scipy/fft/tests/test_basic.py [hunk 1]
```diff
@@ -339,6 +339,24 @@ def test_dtypes_complex(self, dtype, xp):
...
+                                    fft.rfft2, fft.irfft2,
+                                    fft.rfftn, fft.irfftn,
+                                    fft.hfft, fft.ihfft,
+                                    fft.hfft2, fft.ihfft2,
+                                    fft.hfftn, fft.ihfftn,])
+    def test_array_like(self, xp, op):
+        x = [[[1.0, 1.0], [1.0, 1.0]],
+             [[1.0, 1.0], [1.0, 1.0]],
+             [[1.0, 1.0], [1.0, 1.0]]]
+        op(x) # should not error
```
Comment (lucascolley) [inline scipy/fft/tests/test_basic.py:357]: This seems like a better check

```suggestion
        xp_assert_close(op(x), op(xp.asarray(x)))
```

Comment (tylerjereddy) [reply scipy/fft/tests/test_basic.py:357]: Agreed. Apart from that, this branch seems array API test neutral on my local machine (no new issues) with GPU.

Note that you may have accidentally pushed your branch to the repo proper rather than your fork.

The diff is pretty clean, new test seems to run fast enough even with all the params.

Comment (lucascolley) [reply scipy/fft/tests/test_basic.py:357]: > Note that you may have accidentally pushed your branch to the repo proper rather than your fork.

Yep, I was using codespaces so it defaulted to that. Is that an issue, by the way? Sure, we wouldn't want a lot of branches cluttering the main repo, but are there any other issues with it?

Comment (tylerjereddy) [reply scipy/fft/tests/test_basic.py:357]: > but are there any other issues with it?

Not sure if there are any major issues with it, but my intuition is that an uptick in devs writing to the main repo branch space does at least slightly increased the risk of something annoying happening.

**Comment by lucascolley** [comment]
> we should check the other functions in the fft submodule too

Done - the Hankel transforms were bugged too.

**Review by j-bowhay — APPROVED** [review]
Thanks @lucascolley
